'use strict';
// S.time is the sole story/device clock, in minutes since 2026-09-13 00:00.
// Battery usage uses foreground elapsed time, not narrative time skips or photo count.
function ensureDevice(s){if(!s.deviceVitals){const legacy=Math.max(12,87-s.photos.length*5-Math.floor(s.elapsed/180000));s.deviceVitals={battery:legacy,initialBattery:legacy,activeMs:s.elapsed||0,lowPower:false,usage:{},warned:[]};}return s.deviceVitals;}
const beforeDeviceDefaults=v2Defaults;v2Defaults=s=>{beforeDeviceDefaults(s);ensureDevice(s);return s;};ensureDevice(S);
function deviceDate(){return new Date(Date.UTC(2026,8,13)+Math.floor(S.time*60000));}
function deviceDateLabel(){const d=deviceDate();return `${d.getUTCMonth()+1}月${d.getUTCDate()}日 星期${'日一二三四五六'[d.getUTCDay()]}`;}
function deviceTime(seconds=false){const d=deviceDate();return d.toISOString().slice(11,seconds?19:16);}
time=()=>deviceTime();
function batteryPercent(){return Math.ceil(ensureDevice(S).battery-1e-8);}
function batteryMarkup(){const d=ensureDevice(S),p=batteryPercent();return `<span class="battery live-battery ${d.lowPower?'saving':p<=20?'low':''}" data-live-battery role="img" aria-label="电量${p}%${d.lowPower?'，低电量模式':''}" style="--battery-level:${p}%"><i></i><b>${p}</b></span>`;}
renderStatus=()=>{$('#status').innerHTML=`<span data-live-time>${deviceTime()}</span><div class="island"></div><div class="vitals">${I('signal')}${I('wifi')}<span>4G</span>${batteryMarkup()}</div>`;syncDeviceReadouts();};
function liveClockIcon(){return `<svg viewBox="0 0 60 60" class="live-clock-icon" aria-hidden="true"><circle cx="30" cy="30" r="27"/><path d="M30 5v4M55 30h-4M30 55v-4M5 30h4"/><path data-clock-hand="hour" d="M30 30V17"/><path data-clock-hand="minute" d="M30 30V10"/><path data-clock-hand="second" d="M30 36V9"/><circle cx="30" cy="30" r="2" class="clock-pin"/></svg>`;}
const appIconBeforeDevice=appIcon;
appIcon=(id,dock=false)=>{if(id==='clock')return B('open',`<span class="appicon native-clock">${liveClockIcon()}</span><span>时钟</span>`,'app',{app:id});if(id==='calendar')return B('open',`<span class="appicon native-calendar"><small data-live-week>周${'日一二三四五六'[deviceDate().getUTCDay()]}</small><strong data-live-day>${deviceDate().getUTCDate()}</strong></span><span>日历</span>`,'app',{app:id});return appIconBeforeDevice(id,dock);};
const homeBeforeDevice=VIEWS.home;VIEWS.home=()=>homeBeforeDevice().replace(/<small>星期[日一二三四五六]<\/small><strong>\d+<\/strong>/,`<small data-live-week-long>星期${'日一二三四五六'[deviceDate().getUTCDay()]}</small><strong data-live-day>${deviceDate().getUTCDate()}</strong>`);
VIEWS.clock=()=>appHeader('时钟','home')+`<div class="scroll device-clock"><div class="clock-city">临川 · 本地时间</div><div class="large-clock">${liveClockIcon()}</div><strong data-live-time="seconds">${deviceTime(true)}</strong><p data-live-date>${deviceDateLabel()}</p><div class="clock-sun"><span>日出　05:42</span><span>日落　18:09</span></div></div>`;
const calendarBeforeDevice=VIEWS.calendar;VIEWS.calendar=()=>calendarBeforeDevice().replace('<form id="calendar-jump">',`<div class="calendar-today"><span data-live-date>${deviceDateLabel()}</span>${B('device-today','回到今天')}</div><form id="calendar-jump">`);
function usageRows(){const d=ensureDevice(S),rows=Object.entries(d.usage).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]),total=rows.reduce((sum,[,v])=>sum+v,0);return rows.length?rows.map(([app,drain])=>`<div class="device-usage-row"><span>${I(app==='home'?'home':app==='call'?'phone':app)}</span><div><b>${app==='call'?'语音通话':APP_NAMES[app]||'系统'}</b><div class="device-use-track"><i style="width:${Math.max(1,drain/total*100)}%"></i></div></div><small>${Math.round(drain/total*100)}%</small></div>`).join(''):'<p class="muted">使用手机后显示耗电记录。</p>';}
function batteryView(){const d=ensureDevice(S);return appHeader('电池','device-settings')+`<div class="scroll device-battery-page"><div class="battery-overview">${batteryMarkup()}<h2 data-battery-percent>${batteryPercent()}%</h2><p data-battery-mode>${d.lowPower?'低电量模式':'使用电池'}</p></div>${B('device-low-power',`<span>低电量模式<small>减少耗电，延长使用时间</small></span><span class="toggle ${d.lowPower?'on':''}"><i></i></span>`,'setting',{label:'切换低电量模式'})}<section class="device-usage"><div><h3>本次使用</h3><small data-device-duration>${Math.floor(d.activeMs/60000)}分钟</small></div><p>各应用耗电占比</p><div id="device-usage-list">${usageRows()}</div></section></div>`;}
const settingsBeforeDevice=VIEWS.settings;VIEWS.settings=()=>S.view==='battery'?batteryView():settingsBeforeDevice().replace(B('hint','需要一点提示'+I('next'),'setting'),B('device-battery',`<span>电池<small><span data-battery-percent>${batteryPercent()}%</span> · <span data-battery-mode>${ensureDevice(S).lowPower?'低电量模式':'使用电池'}</span></small></span>${I('next')}`,'setting')+B('hint','需要一点提示'+I('next'),'setting'));
function syncDeviceReadouts(){const d=ensureDevice(S),date=deviceDate(),p=batteryPercent();document.querySelectorAll('[data-live-time]').forEach(el=>{const value=deviceTime(el.dataset.liveTime==='seconds');if(el.textContent!==value)el.textContent=value;});document.querySelectorAll('[data-live-date]').forEach(el=>el.textContent=deviceDateLabel());document.querySelectorAll('[data-live-day]').forEach(el=>el.textContent=date.getUTCDate());document.querySelectorAll('[data-live-week]').forEach(el=>el.textContent='周'+'日一二三四五六'[date.getUTCDay()]);document.querySelectorAll('[data-live-week-long]').forEach(el=>el.textContent='星期'+'日一二三四五六'[date.getUTCDay()]);const secs=date.getUTCSeconds()+date.getUTCMilliseconds()/1000,mins=date.getUTCMinutes()+secs/60,hours=date.getUTCHours()%12+mins/60;document.querySelectorAll('[data-clock-hand]').forEach(el=>el.setAttribute('transform',`rotate(${({hour:hours*30,minute:mins*6,second:secs*6})[el.dataset.clockHand]} 30 30)`));document.querySelectorAll('[data-live-battery]').forEach(el=>{el.style.setProperty('--battery-level',p+'%');el.classList.toggle('saving',d.lowPower);el.classList.toggle('low',!d.lowPower&&p<=20);el.setAttribute('aria-label',`电量${p}%${d.lowPower?'，低电量模式':''}`);el.querySelector('b').textContent=p;});document.querySelectorAll('[data-battery-percent]').forEach(el=>el.textContent=p+'%');document.querySelectorAll('[data-battery-mode]').forEach(el=>el.textContent=d.lowPower?'低电量模式':'使用电池');document.querySelectorAll('[data-device-duration]').forEach(el=>el.textContent=Math.floor(d.activeMs/60000)+'分钟');const usage=$('#device-usage-list');if(usage&&usage.dataset.minute!==String(Math.floor(d.activeMs/60000))){usage.innerHTML=usageRows();usage.dataset.minute=Math.floor(d.activeMs/60000);}}
function drainDevice(ms,app,navigating){const d=ensureDevice(S);d.activeMs+=ms;const rates={home:.38,camera:.9,photos:.55,photo:.55,map:.55,call:.85,store:.6},base=rates[app]||.46,extra=navigating?.25:0,factor=d.lowPower?.6:1,wanted=(base+extra)*factor*ms/60000,drained=Math.min(Math.max(0,d.battery-5),wanted);d.battery=Math.max(5,d.battery-drained);d.usage[app]=(d.usage[app]||0)+drained*base/(base+extra);if(extra)d.usage.map=(d.usage.map||0)+drained*extra/(base+extra);if(!$('#modal').innerHTML&&!S.ending){const threshold=batteryPercent()<=10?10:batteryPercent()<=20?20:0;if(threshold&&!d.warned.includes(threshold)){d.warned.push(...[20,10].filter(v=>v>=threshold&&!d.warned.includes(v)));notify('电池电量低',`剩余电量${batteryPercent()}%，可在设置中开启低电量模式。`,'settings','battery');}}}
const advanceBeforeDevice=advance;let lastDeviceSecond=-1;let devicePaintElapsed=0;
advance=ms=>{if(document.hidden||!Number.isFinite(ms)||ms<=0)return;const before=S.time,active=S.app,app=$('.calling')?'call':active,navigating=!!(S.nav&&!S.nav.paused&&!S.arrived||S.phoneCase?.escape&&!S.phoneCase.escape.paused&&!S.ending);advanceBeforeDevice(ms);S.time=Math.max(S.time,before+ms/60000);drainDevice(ms,app,navigating);devicePaintElapsed+=ms;if(devicePaintElapsed>=1000||Math.floor(S.time*60)!==lastDeviceSecond){lastDeviceSecond=Math.floor(S.time*60);devicePaintElapsed%=1000;syncDeviceReadouts();}};
const renderBeforeDevice=render;render=()=>{renderBeforeDevice();syncDeviceReadouts();};
Object.assign(ACTIONS,{'device-battery':()=>open('settings','battery'),'device-settings':()=>open('settings'),'device-low-power':()=>{ensureDevice(S).lowPower=!ensureDevice(S).lowPower;save();render();},'device-today':()=>{const d=deviceDate();S.calendarYear=d.getUTCFullYear();S.calendarMonth=d.getUTCMonth()+1;S.calendarDay=d.getUTCDate();save();render();}});
const textBeforeDevice=window.render_game_to_text;window.render_game_to_text=()=>JSON.stringify({...JSON.parse(textBeforeDevice()),time:deviceTime(),device:{clock:deviceTime(true),date:deviceDateLabel(),battery:batteryPercent(),batteryExact:ensureDevice(S).battery,activeMs:ensureDevice(S).activeMs,lowPower:ensureDevice(S).lowPower,usage:ensureDevice(S).usage}});
window.addEventListener('pagehide',()=>save());save();render();

