'use strict';
// The night is a conversation, not a list of evidence to hand in.
const NIGHT_VERSION=4;
function newNight(){return {version:NIGHT_VERSION,phase:'calm',reassured:{},sleepMs:0,seenPhotos:[],talked:false,hrSeen:false,lurePhoto:null,lure:false,escapeStep:0,quiet:false,flashOff:false,read:[],failure:''};}
function migrateFriendName(value){if(typeof value==='string')return value.replaceAll('小满','小张是好bro').replaceAll('xiaoman_0921','zhang_bro_0921');if(Array.isArray(value))return value.map(migrateFriendName);if(value&&typeof value==='object')for(const key of Object.keys(value))value[key]=migrateFriendName(value[key]);return value;}
const defaultsBeforeNight=v2Defaults;
v2Defaults=s=>{defaultsBeforeNight(s);if(!s.friendNameVersion){migrateFriendName(s);s.friendNameVersion=1;}if(!s.night){s.night=newNight();if(s.checked){s.photos=[];s.uploads=[];s.marks={};s.queue=[];s.ending=null;s.taskReady=0;s.app='wechat';s.view='hr';s.messages.hr=[{self:true,text:'我已经进屋了。',at:time()},{text:'辛苦。先按App里的安排拍几张照片，然后休息。明早六点联系我就行。',at:time()}];for(const id of ['mom','friend'])s.messages[id]=(s.messages[id]||[]).filter(m=>!m.image&&!/门口|门外|原片|证据|唯一|照片|论坛|女人|备案/.test(m.text||''));delete s.messages.unknown;}s.phoneCase=null;s.onSiteLog=[];s.route=null;}
 s.forum??={tab:'全部',sort:'new',query:'',likes:[],saved:[],following:false,comments:{},posts:[],history:[],reads:[],user:null,loginError:'',drafts:{},notices:[],searches:[]};return s;};
v2Defaults(S);
const isHaunted=()=>['awake','escaping','escaped','lost'].includes(S.night.phase);
const ORIGINAL_GHOSTS=Object.fromEntries(ROOMS.map(r=>[r.id,r.photo]));
for(const r of ROOMS)Object.defineProperty(r,'photo',{get:()=>isHaunted()?ORIGINAL_GHOSTS[r.id]:r.live,configurable:true});
const originalRecruiterAvatar=recruiterAvatar;
recruiterAvatar=(j,cls='')=>originalRecruiterAvatar(j.id==='haunted'&&isHaunted()?{...j,avatar:'hr-zhou-ghost-v2.png'}:j,cls);
// Remove obsolete calendar-lock clues from otherwise ordinary social profiles.
POSTS.find(p=>p.id==='zhou2').text='这套房收拾好了。窗帘洗过，热水能用，床单今天换新。';
POSTS.find(p=>p.id==='zhou2').comments=[];
POSTS.find(p=>p.id==='zhou3').text='最近忙着接待看房，有事请威信留言。';
POSTS.find(p=>p.id==='xu1').text='后来发生的事，都写在佰度贴吧的临川吧了。账号：夜航不靠岸。';
PROFILES.hr.sign='房屋租赁 · 居住体验';
arrivalWx=()=>{if(!S.arrived||S.flags.keyGiven)return;appendWx('hr','我到6栋楼下了。',true);S.flags.keyGiven=true;wxQueue('hr',['门口值班的大叔会把钥匙给你。我已经跟他打过招呼了。','604。进屋后告诉我，App里有今晚的拍照安排。']);render();};
enterHouse=()=>{if(!S.arrived||!S.flags.keyGiven||S.checked)return;S.checked=true;S.currentRoom='hall';S.taskReady=0;S.time=Math.max(S.time,1438);S.night=newNight();appendWx('hr','拿到钥匙了，我已经进屋。灯和热水都正常。',true);wxQueue('hr',['好。App里先看拍摄要求，八个位置各拍一张就行。','拍完休息，明早六点联系我。']);close();open('wechat','hr');save();};
checkin=()=>S.flags.keyGiven?enterHouse():open('wechat','hr');
gatedRoom=id=>S.checked&&S.installed&&ROOMS.some(r=>r.id===id)&&ROOMS.findIndex(r=>r.id===id)<=S.taskReady;
capture=id=>{if(R.busy||S.ending)return;if(S.lens==='front'||!S.checked){S.savedImages.push(S.lens==='front'?'player-avatar.png':'wx-cover-lin-v6.png');save();tone('shutter');return notify('照片','照片已保存。','photos');}if(!gatedRoom(id))return;const first=!hasPhoto(id);if(first){S.photos.push({room:id,at:time(),date:S.time>=1440?'9月14日':'9月13日'});S.taskReady=nextPhotoTask();nowAdd(2);}tone('shutter');if(S.flash){$('#flash').className='on';setTimeout(()=>$('#flash').className='',180);}save();render();if(first)notify('照片','照片已保存。','photos');scheduleNightCheckins();};
const NORMAL_TASKS=['拍一张玄关，检查照明。','拍摄客厅，确认窗帘及家具状况。','拍摄厨房，确认灶具关闭、水槽无漏水。','拍摄餐厅，记录餐桌和餐边柜。','拍摄阳台，确认窗户关闭、晾衣架牢固。','拍摄浴室，确认洗手台和热水正常。','拍摄卧室，确认床品已经更换。','走近入户门，拍清门锁与门框。拍完就可以休息。'];
VIEWS.stay=()=>appHeader('安住验房','home',B('chat',I('wechat'),'',{id:'hr'}))+`<div class="scroll night-stay"><div class="night-booking"><small>今晚的预约</small><h2>槐安里 · 604</h2><p>9月13日 23:50 — 9月14日 06:00</p><div>林夏　·　夜间居住体验</div></div>${!S.checked?`<div class="pad"><h3>到达后联系负责人</h3><p>钥匙由门口值班处交接。入住安排在威信沟通。</p>${B(S.arrived?'chat':'map-booking',S.arrived?'联系周先生':'查看步行路线','primary',S.arrived?{id:'hr'}:{app:'map'})}</div>`:isHaunted()?`<div class="pad"><div class="night-service-off"><span>◌</span><h3>服务暂时无法连接</h3><p>上次连接　00:06<br>你的预约仍在进行中。</p></div>${B('chat','联系负责人','secondary',{id:'hr'})}</div>`:`<div class="pad"><h3>睡前拍摄安排</h3><p class="muted">${ROOMS.every(r=>hasPhoto(r.id))?'今晚的拍摄已完成。早点休息。':'照片自动保存在本机相册。'}</p>${ROOMS.map((r,i)=>i<=S.taskReady?B('night-task',`<span class="tasknum">${hasPhoto(r.id)?I('check'):'0'+(i+1)}</span><span class="tasktext"><b>${r.name}</b><small>${hasPhoto(r.id)?'已拍摄':NORMAL_TASKS[i]}</small></span>${I('next')}`,'taskrow',{id:r.id}):'').join('')}</div>`}</div>`;
VIEWS.photos=()=>appHeader('照片','home')+`<div class="scroll"><div class="pad"><h2>最近项目</h2><p class="muted">${S.photos.length+S.savedImages.length} 张照片 · 本机</p></div><div class="album night-album">${S.photos.map(p=>B('view-photo',`<img src="assets/${room(p.room).photo}" alt="${room(p.room).name}照片"><small>${p.at}</small>`,'',{id:p.room})).join('')}${S.savedImages.map((a,i)=>B('saved-view',`<img src="assets/${esc(a)}" alt="保存的图片">`,'',{index:i})).join('')}</div>${!S.photos.length&&!S.savedImages.length?'<p class="empty">还没有照片。</p>':''}</div>`;
VIEWS.photo=()=>{const r=room(S.view),p=S.photos.find(x=>x.room===r.id);if(!p)return appHeader('照片','photo-back')+'<p class="empty">没有这张照片。</p>';return appHeader((p.date||'9月13日')+' '+p.at,'photo-back',B('photo-details',I('dots'),'',{id:r.id}))+`<div class="photo-stage ${R.zoom?'zoomed':''}" id="photo-stage"><img draggable="false" src="assets/${r.photo}" alt="${r.name}照片"></div><div class="photo-info"><small>IMG_0913_0${ROOMS.indexOf(r)+1}.HEIC　${p.at}</small></div><div class="photo-tools">${B('night-photo-prev','‹ 上一张')}${B('zoom',R.zoom?'缩小':'放大')}${B('night-photo-share',I('upload')+'分享','',{id:r.id})}${B('night-photo-next','下一张 ›')}</div>`;};
const dailyWxChat=wxChat;
wxChat=id=>{if(!S.checked)return dailyWxChat(id);const msgs=S.messages[id]||[],pending=threadPending('wx',id),n=S.night;let choices=[];
 if(n.phase==='calm'){if(['mom','friend','dad'].includes(id)&&ROOMS.every(r=>hasPhoto(r.id))&&!n.reassured[id])choices=[['night-reassure','照片拍完了，这里一切正常。',{id}]];if(id==='friend'&&n.reassured.mom&&n.reassured.friend&&ROOMS.every(r=>hasPhoto(r.id)))choices=[['night-sleep','我先睡了，明早再聊。',{}]];if(id==='hr')choices=[['open','查看今晚的拍摄安排',{app:'stay'}]];}
 if(isHaunted()){if(id==='friend'){if(!n.talked){if(nightWakeMessagesReady())choices=[['night-panic','周先生开始说怪话，门窗也打不开了。',{}]];}else if(!n.lure)choices=[['night-friend-news','我再跟你说说刚才的事。',{}]];else if(n.escapeStep===0)choices=[['night-route','我去试试浴室的小窗。',{route:'bath'}],['night-route','我去开入户门。',{route:'door'}]];else if(n.escapeStep===1)choices=[['night-move','停住，屏住呼吸。',{move:'wait'}],['night-move','趁现在翻出去。',{move:'go'}]];else if(n.escapeStep===2)choices=[['night-move','继续等。',{move:'wait'}],['night-move','翻过小窗，往平台走。',{move:'go'}]];else if(n.escapeStep===3)choices=[['night-move','只看你的消息，沿右边走。',{move:'right'}],['night-move','回头看看是谁在叫我。',{move:'look'}]];}
 if(id==='hr')choices=n.lure?[]:[['night-hr','你为什么知道我醒了？',{text:'你为什么知道我醒了？'}],['night-hr','我还在床上，没醒。',{text:'我还在床上，没醒。'}]];
 if(id==='mom')choices=[['reply','妈，你在家吗？',{id:'mom',text:'妈，你在家吗？'}]];}
 return appHeader(pending?'对方正在输入…':personName(id),'wx-list',B('wx-profile',I('dots'),'',{id}))+`<div class="scroll chatbody" id="chatbody"><div class="chat-time">${msgs[0]?.at||time()}</div>${msgs.map(m=>m.system?`<div class="chat-time">${esc(m.text)}</div>`:`<div class="msg ${m.self?'self':''}">${avatarLink(m.self?'self':id)}${(m.image||m.mediaAsset)?wxPhotoBubble(m):`<div class="bubble">${esc(m.text)}</div>`}</div>`).join('')}${pending?'<div class="typing-dots"><i></i><i></i><i></i></div>':''}</div>${choices.length&&!pending?`<div class="chat-choices">${choices.map(([a,l,d])=>B(a,l,'',d)).join('')}</div>`:''}<form class="composer" id="chat-form" data-id="${id}">${B('call',I('sound'),'',{id})}<input id="chat-input" aria-label="消息" maxlength="300" autocomplete="off" value="${esc(S.drafts[id]||'')}">${B('wx-attach',I('plus'),'',{id})}<button class="send" type="submit">发送</button></form>`;};
function scheduleNightCheckins(){
 if(!S.checked||S.night.phase!=='calm'||!ROOMS.every(r=>hasPhoto(r.id))||S.ending)return;
 const n=S.night;n.checkins??={};
 for(const [id,text,delay] of [['friend','到了没？那边住着怎么样，还顺利吗？',2800],['mom','睡了没？今晚的工作还顺利吗？',4200]]){
  if(n.checkins[id])continue;n.checkins[id]=true;
  if(!n.reassured[id])wxQueue(id,[{text,delay,event:'night-checkin'}]);
 }
 save();
}
function nightReassure(id){if(S.night.phase!=='calm'||!ROOMS.every(r=>hasPhoto(r.id))||S.night.reassured[id]||threadPending('wx',id))return;appendWx(id,'照片拍完了，屋里干净，热水也有。一切正常，不用担心。',true);wxQueue(id,[id==='mom'?'那就好。被子盖好，别着凉。':'那就好。明早发工资了记得请我吃饭。',{text:id==='mom'?'早点睡，明早跟妈说一声。':'我明天早起，你醒了找我。',event:'night-reassured'}]);render();}
function nightSleep(){if(S.night.phase!=='calm'||!S.night.reassured.mom||!S.night.reassured.friend||!ROOMS.every(r=>hasPhoto(r.id)))return;appendWx('friend','我先睡了，明早再聊。',true);wxQueue('friend',[{text:'晚安，做个好梦。',event:'night-sleep'}]);render();}
function nightWakeMessagesReady(){return S.night.wakeIntroDone??(S.night.talked||S.night.lure||(S.messages.hr||[]).some(m=>!m.self&&(m.event==='night-awake-ready'||m.text==='别把脚伸到床外。下面那个人，等了很久。')));}
function nightWake(){S.night.wakeIntroDone=false;S.night.phase='awake';S.time=Math.max(S.time+60,1573);S.queue=[];S.night.sleepMs=0;S.messages.friend.push({text:time(),system:true,at:time()});wxQueue('hr',[{text:'你睡着的时候，为什么一直看着门？',delay:0,forceNotify:true},'照片里明明只有一张床。','你睡在里面。外面那个人，是谁？',{text:'别把脚伸到床外。下面那个人，等了很久。',event:'night-awake-ready'}],2200);stepDeliveries(0);save();render();}
function nightPanic(){if(!isHaunted()||S.night.talked||!nightWakeMessagesReady())return;S.night.talked=true;appendWx('friend','周先生突然说床下有人。我试了门和窗，全部打不开。',true);wxQueue('friend',['我在。你先别回应他。','你去biss看看，还是之前那个人吗？再看一眼睡前的照片。','地址发给我。我去楼下接你，你试着在网上搜搜这房子以前发生过什么。']);render();}
function nightHr(text){appendWx('hr',text,true);if(S.night.lurePhoto==='bed'&&/还在床上|没醒|睡着/.test(text)){S.night.lure=true;wxQueue('hr',['照片收到了。','床上果然还有人。',{text:'我进去看看。你继续睡。',event:'night-lured'}],1800);}else wxQueue('hr',[/醒/.test(text)?'是吗。可你发消息的手，在被子外面。':'把卧室的照片发来。我看看你睡在哪边。']);render();}
const beforeNightReply=reply;
reply=wxReply=(id,text)=>{text=text.trim();if(!text)return;if(!S.checked)return beforeNightReply(id,text);S.drafts[id]='';if(S.night.phase==='calm'&&ROOMS.every(r=>hasPhoto(r.id))&&['mom','friend','dad'].includes(id)&&!S.night.reassured[id])return nightReassure(id);if(S.night.phase==='calm'&&id==='friend'&&/睡|晚安/.test(text))return nightSleep();if(isHaunted()&&id==='hr')return nightHr(text);if(isHaunted()&&id==='friend'&&!S.night.talked)return nightPanic();appendWx(id,text,true);if(threadPending('wx',id))return render();wxQueue(id,[isHaunted()?id==='mom'?'我在家。刚睡醒，怎么了小夏？别怕，妈在这儿。':id==='friend'?'我没走。你慢慢查，想到什么就跟我说。别相信门外叫你名字的声音。':'我在。你把地址发我，先别着急。':id==='hr'?'拍完就休息，明早联系。':'好，早点休息，明早聊。']);save();render();};
shareFriend=()=>{if(!S.photos.length)return;for(const p of S.photos)appendWx('friend','',true,{image:p.room});wxQueue('friend',[isHaunted()?'这几张不是你睡前拍的吗？窗帘后面那张脸……你刚才明明说没人。':'照片看着挺正常，早点休息吧。']);open('wechat','friend');};
function nightShare(id,to){if(!hasPhoto(id))return;appendWx(to,'',true,{image:id});if(to==='hr'&&isHaunted()){S.night.lurePhoto=id;wxQueue('hr',[id==='bed'?'床上的人还在。你呢？':'我要看床。拍你睡的地方。']);}else wxQueue(to,[isHaunted()?'你没修图吧？拍照时间还是睡前……那个人怎么会在里面？':'收到，看着挺好的。']);save();open('wechat',to);}
function nightRoute(route){if(!S.night.lure||S.night.escapeStep!==0)return;if(route!=='bath')return nightLose('你拧开了入户门。门外还是同一间卧室，床上躺着一个正在拧门把手的你。');if(!S.night.quiet||S.flash){appendWx('friend','我靠近窗边，又听到脚步朝这里过来。',true);wxQueue('friend',[{text:'刚才手机有动静，脚步就停在门口了。',self:true},'先退回来，别急，别再弄出动静。']);return render();}S.night.phase='escaping';S.night.escapeStep=1;appendWx('friend','浴室小窗松了。外面是检修平台，我能出去。',true);wxQueue('friend',['我到楼下了。你沿平台往右，消防梯在右边。',{text:'门外敲了一下。',self:true,event:'night-knock'},{text:'门把手在慢慢转，我现在不敢动。',self:true}],1600);render();}
function nightMove(move){const n=S.night;if(n.escapeStep===1){if(move!=='wait')return nightLose('你跨出窗沿时，身后的手抓住了脚踝。那一声敲门，是在听你动没动。');n.escapeStep=1.5;appendWx('friend','我停住了。',true);wxQueue('friend',[{text:'等了好久，外面没声音了。',self:true,delay:2600},{text:'又敲了三下。咚、咚、咚。',self:true,delay:2200,event:'night-three'},{text:'脚步声回卧室了。',self:true,delay:1200}]);}else if(n.escapeStep===2){if(move==='wait'){appendWx('friend','我再等一下。',true);wxQueue('friend',['我在下面。看好脚下，等你觉得安全再过来。']);}else{n.escapeStep=3;appendWx('friend','我翻出来了，在平台上。',true);wxQueue('friend',['看脚下，沿右边过来。',{text:'身后有人喊“小夏，别走，妈在你后面”。声音跟我妈一模一样。',self:true,delay:2400}]);}}else if(n.escapeStep===3){if(move==='look')return nightLose('你回头，看见妈妈站在六楼窗外。她的脚没有踩着任何东西。');n.escapeStep=4;appendWx('friend','我只看你发的消息。我沿右边走。',true);wxQueue('friend',['我看见你了。抓住栏杆，慢慢下来。',{text:'林夏，抬头。我就在这里。',event:'night-escaped',delay:2000}]);}save();render();}
function nightLose(why){S.night.failure=why;S.night.phase='lost';S.ending='trapped';S.queue=[];save();open('ending');scare('你听见自己的声音，从床下传出来。');}
function nightCheckpoint(){GameStorage.checkpoint(S);}
restore=()=>{let cp;try{cp=JSON.parse(localStorage.getItem(CHECKPOINT));}catch{}if(!cp?.night)return sheet('重新体验这一夜',B('night-retry-calm','从进屋开始','primary'));const settings=S.settings;S=v2Defaults(cp);S.settings=settings;S.ending=null;R.scareLeft=0;$('#scare').className='';S.queue=[];S.app='wechat';S.view='hr';save();render();};
const beforeNightDelivery=deliveryEvent;
deliveryEvent=q=>{beforeNightDelivery(q);const n=S.night;if(q.event==='night-reassured')n.reassured[q.id]=true;if(q.event==='night-sleep'){n.phase='sleeping';n.sleepMs=0;}if(q.event==='night-awake-ready'){n.wakeIntroDone=true;nightCheckpoint();if(S.app==='wechat'&&S.view==='friend')refreshThread('wx','friend');}if(q.event==='night-lured')wxQueue('friend',[{text:'卧室的床架响了一声，像有人坐下了。',self:true},{text:'我快到了。你那边现在怎么样？'}]);if(q.event==='night-knock')tone('knock');if(q.event==='night-three'){n.escapeStep=2;tone('knock');}if(q.event==='night-escaped'){n.phase='escaped';S.ending='escape';open('ending');}save();};
const beforeNightAdvance=advance;advance=ms=>{v2Defaults(S);beforeNightAdvance(ms);if(document.hidden)return;scheduleNightCheckins();if(S.night.phase==='sleeping'){S.night.sleepMs+=ms;if(S.night.sleepMs>=6500)nightWake();}};
const beforeNightOpen=open;open=(app,view='')=>{beforeNightOpen(app,view);if(app==='biss'&&isHaunted()&&!S.night.hrSeen){S.night.hrSeen=true;save();}if(app==='photo'&&isHaunted()&&!S.night.seenPhotos.includes(view)){S.night.seenPhotos.push(view);save();if(view==='bed'&&S.settings.intense)scare('照片没有重新拍过。');}};
call=id=>{S.calls.push({at:time(),name:PEOPLE[id]?.name||'110',status:isHaunted()?'信号断续':'通话结束'});sheet(PEOPLE[id]?.name||'110',`<div class="calling">${id in PEOPLE?AV(id):I('phone')}<p>${isHaunted()?id==='hr'?'听筒里传来你自己的呼吸。隔了一秒，床下也响起相同的声音。':id==='police'?'接警员：有人正在赶往槐安里，先待在安全的位置，保持联系。':id==='friend'?'小张是好bro：我出门了。你别挂威信，我到楼下跟你说。':'妈妈：我一直在家。小夏，别听门外的声音。':'通话接通。对方叮嘱你早点休息，明早报平安。'}</p>${B('close','挂断','danger')}</div>`);save();};
VIEWS.ending=()=>`<div class="end-view ${S.ending==='escape'?'':'bad'}"><small>${time()}　/　${S.ending==='escape'?'OUTSIDE':'STILL INSIDE'}</small><h2>${S.ending==='escape'?'我看见你了。':'你回来了。'}</h2><div class="end-line">${S.ending==='escape'?'小张是好bro把你拉下最后一阶铁梯。<br><br>六楼的卧室亮了。窗帘后，那个人还在低头看床。<br><br>你没有回头。':' '+esc(S.night.failure)}</div><div class="receipt">${S.ending==='escape'?'妈妈：到小张是好bro那里了吗？<br>你：到了。妈，我想回家。<br><br>论坛提醒：夜航不靠岸　刚刚在线<br>一条新私信：<b>这次，是谁出去了？</b>':'biss直聘 · 凶宅试睡员<br>该职位已删除<br><br>周先生：上一位已经休息了。'}</div>${B('ending-photos','查看照片','primary')}${B('restore-now','从惊醒时重试','secondary')}${B('restart','重新开始','secondary')}</div>`;
VIEWS.files=()=>appHeader('文件','home')+'<div class="scroll pad"><h2>浏览</h2><p class="muted">我的 iPhone</p>'+B('resume-file-v2','林夏_个人简历.pdf','setting')+'</div>';
Object.assign(ACTIONS,{'wx-arrival':arrivalWx,'night-enter':enterHouse,'night-task':d=>sheet(room(d.id).name,`<p>${NORMAL_TASKS[ROOMS.findIndex(r=>r.id===d.id)]}</p>${B('task-camera','打开相机','primary',{id:d.id})}${hasPhoto(d.id)?B('view-photo','查看照片','secondary',{id:d.id}):''}`),'night-reassure':d=>nightReassure(d.id),'night-sleep':nightSleep,'night-panic':nightPanic,'night-hr':d=>nightHr(d.text),'night-route':d=>nightRoute(d.route),'night-move':d=>nightMove(d.move),'night-friend-news':()=>{appendWx('friend','旧照片变了，连周先生的头像也变了。我不是眼花。',true);wxQueue('friend',['我相信你。以前住过这里的人可能也遇到过。搜具体地址试试，我在路上。']);render();},'night-photo-share':d=>sheet('发送给', ['friend','mom','hr'].filter(id=>id!=='hr'||S.contactAccepted).map(id=>B('night-send-photo',AV(id)+personName(id),'setting',{id:d.id,to:id})).join('')),'night-send-photo':d=>nightShare(d.id,d.to),'night-photo-prev':()=>{let i=S.photos.findIndex(p=>p.room===S.view);open('photo',S.photos[(i+S.photos.length-1)%S.photos.length].room);},'night-photo-next':()=>{let i=S.photos.findIndex(p=>p.room===S.view);open('photo',S.photos[(i+1)%S.photos.length].room);},'share-friend':shareFriend,'wx-attach':d=>sheet('聊天工具',B('call','语音通话','setting',{id:d.id})+S.photos.map(p=>B('night-send-photo',room(p.room).name+' · '+p.at,'setting',{id:p.room,to:d.id})).join('')),'camera-help':()=>sheet('相机',`<p>使用快门拍照。轻点画面可以对焦，底部可切换焦段与前后摄像头。</p>${B('flash',S.flash?'关闭闪光灯':'开启闪光灯','setting')}`),'photo-details':d=>sheet('照片信息',`<p>HEIC · ${S.photos.find(p=>p.room===d.id)?.at}<br>本机相机 · 3024 × 4032<br>未编辑</p>`),'hint':()=>sheet('需要一点提示','<p>'+(!S.checked?'先和招聘人沟通，接受工作后按威信里的安排出发。':!isHaunted()?'在工作App看拍摄安排。拍完后，和妈妈、小张是好bro聊聊，再说晚安。':'像平时用手机一样，看看别人发过什么。帖子的日期、作者的日常生活、被留在草稿里的话，都可能有用。')+'</p>'),'contract':()=>sheet('试睡预约单','<p>林夏 · 槐安里6栋604<br>9月13日23:50 — 次日06:00<br>1200元 / 晚<br><br>领取钥匙，拍摄房间，然后留宿体验。</p>'),'restore':()=>sheet('重试这一夜','<p>回到惊醒后的聊天，重新寻找出路。</p>'+B('restore-now','从惊醒时重试','primary')),'night-retry-calm':()=>{S.checked=false;S.flags.keyGiven=true;S.arrived=true;S.photos=[];S.queue=[];S.ending=null;enterHouse();}});
// Chat-only arrival: the player says they entered; no physical keypad UI.
const arrivalChat=wxChat;wxChat=id=>{const html=arrivalChat(id);if(id==='hr'&&S.arrived&&!S.checked&&S.flags.keyGiven&&!threadPending('wx','hr'))return html.replace('<form class="composer"',`<div class="chat-choices">${B('night-enter','拿到钥匙了，我已经进屋。')}</div><form class="composer"`);return html;};
// Notification muting is a phone feature, independent of accessibility audio preferences.
const settingsBeforeNight=VIEWS.settings;VIEWS.settings=()=>S.view==='battery'?settingsBeforeNight():settingsBeforeNight().replace('从最近的拍摄检查点继续','从惊醒时重新尝试').replace(B('hint','需要一点提示'+I('next'),'setting'),B('night-quiet',`<span>消息提示音</span><small>${S.night.quiet?'静音':'响铃'}</small>`,'setting')+B('hint','需要一点提示'+I('next'),'setting'));
ACTIONS['night-quiet']=()=>{S.night.quiet=!S.night.quiet;save();render();};
const flashBeforeNight=ACTIONS.flash;ACTIONS.flash=()=>{flashBeforeNight();S.night.flashOff=!S.flash;save();};
const beforeNightNotify=notify;notify=(title,text,app='wechat',view='')=>{if(!S.night.quiet)return beforeNightNotify(title,text,app,view);R.notice={title,text,app,view};R.noticeLeft=5300;renderNotice();};
const storeBeforeNight=VIEWS.store;VIEWS.store=()=>storeBeforeNight().replaceAll('房源体验与影像记录','房源预约与夜间体验').replaceAll('一份房屋档案<br>从真实记录开始。','今晚的预约<br>都在这里。').replaceAll('影像采集　·　问题记录　·　交付报告','入住安排　·　拍摄要求　·　联系负责人').replaceAll('接收体验任务、整理现场影像、查看房屋资料和提交报告。支持从系统相机拍摄并选择照片附件。','查看预约安排与拍摄要求，使用系统相机拍照，并在威信与负责人沟通。').replaceAll('改进现场记录与任务提醒体验。','改进预约与提醒体验。');
const nightBaseRender=render;render=()=>{v2Defaults(S);PEOPLE.hr.image=isHaunted()?'hr-zhou-ghost-v2.png':'hr-zhou.png';nightBaseRender();$('#phone').classList.toggle('night-sleeping',S.night.phase==='sleeping');};
window.render_game_to_text=()=>JSON.stringify({title:'请确认入住',edition:4,app:S.app,view:S.view,time:time(),battery:batteryPercent(),device:{clock:deviceTime(true),date:deviceDateLabel(),battery:batteryPercent(),batteryExact:ensureDevice(S).battery,activeMs:ensureDevice(S).activeMs,lowPower:ensureDevice(S).lowPower,usage:ensureDevice(S).usage},phase:S.night.phase,checked:S.checked,photos:S.photos.map(p=>({...p,src:room(p.room).photo})),night:S.night,forum:{user:S.forum.user,query:S.forum.query,read:S.forum.reads},pending:S.queue.map(q=>({id:q.id,event:q.event,remaining:q.remaining})),ending:S.ending,scareVisible:R.scareLeft>0,visibleActions:[...document.querySelectorAll('#screen [data-action],#modal [data-action]')].map(b=>({action:b.dataset.action,id:b.dataset.id,text:b.textContent.trim()}))});
save();render();




