'use strict';
const FORUM_POSTS=[
 {id:'cat',author:'夜航不靠岸',date:'2024-09-24 18:06',tag:'生活',title:'今天带一位新室友回家',text:['楼下纸箱里捡到的小猫，暂时叫它 Momo。不是生日，是今天才带回家的。','买猫砂的钱花完了，晚饭又得吃面。希望它不要嫌弃我。'],image:'wx-cat.png',likes:48,comments:[['鱼饼','名字好听！'],['夜航不靠岸','以后能好好生活了。']]},
 {id:'work',author:'夜航不靠岸',date:'2024-11-06 19:20',tag:'夜班',title:'找到日结了，1200，干一晚够交房租',text:['摄影助理面试又黄了。biss上刷到试睡的工作，房东说拍几张照片，住到天亮就好。','联系人姓周，看着挺客气。槐安里6栋604。我带了充电宝，回来给你们写体验。'],likes:29,comments:[['奶油卷','这么高？注意点。'],['夜航不靠岸','没押金，应该还好。']]},
 {id:'normal',author:'夜航不靠岸',date:'2024-11-06 23:48',tag:'夜班',title:'到了，比想象中正常',text:['照片都拍了，没什么东西。窗户能开，门也能开。','床单有太阳晒过的味道，浴室窗外是检修平台。我妈刚打电话来，我说一切正常。','周先生说可以睡了。晚安。'],image:'living.png',likes:34,comments:[['鱼饼','明早记得更新。'],['夜航不靠岸','起床就更新。']]},
 {id:'awake',author:'夜航不靠岸',date:'2024-11-07 02:19',tag:'夜班',title:'有人遇到过照片自己变了吗',text:['刚被威信吵醒。周先生问我睡着了为什么还在看门。','我打开biss想核对手机号。他的头像还是那个姿势，脸却像死了很久。','相册里出现了一个女人。照片的拍摄时间没变。她躺在我现在睡的位置上。','我没有重新拍过。真的没有。'],likes:102,comments:[['山路','是不是恶作剧？'],['夜航不靠岸','那门为什么打不开了？窗户也是。不是锁上，是根本找不到缝。']]},
 {id:'door',author:'夜航不靠岸',date:'2024-11-07 02:43',tag:'夜班',title:'门外是我妈。但我妈在三百公里外',text:['她喊我的乳名，语气一模一样。电话打回家，我妈说她刚醒。','我从猫眼里看，外面不是楼道，是我自己的卧室。床上的我正把脸贴在猫眼上。','有人给我私信，说他以前住过这栋楼。我不敢把他说的办法贴出来。周也在看这个帖子。'],likes:189,comments:[['老楼北窗','看私信，不要在公开楼里说你准备去哪。'],['夜航不靠岸','收到。']]},
 {id:'last',author:'夜航不靠岸',date:'2024-11-07 03:17',tag:'夜班',title:'不要回复这条帖子',text:['它只要一个醒着的人。','我明明没有动，为什么显示“正在输入”？','我不写在这里了。剩下的话放进草稿。','它开始学我的声音。','妈妈我不找工作了','妈妈','我回来了吗'],likes:316,comments:[['鱼饼','楼主回来了吗？'],['奶油卷','2025年了，有人联系上他吗？'],['山路','2026.09.12，还是没上线。']]},
 {id:'building',author:'维修老何',date:'2024-08-10 16:32',tag:'旧城',title:'槐安里老楼维修，北侧平台暂不封闭',text:['6栋北侧有一圈检修平台，右边连接外置消防梯。浴室的小窗朝北，客厅大窗朝内天井。','老住户都知道，夜里别走内天井。那里没有落脚的地方。'],likes:61,comments:[['阿岚','谢谢提醒。']]},
 {id:'noodles',author:'奶油卷',date:'2026-09-13 20:06',tag:'生活',title:'江北路那家面馆居然开到凌晨三点',text:['加了一个煎蛋，十五块。夜班下了有人一起吃吗？','老板说只要灯亮着就能来。'],image:'life-dinner.png',likes:62,comments:[['晚风','我十点下班！']]},
 {id:'rain',author:'山路',date:'2026-09-13 18:41',tag:'旧城',title:'今晚江北路积水，骑车的注意',text:['小区南门排水有点慢，外卖小哥从东门走吧。'],likes:18,comments:[]},
 {id:'shift',author:'鱼饼',date:'2026-09-12 23:51',tag:'夜班',title:'上了三个月夜班，感觉时间错位了',text:['下班的路上别人正在吃早饭。准备休息两天，带猫去做检查。'],likes:37,comments:[]},
 {id:'welcome',author:'站务',date:'2026-09-01 10:00',tag:'公告',title:'临川夜话｜欢迎把生活留在这里',text:['生活、夜班、旧城。这里是临川人的小小客厅。','请文明交流，保护个人信息。旧版用户可通过账号和密码登录，旧邮箱通道已停用。'],likes:223,comments:[]}
];
function forumPosts(){return [...S.forum.posts,...FORUM_POSTS];}
function forumPost(id){return forumPosts().find(p=>p.id===id);}
function forumFace(name){const asset=name==='夜航不靠岸'?'wx-hao-v6.png':name==='老楼北窗'?'wx-mountain.png':name==='林砚'?'player-avatar.png':'wx-cat.png';return `<img src="assets/${asset}" alt="${esc(name)}头像">`;}
function forumLink(view){S.forum.navStack??=[];if(S.app==='browser'&&S.view.startsWith('forum:')&&S.view!=='forum:'+view)S.forum.navStack.push(S.view);open('browser','forum:'+view);}
function forumNav(active){return `<nav class="forum-nav">${[['home','社区','home'],['inbox','消息','wechat'],['me','我的','user']].map(([v,t,i])=>B('forum-go',I(i)+'<span>'+t+'</span>',active===v?'active':'',{view:v})).join('')}</nav>`;}
function forumHeader(){return `<div class="forum-address">${B('forum-back',I('back'),'',{label:'返回浏览器'})}<span>${I('lock')} linchuan.local / 夜话</span>${B('forum-go',I('home'),'',{view:'home',label:'论坛首页'})}</div>`;}
function forumCard(p){return `<article class="forum-card"><div class="forum-byline">${B('forum-profile',forumFace(p.author),'',{author:p.author})}<span>${esc(p.author)}<small>${p.date}</small></span><em>${p.tag}</em></div>${B('forum-post',`<h3>${esc(p.title)}</h3><p>${esc(p.text[0])}</p>${p.image?`<img class="forum-preview" src="assets/${p.image}" alt="帖子配图">`:''}`,'forum-card-body',{id:p.id})}<div class="forum-stats"><span>${(p.likes||0)*13+81} 阅读</span><span>${(p.comments?.length||0)+(S.forum.comments[p.id]?.length||0)} 回复</span>${B('forum-like',(S.forum.likes.includes(p.id)?'♥':'♡')+' '+((p.likes||0)+(S.forum.likes.includes(p.id)?1:0)),S.forum.likes.includes(p.id)?'liked':'',{id:p.id})}</div></article>`;}
function forumHome(){const f=S.forum;let list=forumPosts().filter(p=>(f.tab==='全部'||p.tag===f.tab)&&(!f.query||[p.title,p.author,...p.text].join(' ').toLowerCase().includes(f.query.toLowerCase())));list.sort((a,b)=>f.sort==='hot'?(b.likes||0)-(a.likes||0):b.date.localeCompare(a.date));return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-brand"><div><small>LINCHUAN AFTER HOURS</small><h1>临川<span>夜话</span><i>●</i></h1><p>夜很长，总有人醒着。</p></div><div class="forum-moon">☾</div></div><form id="forum-search" class="forum-search">${I('search')}<input id="forum-query" aria-label="搜索论坛" placeholder="搜索帖子、作者、地点" value="${esc(f.query)}"><button type="submit">搜索</button></form><div class="forum-tabs">${['全部','生活','夜班','旧城','公告'].map(t=>B('forum-tab',t,f.tab===t?'active':'',{tab:t})).join('')}</div><div class="forum-list-head"><span>${f.query?'“'+esc(f.query)+'” · '+list.length+' 个结果':'今日话题'}</span><div>${B('forum-sort',f.sort==='new'?'最新 ↓':'最热 ↓')}${B('forum-go','＋ 发帖','',{view:'compose'})}</div></div>${list.length?list.map(forumCard).join(''):'<p class="empty">没有找到帖子，换个关键词试试。</p>'}<p class="forum-end">已经到底了 · 好好生活，慢慢说</p></div>`+forumNav('home');}
function forumArticle(id){const p=forumPost(id);if(!p)return forumHeader()+'<p class="empty">帖子不存在。</p>';const comments=[...(p.comments||[]),...(S.forum.comments[id]||[])];return forumHeader()+`<div class="scroll forum-scroll"><article class="forum-article"><span class="forum-tag">${p.tag}</span><h1>${esc(p.title)}</h1><div class="forum-byline">${B('forum-profile',forumFace(p.author),'',{author:p.author})}<span>${B('forum-profile',esc(p.author),'',{author:p.author})}<small>${p.date}　临川</small></span></div>${p.text.map(t=>'<p>'+esc(t)+'</p>').join('')}${p.image?B('forum-image',`<img class="forum-article-image" src="assets/${p.image}" alt="帖子图片">`,'',{id}):''}<div class="forum-article-tools">${B('forum-like',(S.forum.likes.includes(id)?'♥ 已赞':'♡ 赞')+' '+((p.likes||0)+(S.forum.likes.includes(id)?1:0)),'',{id})}${B('forum-save',S.forum.saved.includes(id)?'★ 已收藏':'☆ 收藏','',{id})}${B('forum-share','分享','',{id})}</div></article><section class="forum-comments"><h3>全部回复 <small>${comments.length}</small></h3>${comments.map(([a,t],i)=>`<div class="forum-comment">${forumFace(a)}<div><b>${esc(a)}</b><small>${i+1}楼${a===p.author?' · 楼主':''}</small><p>${esc(t)}</p>${B('forum-reply','回复','',{id,author:a})}</div></div>`).join('')||'<p class="muted">还没有回复，说点什么吧。</p>'}</section></div><form class="forum-composer" id="forum-comment-form" data-id="${id}"><input id="forum-comment-text" aria-label="回复帖子" placeholder="友善地说点什么…" maxlength="300" value="${esc(S.forum.drafts['comment:'+id]||'')}"><button type="submit">回复</button></form>`;}
function forumProfile(author){const old=author==='夜航不靠岸',list=forumPosts().filter(p=>p.author===author).sort((a,b)=>b.date.localeCompare(a.date));return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-profile-cover"></div><div class="forum-profile-main">${forumFace(author)}<h2>${esc(author)}</h2><p>${old?'账号 nightboat · 注册于2024年9月':'临川夜话社区成员'}</p><div class="forum-offline">${old?'离线 · 最后在线 2024-11-07 03:17':'最近来过社区'}</div><p>${old?'摄影新手 / 一人一猫 / 希望明年能换一个有阳台的房间。':'把生活慢慢写下来。'}</p><div class="forum-profile-stats"><span><b>${list.length}</b>帖子</span><span><b>${old?127:23}</b>关注者</span><span><b>${old?41:6}</b>关注</span></div>${B('forum-follow',S.forum.following?'已关注':'＋ 关注','forum-solid')}${B('forum-message','发私信','forum-outline',{author})}</div><div class="forum-list-head"><span>全部帖子 · 时间倒序</span>${old?B('forum-go','旧账号登录','',{view:'login'}):''}</div>${list.map(forumCard).join('')}</div>`;}
function forumLogin(){return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-login"><div class="forum-logo">夜</div><h2>欢迎回来</h2><p>临川夜话 · 旧版账号登录</p><form id="forum-login"><label>账号<input id="forum-account" name="account" autocomplete="off" placeholder="用户名" value="${esc(S.forum.drafts.account||'')}"></label><label>密码<input id="forum-password" type="password" autocomplete="off" placeholder="输入密码"></label><p class="forum-error" role="alert">${esc(S.forum.loginError)}</p><button class="forum-solid" type="submit">登录</button></form>${B('forum-password-hint','忘记密码？','forum-login-link')}<p class="forum-privacy">旧邮箱服务已停止。你仍可使用原密码登录。</p></div></div>`;}
function forumMine(){const logged=S.forum.user==='nightboat';return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-my-head">${forumFace(logged?'夜航不靠岸':'林砚')}<h2>${logged?'夜航不靠岸':'林砚 · 访客'}</h2><p>${logged?'nightboat · 旧版账号':'以本机访客身份参与讨论'}</p></div>${!logged?B('forum-go','登录旧版账号'+I('next'),'forum-menu',{view:'login'}):B('forum-go','草稿箱　3'+I('next'),'forum-menu',{view:'drafts'})}${B('forum-go','我的收藏　'+S.forum.saved.length+I('next'),'forum-menu',{view:'saved'})}${B('forum-go','浏览历史　'+S.forum.history.length+I('next'),'forum-menu',{view:'history'})}${B('forum-go','我的帖子'+I('next'),'forum-menu',{view:'myposts'})}${logged?B('forum-logout','退出登录','forum-menu'):''}</div>`+forumNav('me');}
const PRIVATE_THREADS=[{id:'north',name:'老楼北窗',preview:'别再拍新的。它只看你发过去的图。',messages:[['2024-11-07 02:46','你在604？先把消息提示音关掉，相机闪光灯也关掉。它在听你手机的位置。'],['02:48','不要相信入户门。客厅窗外是天井。浴室小窗外才是检修平台，沿右边能到消防梯。'],['02:50','它盯着门窗，是因为知道你醒了。得让它以为你还在床上。'],['02:51','别再拍新的。它只看你发过去的图，认不出旧照片。把睡前拍的卧室照发给周，再说你还在床上、没醒。'],['02:53','它会去床边点人数。那时浴室小窗才能推开。先不要动，听敲门。'],['03:00','收到请回。我只见过一个人下过平台。她说最后一步千万别回头。']]},{id:'zhou',name:'周同安',preview:'你的小猫，今天是不是还没吃饭。',messages:[['2024-11-07 02:58','为什么要换一个账号？'],['03:05','你的小猫，今天是不是还没吃饭。'],['03:16','床上那个人说，他才是你。你们两个谁在骗我？'],['03:17','你出来。让他睡。']]}];
function forumInbox(){const logged=S.forum.user==='nightboat';return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-page-title"><small>INBOX</small><h1>消息</h1></div>${logged?PRIVATE_THREADS.map(t=>B('forum-go',`${forumFace(t.name)}<span><b>${t.name}</b><p>${t.preview}</p></span><small>2024/11/07</small>`,'forum-inbox-row',{view:'dm:'+t.id})).join(''):S.forum.notices.length?S.forum.notices.map(t=>'<div class="forum-card"><p>'+esc(t)+'</p></div>').join(''):'<p class="empty">暂时没有消息。</p>'}</div>`+forumNav('inbox');}
const FORUM_DRAFTS=[{id:'rule',title:'听清楚再动',time:'2024-11-07 03:08',text:['我已经把卧室的旧照片发了。它说“我进去看看”。门口真的安静了。','一声敲门是在听我有没有动。我动了一下，床底就有东西爬出来。','停住，等三声。三声以后脚步回卧室。这个间隙去浴室。','手机提示音和闪光灯都要关。别让它重新找到我。']},{id:'catnote',title:'如果我明早没回来',time:'2024-11-07 03:12',text:['Momo的猫粮在冰箱上面。','浴室窗外不是空的，有平台。沿右边，铁梯就在那里。','不管听到谁叫我，都不回头。就看手机里的字，别接门外的声音。','我想好了。再响三下就走。']},{id:'lastdraft',title:'无标题',time:'2024-11-07 03:18',text:['我刚爬出去，它在身后喊猫的名字。','我只回了一下头。','为什么我又躺在床上。','是谁拿着我的手机下楼了。']}];
function forumPrivate(view){if(S.forum.user!=='nightboat')return forumLogin();if(view==='drafts')return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-page-title"><small>ONLY ME</small><h1>草稿箱</h1><p>仅自己可见 · 从未发布</p></div>${[...FORUM_DRAFTS].sort((a,b)=>b.time.localeCompare(a.time)).map(d=>B('forum-go',`<small>${d.time}</small><h3>${d.title}</h3><p>${d.text[0]}</p>`,'forum-draft',{view:'draft:'+d.id})).join('')}</div>`;if(view.startsWith('draft:')){const d=FORUM_DRAFTS.find(d=>d.id===view.slice(6));if(!d)return forumMine();return forumHeader()+`<div class="scroll forum-scroll"><article class="forum-article"><span class="forum-tag">未发布 · 自动保存</span><h1>${d.title}</h1><small>${d.time}</small>${d.text.map(t=>'<p>'+t+'</p>').join('')}</article></div>`;}const t=PRIVATE_THREADS.find(t=>t.id===view.slice(3));if(!t)return forumInbox();return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-page-title"><small>PRIVATE MESSAGE</small><h2>${t.name}</h2><p>这段对话只对双方可见</p></div>${t.messages.map(([at,text])=>`<div class="forum-private-message"><small>${at}</small><p>${text}</p></div>`).join('')}</div><form id="forum-dm-form" class="forum-composer"><input id="forum-dm-text" aria-label="发送私信" placeholder="发送私信…" maxlength="300"><button type="submit">发送</button></form>`;}
function forumView(){const v=S.view.slice(6)||'home';if(v==='home')return forumHome();if(v.startsWith('post:'))return forumArticle(v.slice(5));if(v.startsWith('profile:'))return forumProfile(v.slice(8));if(v==='login')return forumLogin();if(v==='me')return forumMine();if(v==='inbox')return forumInbox();if(v==='drafts'||v.startsWith('draft:')||v.startsWith('dm:'))return forumPrivate(v);if(['saved','history','myposts'].includes(v)){const ids=v==='saved'?S.forum.saved:v==='history'?S.forum.history:S.forum.posts.map(p=>p.id);return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-page-title"><h2>${{saved:'我的收藏',history:'浏览历史',myposts:'我的帖子'}[v]}</h2></div>${ids.map(forumPost).filter(Boolean).map(forumCard).join('')||'<p class="empty">这里还没有内容。</p>'}</div>`;}return forumHeader()+`<div class="scroll forum-scroll"><div class="forum-page-title"><h2>发布新帖子</h2></div><form id="forum-publish" class="forum-editor"><input id="forum-title" aria-label="帖子标题" maxlength="60" placeholder="标题" value="${esc(S.forum.drafts.title||'')}"><select id="forum-category" aria-label="帖子分类"><option>生活</option><option>夜班</option><option>旧城</option></select><textarea id="forum-body" aria-label="帖子正文" maxlength="3000" placeholder="写下你想说的话…">${esc(S.forum.drafts.body||'')}</textarea><button class="forum-solid" type="submit">发布</button></form></div>`;}
VIEWS.browser=()=>S.view.startsWith('forum:')?forumView():appHeader('浏览器','home',B('history',I('clock')))+`<div class="scroll night-browser"><div class="browser-home"><h2>搜<span>一下</span></h2><form class="search-form" id="search-form"><div class="searchbox">${I('search')}<input id="search-input" aria-label="搜索关键词" placeholder="搜索网页、人物、地点" value="${esc(S.query)}"></div><button type="submit">搜索</button></form></div>${S.query?`<div class="search-results"><small>搜索 “${esc(S.query)}”</small>${/604|槐安|试睡|周|照片|鬼|夜话|夜航|许青|失踪|房|打不开/.test(S.query)?B('forum-result','<small>临川夜话 · 社区讨论</small><h3>找到日结了，1200，干一晚够交房租</h3><p>夜航不靠岸：照片都拍了，没什么东西。我妈刚打电话来，我说一切正常……</p>','result'):''}${B('forum-go','<small>临川夜话 · 本地社区</small><h3>夜很长，总有人醒着。</h3><p>生活、夜班、旧城，看看临川人的故事。</p>','result',{view:'home'})}<div class="result"><small>社区信息</small><h3>槐安里小区</h3><p>江北路北侧，住宅小区。更多住户讨论可在临川夜话搜索。</p></div></div>`:`<div class="pad"><h3>常用网站</h3>${B('forum-go','☾ 临川夜话','forum-site',{view:'home'})}<p class="muted">搜索你感兴趣的事。</p></div>`}</div>`;
doSearch=q=>{S.query=(q??$('#search-input')?.value??'').trim();if(S.query&&!S.history.includes(S.query))S.history.push(S.query);open('browser');};
Object.assign(ACTIONS,{'browser-home':()=>open('browser'),'forum-go':d=>forumLink(d.view),'forum-result':()=>{S.forum.query='604';S.forum.tab='全部';forumLink('home');},'forum-post':d=>{if(!S.forum.reads.includes(d.id))S.forum.reads.push(d.id);S.forum.history=[d.id,...S.forum.history.filter(x=>x!==d.id)];save();forumLink('post:'+d.id);},'forum-profile':d=>forumLink('profile:'+d.author),'forum-tab':d=>{S.forum.tab=d.tab;save();render();},'forum-sort':()=>{S.forum.sort=S.forum.sort==='new'?'hot':'new';save();render();},'forum-like':d=>{S.forum.likes=S.forum.likes.includes(d.id)?S.forum.likes.filter(x=>x!==d.id):[...S.forum.likes,d.id];save();const sc=$('.forum-scroll'),y=sc?.scrollTop;render();if(y)$('.forum-scroll').scrollTop=y;},'forum-save':d=>{S.forum.saved=S.forum.saved.includes(d.id)?S.forum.saved.filter(x=>x!==d.id):[...S.forum.saved,d.id];save();render();},'forum-share':d=>sheet('分享帖子',`<p>${esc(forumPost(d.id).title)}</p><input aria-label="帖子链接" readonly value="linchuan.local/thread/${d.id}">${B('forum-share-wx','发给小张是好bro','primary',{id:d.id})}`),'forum-share-wx':d=>{appendWx('friend','[佰度贴吧] '+forumPost(d.id).title,true);wxQueue('friend',[isHaunted()?'这个人最后一次上线是两年前……点他的头像看看以前还写了什么。':'我下班看看。']);open('wechat','friend');},'forum-follow':()=>{S.forum.following=!S.forum.following;save();render();},'forum-message':d=>sheet('发送私信',`<p>发送给 ${esc(d.author)}</p><form id="forum-guest-message"><textarea id="forum-guest-text" aria-label="私信内容" maxlength="500" placeholder="你好…"></textarea><button type="submit" class="forum-solid">发送</button></form>`),'forum-reply':d=>{S.forum.drafts['comment:'+d.id]='回复 '+d.author+'：';$('#forum-comment-text').value=S.forum.drafts['comment:'+d.id];$('#forum-comment-text').focus();},'forum-password-hint':()=>sheet('旧版密码提示','<p>请先输入用户名，再查看你设置的提示。</p><form id="forum-hint-form"><input id="forum-hint-account" aria-label="查询提示的账号" value="'+esc($('#forum-account')?.value||'')+'" placeholder="用户名"><button type="submit" class="forum-solid">查看提示</button></form>'),'forum-logout':()=>{S.forum.user=null;save();forumLink('me');},'forum-image':d=>sheet('帖子图片',`<img class="social-full-image" src="assets/${forumPost(d.id).image}" alt="帖子原图">`)});
document.addEventListener('input',e=>{const f=S.forum;if(e.target.id==='forum-comment-text')f.drafts['comment:'+e.target.form.dataset.id]=e.target.value;if(e.target.id==='forum-title')f.drafts.title=e.target.value;if(e.target.id==='forum-body')f.drafts.body=e.target.value;if(e.target.id==='forum-account')f.drafts.account=e.target.value;save();});
document.addEventListener('submit',e=>{const id=e.target.id,f=S.forum;if(!id.startsWith('forum-'))return;e.preventDefault();if(id==='forum-search'){f.query=$('#forum-query').value.trim();f.searches.push(f.query);f.tab='全部';save();forumLink('home');}if(id==='forum-login'){const account=$('#forum-account').value.trim(),password=$('#forum-password').value;f.drafts.account=account;if(account==='nightboat'&&password==='momo0924'){f.user='nightboat';f.loginError='';save();forumLink('me');}else{f.loginError='账号或密码不正确。';save();render();}}if(id==='forum-hint-form'){const account=$('#forum-hint-account').value.trim();sheet('密码提示',account==='nightboat'?'<p>你于2024年9月24日设置的提示：</p><blockquote>它的小名，小写。再加上带它回家那天的月日，四位。</blockquote>':'<p>没有找到这个旧版账号。</p>');}if(id==='forum-comment-form'){const postId=e.target.dataset.id,text=$('#forum-comment-text').value.trim();if(!text)return;f.comments[postId]??=[];f.comments[postId].push([f.user==='nightboat'?'夜航不靠岸':'林砚',text]);f.drafts['comment:'+postId]='';save();render();}if(id==='forum-publish'){const title=$('#forum-title').value.trim(),body=$('#forum-body').value.trim(),tag=$('#forum-category').value;if(!title||!body)return sheet('还没有写完','<p>请填写标题和正文。</p>');const postId='local-'+(++S.seq);f.posts.unshift({id:postId,author:f.user==='nightboat'?'夜航不靠岸':'林砚',date:'2026-09-14 '+time(),tag,title,text:body.split('\n').filter(Boolean),likes:0,comments:[]});f.drafts.title=f.drafts.body='';save();forumLink('post:'+postId);}if(id==='forum-guest-message'||id==='forum-dm-form'){const text=$(id==='forum-guest-message'?'#forum-guest-text':'#forum-dm-text').value.trim();if(!text)return;f.notices.push('已发送：'+text+' · 对方离线，尚未读。');save();sheet('私信已发送','<p>对方已经离线很久。消息暂未读。</p>');}});
save();render();

// A website shares through the phone's contact picker, not a story-specific friend button.
ACTIONS['forum-share']=d=>sheet('分享帖子',`<p>${esc(forumPost(d.id).title)}</p><input aria-label="帖子链接" readonly value="linchuan.local/thread/${d.id}">${B('forum-share-wechat',I('wechat')+' 威信','setting',{id:d.id})}`);
ACTIONS['forum-share-wechat']=d=>sheet('威信 · 选择联系人',Object.keys(PEOPLE).filter(id=>id!=='self'&&canSeePeer(id)).map(id=>B('forum-send-contact',AV(id)+esc(personName(id)),'setting',{id:d.id,to:id})).join(''));
ACTIONS['forum-send-contact']=d=>{if(!forumPost(d.id)||!canSeePeer(d.to))return;appendWx(d.to,'[佰度贴吧] '+forumPost(d.id).title,true);wxQueue(d.to,[d.to==='friend'&&isHaunted()?'这个人最后一次上线是两年前……不知道后来还写过什么。':'收到，我看看。']);open('wechat',d.to);};

ACTIONS['forum-back']=()=>{const view=S.forum.navStack?.pop();open('browser',view||'');};
const beforeForumBack=back;back=()=>{if(S.app==='browser'&&S.view.startsWith('forum:')&&!$('#modal').innerHTML)return ACTIONS['forum-back']();beforeForumBack();};



