'use strict';
// Phone-native investigation. Legacy field names remain only for save compatibility.
const beforePhoneDefaults=v2Defaults;
v2Defaults=s=>{beforePhoneDefaults(s);if(!s.phoneCase){s.phoneCase={exposure:0,photoVerified:hasLegacy(s,'bath'),archiveQuery:'',archivePinned:false,attachment:hasLegacy(s,'bed'),selectedFiles:[],restored:false,identity:false,impostor:false,routeOrder:['exit','start','stairs'],routeReady:false,escape:null};if(!s.ending){s.puzzle.reportRevoked=false;s.puzzle.drawer=false;s.puzzle.exitLocated=false;s.puzzle.lever=false;}s.onSiteLog=[];}s.puzzle.power=s.phoneCase.photoVerified;s.puzzle.bedroom=s.phoneCase.attachment;return s;};v2Defaults(S);
const CASE_FILES=[
 {id:'ad',name:'房源宣传_最终版.txt',owner:'周同安',date:'2020-10-24 10:00',text:'房内长期空置，未有其他住户。'},
 {id:'diary',name:'给自己的留言.txt',owner:'沈秋宁',date:'2018-06-13 22:46',text:'门又从外面锁上了。我把求助的信息和录音存进云端。如果有人看到，请记住我的名字。'},
 {id:'route',name:'物业疏散路线.gpx',owner:'沈秋宁',date:'2018-06-13 18:12',text:'从北侧楼梯下楼，西侧出口夜间有人值守。轨迹记录附在文件后。'},
 {id:'other',name:'日记副本.txt',owner:'沈秋月',date:'2018-06-13 21:10',text:'今天搬进槐安二村8幢201。'},
 {id:'receipt',name:'住户登记回执.pdf',owner:'沈秋宁',date:'2018-06-13 18:05',text:'姓名：沈秋宁；房屋：槐安二村3幢604；职业：服装修改。临川社区电子回执。'},
 {id:'fake',name:'给自己的留言_补录.txt',owner:'沈秋宁',date:'2020-10-24 10:01',text:'本人确认此前记录有误，同意永久居住。'}
];
const ARCHIVE_MESSAGES=[
 {id:'a',date:'2020年10月20日 17:30',text:'这周六做最后一次验收。主卧的拍摄示范附件，密码用验收那天的月日，四位数字。',key:true},
 {id:'b',date:'2020年10月19日 09:00',text:'上个月的验收已经取消，之前那个密码不要用了。'},
 {id:'c',date:'2020年10月24日 11:30',text:'窗帘别打开。只要看示范附件，照着拍。'},
 {id:'d',date:'2020年10月18日 14:20',text:'照片里如果出现别人，先别在报告里写。'}
];
const ROUTE_PARTS={start:{title:'604门口',from:'604',to:'北侧楼梯',text:'指南针指向北。楼道两头相似，北侧是楼梯。',icon:'browser'},stairs:{title:'北侧楼梯',from:'北侧楼梯',to:'一层走廊',text:'沿下行方向，从六层到一层。',icon:'signal'},exit:{title:'一层走廊',from:'一层走廊',to:'西侧出口',text:'到一层后向西。出口外是值班室。',icon:'map'}};
function caseDone(id){return ({exposure:S.phoneCase.photoVerified,archive:S.phoneCase.attachment,recovery:S.phoneCase.restored,identity:S.phoneCase.identity,verify:S.phoneCase.impostor,trail:S.phoneCase.routeReady})[id];}
function caseAvailable(id){return ({exposure:hasPhoto('living'),archive:S.taskReady>=3,recovery:hasPhoto('bed'),identity:S.phoneCase.restored,verify:hasPhoto('bed'),trail:S.phoneCase.restored})[id];}
const CASE_CARDS=[['exposure','photos','照片暗部检查','拖动曝光，找出取景时不存在的人影。'],['archive','wechat','聊天记录检索','搜出附件密码的线索，再用日历核对。'],['recovery','files','最近删除','甄别被删文件，恢复同一个人的真实记录。'],['identity','user','身份交叉核对','把旧报道与云端回执对应起来。'],['verify','phone','消息身份核验','给熟悉的人回拨电话，辨认冒名消息。'],['trail','map','离线轨迹整理','把断开的路线片段按起终点接起来。']];
stayTabs=id=>`<nav class="bottomtabs stay-tabs">${[['tasks','files','任务'],['onsite','search','调查'],['docs','notes','资料'],['account','user','我的']].map(([v,i,t])=>B('stay-tab',I(i)+`<span>${t}</span>`,id===v?'active':'',{view:v})).join('')}</nav>`;
function caseHub(){return appHeader('调查记录','stay-home')+`<div class="scroll case-page"><div class="case-intro"><small>604 / 我的记录</small><h2>手机里留下的证据</h2><p>从照片、聊天和文件中找出这一夜的真相。</p></div><div class="case-list">${CASE_CARDS.map(([id,icon,title,desc],i)=>B('case-open',`<span class="case-icon">${I(icon)}</span><span class="case-text"><small>0${i+1} · ${caseDone(id)?'已核实':caseAvailable(id)?'可以调查':'等待线索'}</small><b>${title}</b><p>${desc}</p></span>${I(caseDone(id)?'check':caseAvailable(id)?'next':'lock')}`,'case-row',{id})).join('')}</div>${S.puzzle.reportRevoked?B('case-escape','查看离线路线','primary case-bottom'):''}<p class="case-foot">原始照片与聊天保留在各自的应用中。</p></div>`+stayTabs('onsite');}
const oldStayPhone=VIEWS.stay;
VIEWS.stay=()=>S.view.startsWith('case:')?caseView(S.view.slice(5)):S.view==='onsite'?caseHub():oldStayPhone().replace('查看现场平面图与可调查物品','打开手机调查记录').replaceAll('需要先处理现场通行问题','需要先核验任务附件');
onsiteView=caseHub;
TASK_COPY[2]='上一张异常原片核验完成后，正对洗手台镜面拍摄。';TASK_COPY[3]='解密招聘人提供的机位附件后，降低镜头，拍摄床沿和床底。';
const beforePhoneTask=taskDetail;taskDetail=id=>beforePhoneTask(id).replace('去现场检查配电箱','检查上一张照片的暗部').replace('去现场检查主卧门锁','检索聊天，解密拍摄附件');
function caseFrame(title,body){return appHeader(title,'case-back')+`<div class="scroll case-page case-detail">${body}</div>`;}
function caseView(id){if(!caseAvailable(id))return caseFrame('等待线索','<p class="empty">按任务拍照，新的文件或消息出现后，这项调查就会开放。</p>');
 if(id==='exposure')return caseFrame('照片 · 编辑',`<div class="case-photo"><img src="assets/living.png" alt="原片暗部"><img id="exposure-image" src="assets/living-ghost.png" alt="客厅异常原片，拖动曝光后点选可疑处" style="opacity:${S.phoneCase.exposure/100};filter:brightness(${1+S.phoneCase.exposure/85})">${S.phoneCase.photoVerified?'<span class="case-photo-result">异常区域已留证</span>':''}</div><div class="exposure-controls"><div><b>曝光</b><output id="exposure-value">${S.phoneCase.exposure}</output></div><input type="range" id="case-exposure" min="0" max="100" value="${S.phoneCase.exposure}" aria-label="调整照片曝光"><p id="case-photo-feedback">${S.phoneCase.photoVerified?'窗帘后的脸已核实。浴室任务可以继续。':'照片比取景时更暗。拖动滑杆，点一下藏在暗处的不对劲之处。'}</p></div>${B('task','返回浴室拍摄任务','secondary',{id:'bath'})}`);
 if(id==='archive')return caseFrame('聊天记录 · 周先生',`<form id="case-search-form" class="searchbox"><input id="case-search" placeholder="搜索聊天内容" aria-label="搜索聊天内容" value="${esc(S.phoneCase.archiveQuery)}"><button type="submit">${I('search')}</button></form><p class="muted">安住附件自带的历史沟通记录。试试搜索“验收”或“密码”。</p><div class="archive-results">${ARCHIVE_MESSAGES.filter(m=>S.phoneCase.archiveQuery&&m.text.includes(S.phoneCase.archiveQuery)).map(m=>B('case-pin',`<small>${m.date}</small><p>${m.text}</p><span>${S.phoneCase.archivePinned&&m.key?'已保存这条线索':'保存为密码线索'}</span>`,'archive-message',{id:m.id})).join('')||'<p class="empty">输入关键词查找消息。</p>'}</div>${B('open','打开日历','secondary',{app:'calendar'})}<div class="card case-file"><h3>主卧机位示范.zip</h3><p>${S.phoneCase.attachment?'已解密：镜头靠近地面，拍全床沿和床底。':'加密附件 · 需要四位密码'}</p>${S.phoneCase.attachment?B('task','前往主卧拍摄任务','primary',{id:'bed'}):`<form id="case-code-form"><label class="formfield">附件密码<input id="case-code" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required aria-label="附件密码"></label><p id="case-code-error" class="error"></p><button type="submit" class="primary">解密附件</button></form>`}</div>`);
 if(id==='recovery')return caseFrame('文件 · 最近删除',`<div class="recovery-notice"><b>安住同步缓存</b><p>这里混着多个人的文件，还有事后补录的版本。用旧报道中的姓名与事发日期筛选，选出<strong>3份属于原住户、生前留下的原始文件</strong>。</p>${B('open','去浏览器核对旧报道','text-link',{app:'browser'})}</div>${CASE_FILES.map(f=>B('case-file-pick',`<span class="file-check ${S.phoneCase.selectedFiles.includes(f.id)?'selected':''}">${S.phoneCase.selectedFiles.includes(f.id)?'✓':''}</span><span><b>${f.name}</b><small>创建者 ${f.owner}<br>${f.date}</small></span>`,'recovery-file',{id:f.id})).join('')}<p id="recovery-feedback" class="case-feedback">${S.phoneCase.restored?'三份原始文件已恢复。':'已选择 '+S.phoneCase.selectedFiles.length+' 项'}</p>${B('case-restore-files','恢复选中的文件','primary')}${S.phoneCase.restored?B('case-restored','打开恢复的文件','secondary'):''}`);
 if(id==='identity')return caseFrame('核对居住人身份',`<div class="card"><small>电子回执 · 已恢复</small><h3>槐安二村3幢604</h3><p>沈秋宁 · 服装修改<br>2018年6月13日登记</p></div><p>回执中的地址使用旧门牌。找出与报道相符的信息，归入异常报告。</p>${B('open','查看浏览器资料','secondary',{app:'browser'})}<form id="case-identity-form"><label class="formfield">报道中的姓名<select id="case-person"><option value="">请选择</option><option>沈秋月</option><option>沈秋宁</option><option>周同安</option></select></label><label class="formfield">现在的房号<select id="case-address"><option value="">请选择</option><option>槐安里3栋604</option><option>槐安里6栋604</option><option>槐安里6栋304</option></select></label><label class="formfield">报道中的事发日期<input id="case-date" placeholder="例如 20180614" inputmode="numeric" maxlength="8" aria-label="事发日期"></label><p id="identity-feedback" class="case-feedback">${S.phoneCase.identity?'身份已核实，写入异常报告。':''}</p><button type="submit" class="primary">交叉核对</button></form>`);
 if(id==='verify')return caseFrame('消息身份核验',`<div class="verify-contact">${AV('mom')}<div><h2>${esc(personName('mom'))}</h2><small>已保存的联系人</small></div></div><div class="verify-message"><small>威信 · 刚刚</small><p>“小砚，妈就在门外。把门开一下。”</p></div><p>熟悉的头像不能证明发消息的人是谁。用通讯录里原来的号码回拨，核对她现在的位置。</p>${B('call','拨打妈妈已保存的号码','primary',{id:'mom'})}${S.flags.calledMom?'<blockquote class="phone-quote">电话里的妈妈：“我在家里，跟你爸一起。妈妈根本没去临川。”</blockquote>':''}<p>你要信任哪条信息？</p>${B('case-verify','威信里说她就在门外','secondary',{answer:'message'})}${B('case-verify','回拨电话中确认她仍在家','secondary',{answer:'call'})}<p id="verify-feedback" class="case-feedback">${S.phoneCase.impostor?'冒名消息已标注，不向门外回应。':''}</p>`);
 if(id==='trail')return caseFrame('地图 · 恢复离线轨迹',`<div class="trail-summary"><small>物业疏散路线.gpx</small><h2>把路线接起来</h2><p>起点是604，终点是西侧出口。上一段的终点必须接上下一段的起点。拖动卡片或点箭头调整顺序。</p></div><div class="trail-cards">${S.phoneCase.routeOrder.map((key,i)=>`<article class="trail-card" draggable="true" data-route-key="${key}"><span class="trail-index">${i+1}</span><div><b>${ROUTE_PARTS[key].from} → ${ROUTE_PARTS[key].to}</b><p>${ROUTE_PARTS[key].text}</p></div><div class="trail-arrows">${B('case-route-move','↑','',{id:key,step:-1,label:'上移'+ROUTE_PARTS[key].title})}${B('case-route-move','↓','',{id:key,step:1,label:'下移'+ROUTE_PARTS[key].title})}</div></article>`).join('')}</div><p id="route-feedback" class="case-feedback">${S.phoneCase.routeReady?'路线已连接，已保存到本机离线地图。':''}</p>${B('case-route-check','检查并保存路线','primary')}${S.phoneCase.routeReady?B('case-escape','查看离线导航','secondary'):''}`);
 return caseHub();}
docsView=()=>appHeader('房屋资料','stay-home')+`<div class="scroll pad"><div class="card"><h3>可在手机里查看的资料</h3>${B('case-open','周先生 · 历史聊天附件','setting',{id:'archive'})}${B('case-open','云端同步 · 最近删除','setting',{id:'recovery'})}${B('doc-history','上一位体验员的留言','setting')}${S.phoneCase.restored?B('case-restored','已恢复的原始文件','setting'):''}</div><div class="card"><h3>房屋旧地址</h3><p>新门牌写着槐安里6栋604。旧报道使用什么地址？</p>${B('search-term','搜索社区新旧门牌','secondary',{q:'槐安里604'})}</div>${S.checked?B('report','体验报告','primary'):''}</div>`+stayTabs('docs');
WEB2.news.body=()=>'<div class="masthead">临川晚报 · 旧报存档</div><h2>槐安二村一居民家中身亡</h2><p>2018年6月14日凌晨，槐安二村3幢604发生一起非正常死亡事件。死者沈秋宁，女，32岁，经营服装修改铺。</p><p>邻居称夜里听见女子拍门求救，但入户门没有打开。相关情况仍在调查。</p><p>她生前将日记、社区回执和一份物业路线文件同步到了房屋云盘，文件后来被转入“最近删除”。有些同名文件在两年后才被补录。</p>';
WEB2.forum.body=()=>'<h2>我没有签那张入住声明</h2><p>周先生在找新的“唯一住户”。别让他删掉你的原片。拍全异常、核实原住户身份，把证据发给屋外可信的人，再提交拒绝变更登记的报告。</p><p>云盘最近删除里混着伪造版本，真正的记录创建于她出事之前。恢复文件后，用物业轨迹建立离线路线。</p><p>我靠北侧楼梯、西侧出口离开。楼里的信号不稳定，别等失联了再下载路线。</p><p>门外模仿你亲人的声音。要回拨通讯录里存的号码，不要只相信消息里的头像。</p>';
WEB2.blog.body=()=>'<h2>秋宁的小屋</h2><p>2011年9月20日</p><p>这周六就是婚礼了。终于有自己的小家。</p><p>后续的日记和生活文件都转存到房屋云盘了。</p>'+B('case-open','查看云盘最近删除','primary',{id:'recovery'});
function restoredFiles(){sheet('已恢复 · 3个文件',CASE_FILES.filter(f=>['diary','receipt','route'].includes(f.id)).map(f=>`<div class="card"><small>${f.date}</small><h3>${f.name}</h3><p>${f.text}</p></div>`).join('')+B('case-open','核对原住户身份','primary',{id:'identity'})+B('case-open','整理离线路线','secondary',{id:'trail'}));}
const phoneReportView=reportV2;reportV2=()=>phoneReportView().replace('你不再是登记候选人。但入户门依然锁着，需要从原始户型中的维修通道离开。','你不再是登记候选人。核验门外消息并打开已恢复的离线路线，才能避开错误的出口。').replace('返回现场寻找出口','打开手机调查记录');
submitReport=()=>{S.report.finding=$('#report-finding').value;S.report.name=$('#resident-name').value.trim();save();const err=$('#report-error');if(S.uploads.length<5){err.textContent='请先完成五项照片记录。';return;}if(S.report.finding==='alone')return sheet('确认入住','<p>我确认屋内没有其他居住者，同意登记为唯一住户。</p>'+B('sign-alone','确认签署','danger')+B('close','返回修改','secondary'));if(S.report.finding!=='occupied'){err.textContent='请选择居住情况。';return;}if(!S.phoneCase.identity||S.report.name!=='沈秋宁'){err.textContent='请先交叉核对云端回执和旧报道中的原住户身份。';return;}if(['living','bath','bed'].some(id=>!S.marks[id])){err.textContent='客厅、浴室、卧室原片均需要标记人影。';return;}if(!S.flags.shared){err.textContent='请先把三张异常原片发给小张是好bro备份。';return;}if(!S.read.includes('forum')){err.textContent='前体验员的公开帖子里有关于登记的记录，请先阅读。';return;}S.puzzle.reportRevoked=true;save();checkpoint();open('stay','report');};
function escapeReady(){return S.puzzle.reportRevoked&&S.phoneCase.impostor&&S.phoneCase.routeReady;}
function escapeMap(){const p=Math.min(1,(S.phoneCase.escape?.elapsed||0)/18000),index=Math.min(2,Math.floor(p*3));return appHeader('离线步行导航','case-back')+`<div class="scroll case-detail"><div class="trail-summary"><small>离线地图 · 604 → 西侧出口</small><h2>${ROUTE_PARTS[['start','stairs','exit'][index]].title}</h2><p>${escapeReady()?'路线已在本机保存。跟随指引离开，不回应背后的声音。':'离开前，先撤销入住登记、核验门外消息，并保存离线路线。'}</p></div><div class="escape-route">${['start','stairs','exit'].map((key,i)=>`<div class="escape-stop ${index===i?'current':''} ${index>i?'done':''}"><span>${index>i?'✓':i+1}</span><div><b>${ROUTE_PARTS[key].title}</b><p>${ROUTE_PARTS[key].text}</p></div></div>`).join('')}</div><div class="routeprogress"><i id="escape-progress" style="width:${p*100}%"></i></div><p id="escape-distance">${Math.ceil(180*(1-p))} 米 · 西侧出口</p>${escapeReady()?B('case-walk',S.phoneCase.escape?(S.phoneCase.escape.paused?'继续步行':'暂停步行'):'开始离线步行','primary'):B('case-back','返回调查记录','primary')}</div>`;}
const mapBeforePhone=VIEWS.map;VIEWS.map=()=>S.view==='escape'?escapeMap():mapBeforePhone();
const advanceBeforePhone=advance;advance=ms=>{advanceBeforePhone(ms);const nav=S.phoneCase?.escape;if(!nav||nav.paused||S.ending||document.hidden)return;const old=Math.floor(nav.elapsed/6000);nav.elapsed=Math.min(18000,nav.elapsed+ms);if(nav.elapsed===18000){nav.paused=true;finish('escape');return;}if(S.app==='map'&&S.view==='escape'){if(old!==Math.floor(nav.elapsed/6000))render();const fill=$('#escape-progress'),text=$('#escape-distance');if(fill)fill.style.width=nav.elapsed/180+'%';if(text)text.textContent=Math.ceil(180*(1-nav.elapsed/18000))+' 米 · 西侧出口';}};
VIEWS.ending=()=>`<div class="end-view ${S.ending==='escape'?'':'bad'}"><div class="eyebrow">${S.ending==='escape'?'06:03 / OUTSIDE':'06:00 / STILL INSIDE'}</div><h2>${S.ending==='escape'?'今夜，不入住。':'恭喜，入住成功。'}</h2><div class="end-line">${S.ending==='escape'?'信号消失时，离线地图还亮着。<br><br>你按存好的路线走下北侧楼梯。妈妈的声音在楼上叫你，你把刚才的通话记录看了一遍，没有回头。<br><br>西侧出口的值班室亮着灯。天亮后小张是好bro赶到，她的手机里还存着你发出的所有原片。':'签署成功。<br><br>屏幕上的头像变成了你。最近删除里，多出一份名叫“林砚”的文件。<br><br>biss直聘通知：正在寻找下一位房源体验员。'}</div><div class="receipt">${S.ending==='escape'?'你：妈，我回来了。<br>妈妈：回来就好。':'登记住户：林砚<br>居住期限：长期'}</div><div class="buttons">${B('ending-photos','查看照片','primary')}${B('restore','恢复最近检查点','secondary')}${B('restart','重新开始','secondary')}</div></div>`;
function caseHint(){let msg;if(!S.checked)return houseHint();if(!hasPhoto('living'))msg='先按任务拍摄并提交玄关和客厅。';else if(!S.phoneCase.photoVerified)msg='调查 → 照片暗部检查。提高曝光，再点窗帘后不该存在的人影。';else if(!hasPhoto('bath'))msg='浴室任务已经可以拍摄。';else if(!S.phoneCase.attachment)msg='检索历史聊天中的“验收”，保存相关消息，用2020年10月日历推算那周周六。';else if(!hasPhoto('bed'))msg='主卧的机位附件已解密，可以继续拍摄。';else if(!S.phoneCase.restored)msg='查旧报道确认姓名和事发日。在最近删除中选择同一个人事发前留下的三份文件。';else if(!S.phoneCase.identity)msg='用新旧门牌查询和旧报道，对照已恢复的社区电子回执。';else if(!S.phoneCase.impostor)msg='给妈妈已保存的号码回拨，比较电话与威信中她自称的位置。';else if(!S.phoneCase.routeReady)msg='整理离线轨迹：从604开始，让每段终点接到下一段起点。';else if(!S.puzzle.reportRevoked)msg='完成五项拍摄和三处标记，发给小张是好bro备份，再核对报告。';else msg='打开离线地图，开始步行离开。';sheet('调查提示','<p>'+msg+'</p>');}
Object.assign(ACTIONS,{
 'case-back':()=>open('stay','onsite'),'case-open':d=>{close();open('stay','case:'+d.id);},
 'case-pin':d=>{const m=ARCHIVE_MESSAGES.find(m=>m.id===d.id);if(m?.key){S.phoneCase.archivePinned=true;save();render();}else sheet('线索不完整','<p>这条消息没有同时说明验收日期和密码规则。试着查找更完整的一条。</p>');},
 'case-file-pick':d=>{if(S.phoneCase.restored)return restoredFiles();const a=S.phoneCase.selectedFiles,i=a.indexOf(d.id);if(i>=0)a.splice(i,1);else a.push(d.id);save();render();},
 'case-restore-files':()=>{if(!S.read.includes('news')){$('#recovery-feedback').textContent='先读旧报道，确认原住户是谁、何时出事。';return;}if(S.phoneCase.selectedFiles.slice().sort().join(',')!=='diary,receipt,route'){$('#recovery-feedback').textContent='所选文件不匹配。核对创建者和创建日期，留意同名补录版本。';return;}S.phoneCase.restored=true;save();render();},'case-restored':restoredFiles,
 'case-verify':d=>{if(!S.flags.calledMom){$('#verify-feedback').textContent='先拨打通讯录里已保存的号码，取得独立核实。';return;}if(d.answer!=='call'){$('#verify-feedback').textContent='同一时刻的位置互相矛盾。消息里的头像可以被冒用。';return;}S.phoneCase.impostor=true;save();render();},
 'case-route-move':d=>{const a=S.phoneCase.routeOrder,i=a.indexOf(d.id),j=i+Number(d.step);if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];S.phoneCase.routeReady=false;save();render();},
 'case-route-check':()=>{if(S.phoneCase.routeOrder.join(',')!=='start,stairs,exit'){$('#route-feedback').textContent='路线中途断开了。对照卡片上的起点和终点，再调整顺序。';return;}S.phoneCase.routeReady=true;save();render();},
 'case-escape':()=>{close();open('map','escape');},'case-walk':()=>{if(!escapeReady())return;if(!S.phoneCase.escape)S.phoneCase.escape={elapsed:0,paused:false};else S.phoneCase.escape.paused=!S.phoneCase.escape.paused;save();render();},
 hint:caseHint,'hidden-exit':()=>open('map','escape'),escape:()=>open('map','escape'),inspect:()=>open('stay','onsite'),
 'doc-oldplan':()=>open('stay','case:trail'),'doc-current':()=>open('stay','case:trail'),'doc-diary':restoredFiles,'doc-meter':()=>open('stay','case:exposure'),'album-unlock':()=>open('stay','case:recovery')
});
document.addEventListener('input',e=>{if(e.target.id==='case-exposure'){S.phoneCase.exposure=Number(e.target.value);const img=$('#exposure-image');img.style.opacity=S.phoneCase.exposure/100;img.style.filter=`brightness(${1+S.phoneCase.exposure/85})`;$('#exposure-value').textContent=S.phoneCase.exposure;save();}});
document.addEventListener('pointerup',e=>{if(e.target.id!=='exposure-image')return;const rc=e.target.getBoundingClientRect(),x=(e.clientX-rc.left)/rc.width,y=(e.clientY-rc.top)/rc.height;if(S.phoneCase.exposure>=55&&x>=.77&&x<=.96&&y>=.22&&y<=.40){S.phoneCase.photoVerified=true;S.puzzle.power=true;S.marks.living={x,y};save();render();}else $('#case-photo-feedback').textContent=S.phoneCase.exposure<55?'暗部仍看不清，再提高一点曝光。':'这里与取景没有明显区别，检查右侧窗帘。';});
document.addEventListener('submit',e=>{if(e.target.id==='case-search-form'){S.phoneCase.archiveQuery=$('#case-search').value.trim();save();render();}if(e.target.id==='case-code-form'){if(!S.phoneCase.archivePinned){$('#case-code-error').textContent='先检索并保存说明密码规则的那条聊天记录。';return;}if($('#case-code').value!=='1024'){$('#case-code-error').textContent='密码不符。帖子发布于周二，“这周六”是哪一天？';return;}S.phoneCase.attachment=true;S.puzzle.bedroom=true;save();render();}if(e.target.id==='case-identity-form'){if(!S.puzzle.mapping||!S.read.includes('news')){$('#identity-feedback').textContent='先查询新旧门牌，并阅读对应旧报道。';return;}if($('#case-person').value==='沈秋宁'&&$('#case-address').value==='槐安里6栋604'&&$('#case-date').value==='20180614'){S.phoneCase.identity=true;S.puzzle.drawer=true;S.report.name='沈秋宁';save();$('#identity-feedback').textContent='身份已核实，写入异常报告。';}else $('#identity-feedback').textContent='信息未能对应。回执使用的是旧楼号，注意报道中的事发日。';}});
let draggedRoute=null;document.addEventListener('dragstart',e=>{const el=e.target.closest('[data-route-key]');if(el){draggedRoute=el.dataset.routeKey;e.dataTransfer.setData('text/plain',draggedRoute);}});document.addEventListener('dragover',e=>{if(e.target.closest('[data-route-key]'))e.preventDefault();});document.addEventListener('drop',e=>{const el=e.target.closest('[data-route-key]');if(!el||!draggedRoute)return;e.preventDefault();const a=S.phoneCase.routeOrder,i=a.indexOf(draggedRoute),j=a.indexOf(el.dataset.routeKey);if(i<0||j<0)return;a.splice(i,1);a.splice(j,0,draggedRoute);draggedRoute=null;S.phoneCase.routeReady=false;save();render();});
const textBeforePhone=window.render_game_to_text;window.render_game_to_text=()=>JSON.stringify({...JSON.parse(textBeforePhone()),phoneInvestigation:S.phoneCase,investigationVersion:3});
const CASE_TARGETS={exposure:'photos',archive:'wechat',recovery:'files',identity:'stay',verify:'phone',trail:'map'};
for(const app of ['photos','wechat','files','phone','map']){const original=VIEWS[app];VIEWS[app]=()=>S.view.startsWith('case:')?caseView(S.view.slice(5)):original()+(app==='photos'&&hasPhoto('living')?`<div class="sticky-actions">${B('case-open','编辑 · 检查客厅照片暗部','secondary',{id:'exposure'})}</div>`:app==='files'&&hasPhoto('bed')?`<div class="sticky-actions">${B('case-open','安住云盘 · 最近删除','secondary',{id:'recovery'})}</div>`:'');}
ACTIONS['case-open']=d=>{close();open(CASE_TARGETS[d.id]||'stay','case:'+d.id);};
save();render();
