'use strict';
// Browser navigation is explicit. Search fields are never populated by story events.
const beforeRealDefaults=v2Defaults;
v2Defaults=s=>{beforeRealDefaults(s);if(!s.web){s.web={version:1,stack:[],at:-1,bookmarks:[],category:'网页',hotPage:0};s.query='';s.forum.query='';if(s.app==='browser')s.view='';}s.forum.follows??=s.forum.following?['夜航不靠岸']:[];s.forum.bars??=[];s.forum.replies??={};s.forum.onlyOwner??=false;s.forum.reverse??=false;s.forum.limit??=12;return s;};v2Defaults(S);
const FORUM_AVATARS={'奶油卷':0,'鱼饼':1,'山路':2,'阿岚':3,'老楼北窗':4,'晚风':5,'夜航不靠岸':6,'电台失眠':7,'今天遛狗了吗':8};
forumFace=name=>{if(name==='维修老何')return '<span class="tb-avatar" role="img" aria-label="维修老何头像" style="background-image:url(assets/zhou-moment-repair-2021.png)"></span>';if(name==='林砚')return '<span class="tb-avatar" role="img" aria-label="林砚头像" style="background-image:url(assets/player-avatar.png)"></span>';if(name==='周同安')return `<span class="tb-avatar" role="img" aria-label="周同安头像" style="background-image:url(assets/${isHaunted()?'hr-zhou-ghost-v2.png':'hr-zhou.png'})"></span>`;if(name==='站务')return '<span class="tb-avatar tb-staff" role="img" aria-label="站务头像">贴</span>';const cell=FORUM_AVATARS[name];if(cell!==undefined)return `<span class="tb-avatar tb-atlas" role="img" aria-label="${esc(name)}头像" data-avatar-cell="${cell}" style="background-position:${cell%3*50}% ${Math.floor(cell/3)*50}%"></span>`;const hue=[...name].reduce((n,c)=>n+c.charCodeAt(0),0)%360;return `<span class="tb-avatar tb-fallback" role="img" aria-label="${esc(name)}头像" style="background:hsl(${hue} 45% 55%)">${esc(name[0])}</span>`;};
const EVERYDAY_POSTS=[
 ['morning','晚风','临川吧','生活','周末沿江散步，发现这条路很舒服','江北路一直走到河堤，傍晚有风。人不多，还能看见有人钓鱼。','wx-cover-hao-v6.png'],
 ['rent','阿岚','租房吧','生活','毕业后第一次租房，押一付一要注意什么','今天看了三个房子，有一个窗户朝走廊。大家签合同前一般会检查哪些地方？',''],
 ['dogwalk','今天遛狗了吗','宠物吧','生活','晚上遛狗被它拽着走了三公里','别人遛狗，我被狗遛。到家躺门口一动不动，开了罐头才起来。','wx-dog.png'],
 ['cameraused','电台失眠','摄影吧','生活','预算两千，买二手微单还是继续用手机','主要拍拍日常和街景，不追求器材，想听听实际用过的人怎么选。','wx-cover-qiao-v6.png'],
 ['eat','奶油卷','临川吧','生活','整理一下江北区吃过还想再吃的小店','面馆、砂锅、烤红薯。没有推广，就是周末乱逛吃到的，慢慢往楼里补。','life-dinner.png'],
 ['jobs','鱼饼','打工吧','夜班','简历投了二十家，今天终于接到面试电话','普通运营岗，薪资不高但离家近。回来给大家说结果，希望别再已读不回了。',''],
 ['bus','山路','临川吧','旧城','末班公交改时间了吗，有没有最近坐过的','昨晚22:40去站台已经没有车了。站牌上贴的还是去年的时刻表。',''],
 ['plants','阿岚','生活吧','生活','救救这盆绿萝，怎么越浇水越蔫','放在朝北的窗台，一周浇两次。是不是浇太多了，有懂的朋友吗？','wx-cover-mom-v6.png'],
 ['music','电台失眠','音乐吧','夜班','来聊聊下夜班路上最常听的一首歌','路上没什么人，戴一只耳机，走到面馆正好听完一张专辑。',''],
 ['coffee','奶油卷','生活吧','生活','今天的咖啡拉花失败，但味道还行','本来想拉一只猫，朋友说像刚出锅的煎蛋。算了，下次继续练。','life-coffee.png'],
 ['elevator','老楼北窗','临川吧','旧城','槐安里6栋楼道灯已经修好了','物业下午来换了声控灯。604门口那一盏接触不好，师傅说下周再来看。大家晚上上下楼注意。',''],
 ['movie','晚风','电影吧','生活','有没有适合周末一个人慢慢看的电影','最近不太想看节奏太快的，想找些有人情味的故事。欢迎分享片单。',''],
 ['room604','阿岚','租房吧','生活','看房遇到604，朝向还不错但有点潮','看的不是江北那套，是城南新小区。梅雨季大家一般怎么除湿？',''],
 ['laundry','今天遛狗了吗','生活吧','生活','洗衣机洗完一身纸屑怎么救','兜里藏了半包纸巾，黑衣服全是白点，已经开始怀疑人生。',''],
 ['moon','山路','摄影吧','生活','手机拍月亮真的需要长焦吗','试着用专业模式压低曝光，意外拍到了月亮的轮廓。参数发在二楼。','wx-cover-dad-v6.png'],
 ['shiftfood','鱼饼','打工吧','夜班','夜班带饭求推荐，不想每天都点外卖','公司只有微波炉，求便宜、吃完不犯困的菜。番茄炒蛋已经吃腻了。',''],
 ['market','老楼北窗','临川吧','旧城','槐安里周日早市还在，别跑空了','现在摊位挪到东门，卖豆腐的阿姨还在。早上九点半基本收摊。',''],
 ['catfood','晚风','宠物吧','生活','家里主子只吃冻干，不爱吃猫粮','换了两种粮都不吃，想问问怎么慢慢改回来。精神和喝水都正常。','']
].map(([id,author,bar,tag,title,body,image],i)=>({id:'daily-'+id,author,bar,tag,title,text:[body],image:image||undefined,date:`2026-09-${String(13-Math.floor(i/7)).padStart(2,'0')} ${String(21-i%7).padStart(2,'0')}:12`,likes:12+i*7,comments:[['鱼饼',i%2?'蹲一个后续。':'来了，先顶一下。'],['阿岚',i%2?'我也想知道。':'同城的，留个脚印。']]}));
FORUM_POSTS.push(...EVERYDAY_POSTS);
FORUM_POSTS.find(p=>p.id==='welcome').title='【吧务】临川吧新人报到与交流须知';
FORUM_POSTS.find(p=>p.id==='welcome').text=['欢迎临川的朋友。聊生活、聊工作，分享身边的新鲜事。','发布帖子时选好分类，请勿重复刷屏。遇到问题可以联系吧务。'];
const TB_BARS=['临川吧','生活吧','打工吧','租房吧','摄影吧','宠物吧','音乐吧'];
function postBar(p){return p.bar||(['work','normal','awake','door','last','building','rain','welcome'].includes(p.id)?'临川吧':p.id==='cat'?'宠物吧':p.tag==='夜班'?'打工吧':'生活吧');}
function tbUser(){return S.forum.user==='nightboat'?'夜航不靠岸':'林砚';}
function forumAccountId(author){const known={'夜航不靠岸':'nightboat','林砚':'summer_lin','秋天有芸':'autumn_qy','向海的日常':'zhou2006'};if(known[author])return known[author];const index=Object.keys(FORUM_AVATARS).indexOf(author);if(index>=0)return index+'_lc';let hash=2166136261;for(const char of author)hash=Math.imul(hash^char.codePointAt(0),16777619)>>>0;return 'lc_'+hash.toString(36);}
function searchPosts(q){const normalized=q.trim().toLowerCase(),parts=normalized.split(/\s+/).filter(Boolean);if(!parts.length)return forumPosts();return forumPosts().filter(p=>{const hay=[p.title,p.author,postBar(p),...p.text].join(' ').toLowerCase();if(parts.every(t=>hay.includes(t)))return true;return /槐安|6.?栋.?604|3.?幢.?604/.test(normalized)&&['work','normal','awake','door','last','building','daily-elevator','daily-market'].includes(p.id);});}
function browserAddress(){if(S.view.startsWith('forum:'))return 'tieba.baiduu.invalid';return 'm.baiduu.invalid';}
function webBar(){const w=S.web;return `<div class="web-address">${B('browser-address','<span>大小</span><b>'+I('lock')+browserAddress()+'</b>','web-address-pill')}${B('browser-reload',I('rotate'),'',{label:'刷新网页'})}</div><nav class="web-toolbar">${B('browser-back',I('back'),'',{label:'后退'})}${B('browser-forward',I('next'),'',{label:'前进'})}${B('browser-share',I('upload'),'',{label:'分享网页'})}${B('browser-bookmarks',I('files'),'',{label:'书签和历史'})}${B('browser-tabs','<span class="web-tab-count">'+Math.max(1,w.stack.length)+'</span>','',{label:'浏览记录'})}</nav>`;}
function webRememberScroll(){if(S.app!=='browser')return;const entry=S.web.stack[S.web.at],sc=$('#screen .scroll');if(entry&&entry.view===S.view&&sc)entry.scrollTop=sc.scrollTop;}
function webRestoreScroll(entry){const sc=$('#screen .scroll');if(!sc)return;const target=Math.max(0,Number(entry?.scrollTop)||0);sc.scrollTop=target;const app=S.app,view=S.view,initial=sc.scrollTop;Promise.all([...sc.querySelectorAll('img')].map(img=>img.decode().catch(()=>{}))).then(()=>{if(S.app===app&&S.view===view&&sc.isConnected&&Math.abs(sc.scrollTop-initial)<=1&&Math.abs(sc.scrollTop-target)>1)sc.scrollTop=target;});}
function recordWeb(){const w=S.web,entry={view:S.view,query:S.query,forumQuery:S.forum.query,scrollTop:0};const current=w.stack[w.at];if(!current||['view','query','forumQuery'].some(key=>entry[key]!==current[key])){w.stack=w.stack.slice(0,w.at+1);w.stack.push(entry);w.at=w.stack.length-1;save();}}
const openBeforeReal=open;open=(app,view='')=>{v2Defaults(S);webRememberScroll();if(app==='browser'&&!view){S.query='';S.web.category='网页';}openBeforeReal(app,view);if(app==='browser')recordWeb();};
function webRestore(index,remember=true){const w=S.web;if(index<0||index>=w.stack.length)return;if(remember)webRememberScroll();w.at=index;const entry=w.stack[index];S.query=entry.query;S.forum.query=entry.forumQuery;openBeforeReal('browser',entry.view);webRestoreScroll(entry);save();}
const openAppBeforeWebResume=ACTIONS.open;ACTIONS.open=data=>{const entry=data.app==='browser'&&!data.view&&S.app!=='browser'?S.web.stack[S.web.at]:null;if(!entry)return openAppBeforeWebResume(data);S.query=entry.query;S.forum.query=entry.forumQuery;open('browser',entry.view);webRestoreScroll(entry);};
function baiduLogo(){return '<div class="baidu-logo fictional-search-logo" aria-label="佰度"><svg class="fictional-search-mark" role="img" aria-label="佰度检索标志" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect x="5" y="5" width="54" height="54" rx="17" fill="#197c91"/><path d="M18 22h20a10 10 0 0 1 0 20H23" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round"/><path d="m38 38 10 10" stroke="#ffd074" stroke-width="5" stroke-linecap="round"/><circle cx="20" cy="32" r="3" fill="#ffd074"/></svg><span>佰度<small>BAIDUU</small></span></div>';}
function baiduSearchForm(result=false){return `<form id="search-form" class="baidu-search-form"><input id="search-input" aria-label="搜索关键词" placeholder="${result?'':'找一找，答案就在这里'}" autocomplete="off" value="${result?esc(S.query):''}">${B('baidu-clear','×','',{label:'清空搜索'})}<button type="submit">佰度搜索</button></form>`;}
const HOT_SEARCHES=['临川周末去哪儿玩','应届生面试穿什么','家常菜一周食谱','夜跑后怎么拉伸','手机拍照构图技巧','秋天适合养什么花','租房第一次看房注意什么','通勤路上听什么歌'];
function baiduHome(){return `<div class="scroll baidu-page"><div class="baidu-top"><span>临川　18°</span>${B('browser-menu','☰','',{label:'浏览器菜单'})}</div>${baiduLogo()}${baiduSearchForm()}<div class="baidu-shortcuts">${[['贴吧','tb-home','贴吧'],['图片','baidu-channel','图片'],['资讯','baidu-channel','资讯'],['地图','open','map']].map(([t,a,v])=>B(a,`<span>${I(t==='地图'?'map':t==='贴吧'?'wechat':t==='图片'?'photos':'files')}</span>${t}`,'',a==='open'?{app:v}:{channel:v})).join('')}</div><section class="baidu-hot"><div><h3>佰度热搜</h3>${B('baidu-hot-refresh','换一换')}</div>${HOT_SEARCHES.slice(S.web.hotPage*4,S.web.hotPage*4+4).map((q,i)=>B('search-term',`<b>${i+1}</b><span>${q}</span>${i===0?'<em>热</em>':''}`,'',{q})).join('')}</section><p class="baidu-footer">找一找，答案就在这里</p></div>`+webBar();}
function baiduResults(){const list=searchPosts(S.query),category=S.web.category;return `<div class="baidu-results-head">${B('browser-home','<strong>佰度</strong>')}${baiduSearchForm(true)}</div><div class="baidu-result-tabs">${['网页','贴吧','图片','资讯'].map(t=>B('baidu-result-tab',t,category===t?'active':'',{tab:t})).join('')}</div><div class="scroll baidu-results">${category==='图片'?`<div class="baidu-image-results">${list.filter(p=>p.image).map(p=>B('forum-post',`<img src="assets/${p.image}" alt="${esc(p.title)}"><p>${esc(p.title)}</p>`,'',{id:p.id})).join('')||'<p class="empty">未找到相关图片</p>'}</div>`:list.length?list.map(p=>B('forum-post',`<small><i>贴</i>佰度贴吧　·　${esc(postBar(p))}</small><h3>${esc(p.title)}</h3><p>${esc(p.text.join(' ').slice(0,100))}</p><span>${p.date.split(' ')[0]}　${esc(p.author)}</span>`,'baidu-result',{id:p.id})).join(''):'<div class="baidu-empty"><h3>没有找到相关结果</h3><p>试试其他关键词。</p></div>'}${B('tb-home','佰度贴吧　进入兴趣社区　›','baidu-site-link')}</div>`+webBar();}
doSearch=q=>{const value=(q??$('#search-input')?.value??'').trim();if(!value)return;S.query=value;if(!S.history.includes(value))S.history.push(value);S.web.category='网页';open('browser','search');};
forumLink=view=>{if(view==='home'){S.forum.query='';S.forum.tab='全部';S.forum.limit=12;}open('browser','forum:'+view);};
forumHeader=()=>'';
function tbHeader(title,extra=''){return `<div class="tb-header">${B('browser-back',I('back'),'',{label:'返回'})}<strong>${title}</strong><div>${extra||B('tb-search-open',I('search'),'',{label:'搜索贴吧'})}</div></div>`;}
forumNav=active=>`<nav class="tb-nav">${[['home','首页','home'],['bars','进吧','files'],['compose','发布','plus'],['inbox','消息','wechat'],['me','我的','user']].map(([v,t,i])=>B('forum-go',I(i)+`<span>${t}</span>`,active===v?'active':'',{view:v})).join('')}</nav>`;
function tbFollowing(){return S.forum.user==='nightboat'?(S.forum.nightboatFollows??=['老楼北窗']):S.forum.follows;}
function tbAccountStats(author){const posts=forumPosts().filter(p=>p.author===author);return {followers:author==='夜航不靠岸'?127+Number(S.forum.follows.includes(author)):author==='林砚'?0:32,following:author==='夜航不靠岸'?40+(S.forum.nightboatFollows??['老楼北窗']).length:author==='林砚'?S.forum.follows.length:19,likes:posts.reduce((sum,p)=>sum+(p.likes||0)+Number(S.forum.likes.includes(p.id)),0)};}
function tbFollow(name){if(name===tbUser())return '';return B('tb-follow',tbFollowing().includes(name)?'已关注':'+ 关注',tbFollowing().includes(name)?'tb-follow followed':'tb-follow',{author:name});}
forumCard=p=>`<article class="tb-card" data-post="${p.id}"><div class="tb-byline">${B('forum-profile',forumFace(p.author),'',{author:p.author})}<div>${B('forum-profile',esc(p.author),'tb-name',{author:p.author})}<small>${p.date.split(' ')[0]}　${esc(postBar(p))}</small></div>${B('tb-post-more',I('dots'),'',{id:p.id,label:'帖子菜单'})}</div>${B('forum-post',`<h3>${esc(p.title)}</h3><p>${esc(p.text[0])}</p>${p.image?`<img class="tb-card-image" src="assets/${p.image}" alt="帖子配图">`:''}`,'tb-card-body',{id:p.id})}<div class="tb-card-actions">${B('forum-share',I('upload')+'分享','',{id:p.id})}${B('forum-post',I('wechat')+String((p.comments?.length||0)+(S.forum.comments[p.id]?.length||0)),'',{id:p.id})}${B('forum-like',I('heart')+String((p.likes||0)+(S.forum.likes.includes(p.id)?1:0)),S.forum.likes.includes(p.id)?'liked':'',{id:p.id})}</div></article>`;
function tbSorted(list){return [...list].sort((a,b)=>S.forum.sort==='hot'?(b.likes||0)-(a.likes||0):b.date.localeCompare(a.date));}
function tbList(list){return list.slice(0,S.forum.limit).map(forumCard).join('')+(list.length>S.forum.limit?B('tb-more','加载更多','tb-load-more'):'<p class="tb-end">没有更多了</p>');}
forumHome=()=>`<div class="tb-home-top"><b>佰度贴吧</b>${B('tb-search-open',I('search')+' 搜你感兴趣的吧','tb-search-pill')}${B('forum-go',I('user'),'',{view:'me',label:'我的'})}</div><div class="tb-feed-tabs">${[['全部','推荐'],['关注','关注'],['热榜','热榜']].map(([id,t])=>B('tb-feed',t,S.forum.tab===id?'active':'',{tab:id})).join('')}</div><div class="scroll tb-scroll"><div class="tb-interest-row">${['临川吧','打工吧','生活吧','摄影吧'].map((bar,i)=>B('tb-bar',`<span class="tb-bar-icon c${i}">${bar.slice(0,2)}</span><b>${bar}</b>`,'',{bar})).join('')}</div>${tbList(tbSorted(forumPosts().filter(p=>S.forum.tab!=='关注'||tbFollowing().includes(p.author)||S.forum.bars.includes(postBar(p)))))}</div>`+forumNav('home');
function tbBarView(bar){const all=forumPosts().filter(p=>postBar(p)===bar),joined=S.forum.bars.includes(bar);return tbHeader(bar)+`<div class="scroll tb-scroll"><div class="tb-bar-cover"><span class="tb-bar-icon">${bar.slice(0,2)}</span><div><h2>${bar}</h2><p>关注 1.2万　帖子 ${all.length}</p></div>${B('tb-join',joined?'已关注':'+ 关注','tb-follow',{bar})}</div><p class="tb-bar-desc">分享身边的生活，和志同道合的吧友聊聊。</p><div class="tb-bar-tools">${B('tb-sort','全部帖子 '+(S.forum.sort==='new'?'↓ 最新':'↓ 热门'))}${B('tb-search-open','吧内搜索','',{bar})}${B('forum-go','发帖','',{view:'compose'})}</div>${B('forum-post','置顶　吧友交流须知与新人报到　›','tb-pinned',{id:'welcome'})}${tbList(tbSorted(all))}</div>`+forumNav('bars');}
function tbSearchView(){const q=S.forum.query;return tbHeader('搜索')+`<form id="tb-search" class="tb-search-form"><input id="forum-query" aria-label="搜索论坛" autocomplete="off" placeholder="搜索吧、帖子、用户" value="${esc(q)}"><button type="submit">搜索</button></form><div class="tb-feed-tabs"><b>帖子</b></div><div class="scroll tb-scroll">${q?tbList(tbSorted(searchPosts(q))):`<div class="tb-search-history"><h3>搜索历史</h3>${[...new Set(S.forum.searches)].reverse().slice(0,8).map(t=>B('tb-search-term',esc(t),'',{q:t})).join('')||'<p>暂无搜索历史</p>'}</div>`}</div>`;}
forumArticle=id=>{const p=forumPost(id);if(!p)return tbHeader('帖子')+'<p class="empty">帖子不存在</p>';let comments=[...(p.comments||[]),...(S.forum.comments[id]||[])].map(([author,text],i)=>({author,text,floor:i+2}));if(S.forum.onlyOwner)comments=comments.filter(c=>c.author===p.author);if(S.forum.reverse)comments.reverse();return tbHeader(postBar(p),B('tb-post-more',I('dots'),'',{id,label:'帖子菜单'}))+`<div class="scroll tb-scroll"><article class="tb-thread"><h1>${esc(p.title)}</h1><div class="tb-byline">${B('forum-profile',forumFace(p.author),'',{author:p.author})}<div>${B('forum-profile',esc(p.author),'tb-name',{author:p.author})}<span class="tb-level">Lv.${p.author==='夜航不靠岸'?5:8}</span><small>${p.date}　IP属地：临川</small></div>${tbFollow(p.author)}</div><div class="tb-post-text">${p.text.map(t=>'<p>'+esc(t)+'</p>').join('')}${p.image?B('forum-image',`<img src="assets/${p.image}" alt="帖子图片">`,'',{id}):''}</div><div class="tb-floor-meta"><span>1楼 · 楼主</span>${B('forum-save',S.forum.saved.includes(id)?'已收藏':'收藏','',{id})}${B('forum-share','分享','',{id})}</div></article><section class="tb-replies"><div class="tb-reply-head"><strong>全部回复 ${comments.length}</strong><div>${B('tb-only-owner',S.forum.onlyOwner?'显示全部':'只看楼主')}${B('tb-reverse',S.forum.reverse?'正序':'倒序')}</div></div>${comments.map(c=>`<div class="tb-reply">${B('forum-profile',forumFace(c.author),'',{author:c.author})}<div>${B('forum-profile',esc(c.author),'tb-name',{author:c.author})}${c.author===p.author?'<em class="tb-owner">楼主</em>':''}<small>${c.floor}楼</small><p>${esc(c.text)}</p>${(S.forum.replies[id+':'+c.floor]||[]).map(r=>`<div class="tb-sub-reply"><b>${esc(r.author)}</b>：${esc(r.text)}</div>`).join('')}${B('tb-floor-reply','回复','tb-reply-link',{id,floor:c.floor,author:c.author})}</div></div>`).join('')||'<p class="empty">暂无回复</p>'}</section></div><form id="forum-comment-form" data-id="${id}" class="tb-composer"><input id="forum-comment-text" aria-label="回复帖子" maxlength="300" placeholder="我来说两句…" value="${esc(S.forum.drafts['comment:'+id]||'')}"><button type="submit">回复</button>${B('forum-like',I('heart')+((p.likes||0)+(S.forum.likes.includes(id)?1:0)),S.forum.likes.includes(id)?'liked':'',{id})}</form>`;};
forumProfile=author=>{const old=author==='夜航不靠岸',list=forumPosts().filter(p=>p.author===author);return tbHeader('个人主页')+`<div class="scroll tb-scroll"><div class="tb-profile-cover"></div><div class="tb-profile"><div class="tb-profile-avatar">${forumFace(author)}${tbFollow(author)}</div><h2>${esc(author)}</h2><p>贴吧账号：${forumAccountId(author)}</p><p>${old?'摄影新手 / 一人一猫 / 希望明年能换一个有阳台的房间。':'生活里，总有值得聊聊的事。'}</p>${old?'<p class="tb-offline">离线 · 最后发帖 2024-11-07 03:17</p>':''}<div class="tb-profile-stats"><span><b>${list.length}</b>帖子</span><span><b>${tbAccountStats(author).followers}</b>粉丝</span><span><b>${tbAccountStats(author).following}</b>关注</span>${B('forum-message',I('wechat')+' 私信','tb-message-btn',{author})}</div></div><div class="tb-feed-tabs"><b>帖子</b></div>${tbList(tbSorted(list))}</div>`;};
forumLogin=()=>tbHeader('登录佰度账号')+`<div class="scroll tb-scroll tb-login"><h2>账号密码登录</h2><p>登录后体验更多服务</p><form id="forum-login"><input id="forum-account" aria-label="账号" autocomplete="off" placeholder="用户名" value="${esc(S.forum.drafts.account||'')}"><input id="forum-password" aria-label="密码" autocomplete="off" type="password" placeholder="密码"><p class="forum-error" role="alert">${esc(S.forum.loginError)}</p><button type="submit" class="tb-login-submit">登录</button></form>${B('forum-password-hint','忘记密码？','tb-forgot')}<p class="tb-login-agreement">登录即表示同意${B('tb-agreement','用户协议')}和${B('tb-privacy','隐私政策')}</p></div>`;
forumMine=()=>tbHeader('我的',B('tb-account-menu',I('dots'),'',{label:'账号设置'}))+`<div class="scroll tb-scroll"><div class="tb-mine">${forumFace(tbUser())}<div><h2>${tbUser()}</h2><p>${S.forum.user==='nightboat'?'nightboat':'summer_lin'}</p></div></div><div class="tb-my-stats"><span><b>${tbAccountStats(tbUser()).following}</b>关注</span><span><b>${tbAccountStats(tbUser()).followers}</b>粉丝</span><span><b>${tbAccountStats(tbUser()).likes}</b>获赞</span></div>${[['myposts','我的帖子'],['saved','我的收藏'],['history','浏览历史'],['drafts','草稿箱'],['bars','关注的吧']].map(([view,t])=>B('forum-go',t+I('next'),'tb-menu',{view})).join('')}${B('forum-go','切换账号'+I('next'),'tb-menu',{view:'login'})}</div>`+forumNav('me');
const forumPrivateBeforeReal=forumPrivate,forumInboxBeforeReal=forumInbox;
forumPrivate=view=>S.forum.user!=='nightboat'?forumLogin():tbHeader(view.startsWith('dm:')?'私信':view==='drafts'?'草稿箱':'草稿')+forumPrivateBeforeReal(view).replaceAll('ONLY ME','').replaceAll('PRIVATE MESSAGE','').replaceAll('仅自己可见 · 从未发布','仅自己可见');
forumInbox=()=>tbHeader('消息')+forumInboxBeforeReal().replace(/<div class="forum-page-title">[\s\S]*?<\/div>/,'');
function tbBars(){return tbHeader('进吧')+`<div class="scroll tb-scroll"><div class="tb-bars-title">${S.forum.bars.length?'我关注的吧':'推荐关注'}</div>${TB_BARS.map((bar,i)=>B('tb-bar',`<span class="tb-bar-icon c${i%4}">${bar.slice(0,2)}</span><span><b>${bar}</b><small>${S.forum.bars.includes(bar)?'已关注':'发现同好，聊你喜欢'}</small></span>${I('next')}`,'tb-bar-row',{bar})).join('')}</div>`+forumNav('bars');}
const forumViewBeforeReal=forumView;forumView=()=>{const v=S.view.slice(6);if(v==='search')return tbSearchView();if(v==='bars')return tbBars();if(v.startsWith('bar:'))return tbBarView(v.slice(4));if(['saved','history','myposts'].includes(v)){const ids=v==='saved'?S.forum.saved:v==='history'?S.forum.history:forumPosts().filter(p=>p.author===tbUser()).map(p=>p.id);return tbHeader({saved:'我的收藏',history:'浏览历史',myposts:'我的帖子'}[v])+`<div class="scroll tb-scroll">${ids.map(forumPost).filter(Boolean).map(forumCard).join('')||'<p class="empty">暂无内容</p>'}</div>`;}if(v==='compose')return tbHeader('发帖')+forumViewBeforeReal().replace('<div class="forum-page-title"><h2>发布新帖子</h2></div>','');return forumViewBeforeReal();};
VIEWS.browser=()=>{v2Defaults(S);if(S.view.startsWith('forum:'))return `<div class="tb-web-content">${forumView()}</div>`+webBar();return S.view==='search'?baiduResults():baiduHome();};
function repaintKeepScroll(){const sc=$('#screen .scroll'),y=sc?.scrollTop;render();if(y)$('#screen .scroll')?.scrollTo(0,y);}
Object.assign(ACTIONS,{
 'browser-home':()=>open('browser'),'browser-back':()=>webRestore(S.web.at-1),'browser-forward':()=>webRestore(S.web.at+1),'browser-reload':()=>{webRememberScroll();render();webRestoreScroll(S.web.stack[S.web.at]);},
 'browser-address':()=>sheet('地址栏',`<form id="web-address-form"><input id="web-address-input" aria-label="网址或搜索内容" placeholder="搜索或输入网站名称" value="${browserAddress()}"><button type="submit" class="primary">前往</button></form>`),
 'browser-tabs':()=>sheet('浏览记录',S.web.stack.map((e,i)=>B('web-history-entry',(i+1)+'　'+(e.view.startsWith('forum:')?'佰度贴吧':e.query||'佰度首页'),'setting',{index:i})).join('')),
 'web-history-entry':d=>webRestore(Number(d.index)),
 'browser-bookmarks':()=>sheet('书签与历史',B('web-bookmark-add','添加当前网页到书签','setting')+S.web.bookmarks.map((e,i)=>B('web-bookmark-open',esc(e.query||e.view.replace('forum:','贴吧 · ')||'佰度首页'),'setting',{index:i})).join('')+B('history','搜索历史','setting')),
 'web-bookmark-add':()=>{S.web.bookmarks.push({view:S.view,query:S.query,forumQuery:S.forum.query});save();close();},'web-bookmark-open':d=>{const e=S.web.bookmarks[Number(d.index)];S.query=e.query;S.forum.query=e.forumQuery;open('browser',e.view);},
 'browser-share':()=>S.view.startsWith('forum:post:')?ACTIONS['forum-share']({id:S.view.slice(11)}):sheet('分享网页',`<p>${browserAddress()}</p>${B('web-bookmark-add','添加书签','setting')}`),
 'browser-menu':()=>sheet('浏览器',B('history','搜索历史','setting')+B('browser-bookmarks','书签','setting')+B('browser-home','佰度首页','setting')),
 'baidu-clear':()=>{$('#search-input').value='';$('#search-input').focus();},'baidu-hot-refresh':()=>{S.web.hotPage=1-S.web.hotPage;save();render();},
 'baidu-channel':d=>{if(d.channel==='图片'){S.web.category='图片';S.query='';open('browser','search');}else{S.query='临川';S.web.category='资讯';open('browser','search');}},'baidu-result-tab':d=>{S.web.category=d.tab;save();render();},
 'tb-home':()=>forumLink('home'),'forum-go':d=>forumLink(d.view),'forum-result':()=>ACTIONS['forum-post']({id:'work'}),
 'tb-feed':d=>{S.forum.tab=d.tab;S.forum.sort=d.tab==='热榜'?'hot':'new';S.forum.limit=12;save();render();},
 'tb-bar':d=>{S.forum.limit=12;forumLink('bar:'+d.bar);},'tb-join':d=>{S.forum.bars=S.forum.bars.includes(d.bar)?S.forum.bars.filter(b=>b!==d.bar):[...S.forum.bars,d.bar];save();render();},
 'tb-sort':()=>{S.forum.sort=S.forum.sort==='new'?'hot':'new';save();render();},'tb-more':()=>{S.forum.limit+=12;save();repaintKeepScroll();},
 'tb-search-open':()=>{S.forum.query='';forumLink('search');},'tb-search-term':d=>{S.forum.query=d.q;forumLink('search');},
 'tb-follow':d=>{const name=d.author;if(name===tbUser())return;const list=tbFollowing(),next=list.includes(name)?list.filter(n=>n!==name):[...list,name];if(S.forum.user==='nightboat')S.forum.nightboatFollows=next;else S.forum.follows=next;S.forum.following=S.forum.follows.includes('夜航不靠岸');save();repaintKeepScroll();},
 'tb-only-owner':()=>{S.forum.onlyOwner=!S.forum.onlyOwner;save();repaintKeepScroll();},'tb-reverse':()=>{S.forum.reverse=!S.forum.reverse;save();repaintKeepScroll();},
 'tb-floor-reply':d=>sheet('回复 '+d.author,`<form id="tb-floor-form" data-id="${d.id}" data-floor="${d.floor}"><textarea id="tb-reply-text" aria-label="楼中楼回复" maxlength="300" placeholder="回复 ${esc(d.author)}…"></textarea><button class="primary" type="submit">回复</button></form>`),
 'tb-post-more':d=>sheet('帖子',B('forum-save',S.forum.saved.includes(d.id)?'取消收藏':'收藏','setting',{id:d.id})+B('forum-share','分享','setting',{id:d.id})+B('tb-bar','进入'+postBar(forumPost(d.id)),'setting',{bar:postBar(forumPost(d.id))})),
 'tb-account-menu':()=>sheet('账号设置',B('forum-go','切换账号','setting',{view:'login'})+B('forum-logout','退出登录','setting')),
 'tb-agreement':()=>sheet('用户协议','<p>请友善交流，尊重他人的隐私和作品。发布内容可在自己的主页查看。</p>'),
 'tb-privacy':()=>sheet('隐私政策','<p>仅保存本机的账号状态、发帖、回复、收藏及浏览记录。可通过手机设置重新开始，清除本次内容。</p>')
});
const viewPostBeforeReal=ACTIONS['forum-post'];ACTIONS['forum-post']=d=>{S.forum.onlyOwner=false;S.forum.reverse=false;viewPostBeforeReal(d);};
ACTIONS['forum-back']=ACTIONS['browser-back'];
ACTIONS['forum-share']=d=>sheet('分享帖子',`<p>${esc(forumPost(d.id).title)}</p><input aria-label="帖子链接" readonly value="tieba.baiduu.invalid/p/${d.id}">${B('forum-share-wechat',I('wechat')+' 威信','setting',{id:d.id})}`);
const sendForumBeforeReal=ACTIONS['forum-send-contact'];ACTIONS['forum-send-contact']=d=>{sendForumBeforeReal(d);const m=S.messages[d.to]?.filter(m=>m.self).at(-1);if(m)m.text=m.text.replace('[临川夜话]','[佰度贴吧]');save();render();};
document.addEventListener('submit',e=>{if(e.target.id==='tb-search'){e.preventDefault();S.forum.query=$('#forum-query').value.trim();if(S.forum.query)S.forum.searches.push(S.forum.query);S.forum.limit=12;forumLink('search');}if(e.target.id==='tb-floor-form'){e.preventDefault();const text=$('#tb-reply-text').value.trim();if(!text)return;const key=e.target.dataset.id+':'+e.target.dataset.floor;S.forum.replies[key]??=[];S.forum.replies[key].push({author:tbUser(),text});save();close();repaintKeepScroll();}if(e.target.id==='web-address-form'){e.preventDefault();const q=$('#web-address-input').value.trim();close();if(/tieba|贴吧/.test(q))forumLink('home');else if(/baidu\.com|baiduu\.invalid/.test(q))open('browser');else doSearch(q);}});
// Existing app search should also behave like a search, not a plot-aware catalog.
const storeBeforeReal=VIEWS.store;VIEWS.store=()=>{const introduced=S.hrIntroduced;let html;try{if(!S.view)S.hrIntroduced=false;html=storeBeforeReal();}finally{S.hrIntroduced=introduced;}return html;};
// Persist ordinary social interactions without resetting the reader's position.
for(const [action,key] of [['forum-like','likes'],['forum-save','saved']])ACTIONS[action]=d=>{S.forum[key]=S.forum[key].includes(d.id)?S.forum[key].filter(id=>id!==d.id):[...S.forum[key],d.id];save();close();repaintKeepScroll();};
const privateWithLayout=forumPrivate;
forumPrivate=view=>{let html=privateWithLayout(view);if(S.forum.user==='nightboat'&&view.startsWith('dm:')){const sent=S.forum.sent?.[view]||[];html=html.replace('</div><form id="forum-dm-form"',sent.map(m=>`<div class="forum-private-message self"><small>${esc(m.at)} · 已发送</small><p>${esc(m.text)}</p></div>`).join('')+'</div><form id="forum-dm-form"');}return html;};
document.addEventListener('submit',e=>{if(e.target.id!=='forum-dm-form')return;e.preventDefault();e.stopImmediatePropagation();const text=$('#forum-dm-text').value.trim();if(!text)return;S.forum.sent??={};const key=S.view.slice(6);S.forum.sent[key]??=[];S.forum.sent[key].push({at:time(),text});save();render();const sc=$('#screen .scroll');sc.scrollTop=sc.scrollHeight;},true);
// Each browser tab owns its own back/forward stack.
const tabDefaults=v2Defaults;v2Defaults=s=>{tabDefaults(s);s.web.tabs??=[{stack:s.web.stack,at:s.web.at}];s.web.activeTab??=0;s.forum.outbox??={};return s;};v2Defaults(S);
const chromeBeforeTabs=webBar;webBar=()=>chromeBeforeTabs().replace(/<span class="web-tab-count">\d+<\/span>/,'<span class="web-tab-count">'+S.web.tabs.length+'</span>').replace('浏览记录','标签页');
function keepTab(){webRememberScroll();S.web.tabs[S.web.activeTab]={stack:[...S.web.stack],at:S.web.at};}
function switchTab(index){keepTab();S.web.activeTab=index;const tab=S.web.tabs[index];S.web.stack=[...tab.stack];S.web.at=tab.at;if(tab.at>=0)webRestore(tab.at,false);else open('browser');}
ACTIONS['browser-tabs']=()=>{keepTab();sheet('标签页',S.web.tabs.map((t,i)=>{const e=t.stack[t.at];return '<div class="web-tab-row">'+B('web-tab-open',esc(e?.view.startsWith('forum:')?'佰度贴吧':e?.query||'佰度首页'),'setting',{index:i})+(S.web.tabs.length>1?B('web-tab-close','×','',{index:i,label:'关闭标签页'}):'')+'</div>';}).join('')+B('web-tab-new','＋ 新建标签页','setting'));};
ACTIONS['web-tab-open']=d=>switchTab(Number(d.index));
ACTIONS['web-tab-new']=()=>{keepTab();S.web.tabs.push({stack:[],at:-1});switchTab(S.web.tabs.length-1);};
ACTIONS['web-tab-close']=d=>{const i=Number(d.index);keepTab();S.web.tabs.splice(i,1);if(i<S.web.activeTab)S.web.activeTab--;else if(i===S.web.activeTab){S.web.activeTab=Math.min(i,S.web.tabs.length-1);const tab=S.web.tabs[S.web.activeTab];S.web.stack=[...tab.stack];S.web.at=tab.at;if(tab.at>=0)webRestore(tab.at,false);else open('browser');}save();ACTIONS['browser-tabs']();};
// Search can return communities and people as well as threads.
const searchViewBeforeTabs=tbSearchView;
tbSearchView=()=>{const kind=S.forum.searchKind||'帖子',tabs='<div class="tb-feed-tabs">'+['帖子','吧','用户'].map(t=>B('tb-search-kind',t,kind===t?'active':'',{kind:t})).join('')+'</div>';let html=searchViewBeforeTabs().replace('<div class="tb-feed-tabs"><b>帖子</b></div>',tabs);if(kind!=='帖子'){const q=S.forum.query.toLowerCase(),names=kind==='吧'?TB_BARS:[...new Set(forumPosts().map(p=>p.author))];const rows=names.filter(n=>!q||n.toLowerCase().includes(q)).map(n=>B(kind==='吧'?'tb-bar':'forum-profile',(kind==='吧'?'<span class="tb-bar-icon">'+n.slice(0,2)+'</span>':forumFace(n))+'<span><b>'+esc(n)+'</b></span>'+I('next'),'tb-bar-row',kind==='吧'?{bar:n}:{author:n})).join('');const start=html.indexOf('<div class="scroll tb-scroll">');html=html.slice(0,start)+'<div class="scroll tb-scroll">'+(rows||'<p class="empty">没有找到相关结果</p>')+'</div>';}return html;};
ACTIONS['tb-search-kind']=d=>{S.forum.searchKind=d.kind;save();render();};
// Sent private messages remain in the sender's inbox, like ordinary conversations.
const inboxWithLayout=forumInbox;forumInbox=()=>{let html=inboxWithLayout();const rows=Object.entries(S.forum.outbox).map(([name,messages])=>B('tb-chat',forumFace(name)+'<span><b>'+esc(name)+'</b><p>'+esc(messages.at(-1).text)+'</p></span><small>'+messages.at(-1).at+'</small>','forum-inbox-row',{author:name})).join('');return html.replace('<div class="scroll forum-scroll">','<div class="scroll forum-scroll">'+rows).replace(rows?'<p class="empty">暂时没有消息。</p>':'__never__','');};
const viewBeforeChat=forumView;forumView=()=>{if(!S.view.startsWith('forum:chat:'))return viewBeforeChat();const name=S.view.slice(11),list=S.forum.outbox[name]||[];return tbHeader(esc(name))+`<div class="scroll forum-scroll">${name==='夜航不靠岸'?'<p class="tb-end">对方已离线 · 消息暂未读</p>':''}${list.map(m=>'<div class="forum-private-message self"><small>'+m.at+' · 已发送</small><p>'+esc(m.text)+'</p></div>').join('')}</div><form id="tb-chat-form" class="tb-composer" data-author="${esc(name)}"><input id="tb-chat-text" aria-label="私信内容" maxlength="500" placeholder="发送私信…"><button type="submit">发送</button></form>`;};
ACTIONS['tb-chat']=d=>forumLink('chat:'+d.author);
ACTIONS['forum-message']=d=>sheet('发送私信',`<p>发送给 ${esc(d.author)}</p><form id="forum-guest-message" data-author="${esc(d.author)}"><textarea id="forum-guest-text" aria-label="私信内容" maxlength="500" placeholder="你好…"></textarea><button type="submit" class="primary">发送</button></form>`);
document.addEventListener('submit',e=>{if(!['forum-guest-message','tb-chat-form'].includes(e.target.id))return;e.preventDefault();e.stopImmediatePropagation();const name=e.target.dataset.author,text=$(e.target.id==='tb-chat-form'?'#tb-chat-text':'#forum-guest-text').value.trim();if(!text)return;S.forum.outbox[name]??=[];S.forum.outbox[name].push({at:time(),text});save();forumLink('chat:'+name);},true);
const APP_CATALOG=[['wechat','威信','社交 · 让生活更方便'],['biss','biss直聘','商务 · 找工作，与招聘者沟通'],['map','地图','导航 · 路线与出行'],['notes','备忘录','效率 · 随手记下想法']];
const storeDetailView=VIEWS.store;
VIEWS.store=()=>{if(S.view==='app:stay')return storeDetailView();const q=S.storeSearch||'',list=APP_CATALOG.filter(([,name])=>!q||name.toLowerCase().includes(q.toLowerCase()));return appHeader('App Store','home')+`<div class="scroll store-page"><div class="store-heading"><h2>搜索</h2></div><form id="store-search" class="searchbox">${I('search')}<input id="store-query" aria-label="搜索App" placeholder="游戏、App、故事等" autocomplete="off" value="${esc(q)}"><button type="submit">搜索</button></form><h3 class="store-section-title">${q?'搜索结果':'为你推荐'}</h3>${list.map(([id,name,desc])=>`<div class="store-app"><div class="appicon ${id}">${id==='biss'?'biss':I(id)}</div><div><h3>${name}</h3><p>${desc}</p></div>${B('open','打开','get-app',{app:id})}</div>`).join('')||'<div class="empty"><h3>无结果</h3><p>试试其他关键词。</p></div>'}</div>`;};
document.addEventListener('submit',e=>{if(e.target.id!=='store-search')return;e.preventDefault();e.stopImmediatePropagation();const q=$('#store-query').value.trim();S.storeSearch=q;save();open('store',/安住|验房|试睡/.test(q)?'app:stay':q?'results':'');},true);
const mapBeforeReal=VIEWS.map;
VIEWS.map=()=>{let html=mapBeforeReal().replace(B('chat','联系周先生，领取钥匙','primary',{id:'hr'}),B('map-done','完成','primary'));if(!mapHasDestination()){html=html.replace(/<path d="[^"]+" fill="none" stroke="#b4cee9"[^>]*\/>/,'').replace(/<path id="walk-progress"[^>]*\/>/,'').replace('<circle cx="250" cy="106" r="7" fill="#e77359" stroke="white" stroke-width="3"/>','').replace('槐安里 · 6栋','槐安里');html=html.slice(0,html.indexOf('<div class="mapcard">'))+'<div class="mapcard"><small class="eyebrow">当前位置</small><h2>江北路</h2><p>附近 · 街心花园　榆树巷</p></div>';}return html;};
ACTIONS['map-done']=()=>open('home');
// Keep the optional player assistance in Settings; never insert it into websites.
save();render();
