const rdNameBefore=personName;personName=id=>id==='hr'&&rdContactName()?rdContactName():rdNameBefore(id);
const rdWxViewBefore=VIEWS.wechat;VIEWS.wechat=()=>{if(S.redemption.contactPhase!=='research'&&['profile:hr','album:hr'].includes(S.view))return S.view==='album:hr'&&S.redemption.contactPhase==='shen'?feed('hr'):wxProfile('hr');return rdWxViewBefore();};
const rdBissBefore=VIEWS.biss;VIEWS.biss=()=>S.redemption.resolved&&['candidate','employer','employer-edit','employer-profile','haunted','chat:haunted'].includes(S.view)?appHeader('职位已关闭','home')+'<div class="pad"><h2>该职位已删除</h2><p>招聘账号已注销，不再接受沟通。</p></div>':rdBissBefore();
const rdEndingBefore=VIEWS.ending;
const RD_ENDINGS={escape:{coda:'（恭喜你，林夏。走出那扇门的，仍然是你。）',label:'逃脱者',subtitle:'你走出了这一夜',kind:'生还结局',line:'你拒绝让另一个人代替自己。房间仍在，但你把自己的名字带了出来。'},replacement:{coda:'（恭喜你，林夏。或者，该叫你另一个名字——周先生？）',label:'替罪者',subtitle:'你把这一夜留给了别人',kind:'轮回结局',line:'许晨的消息停了，你终于可以离开。周先生的账号依然在线，下一份招聘还在等待发送。'},redemption:{coda:'（恭喜你，林夏。这一次，天亮的不只是窗外。）',label:'救赎者',subtitle:'今夜之后，不再有人入住',kind:'隐藏结局 · 完全解咒',line:'你把二十年前的真相告诉了沈秋芸。照片一张张亮起来：那间让人害怕的房子，原来曾装满两个人相爱的日常。她终于知道，他一直想回家。'}};
VIEWS.ending=()=>{const r=S.redemption,m=RD_ENDINGS[S.ending];if(!m){if(r.failed)return `<div class="end-view rd-interrupted"><small>调查中断 · 尚未达成结局</small><h2>还没到天亮。</h2><div class="end-line">${esc(r.failure)}</div><p>已保留这次调查前的线索。</p>${B('rd-retry','回到最近调查节点','primary')}${B('restart','重新开始这一夜','secondary')}</div>`;return rdEndingBefore().replace('你回来了。','还没到天亮。').replace('<small>','<p class="rd-no-ending">尚未达成结局 · 可以重试</p><small>');}if(!S.endingAwards.includes(S.ending)){S.endingAwards.push(S.ending);save();}const extra=S.ending==='redemption'?`<div class="rd-after"><div class="rd-deleted-row"><img class="avatar" src="assets/shen-2006.png" alt="沈秋芸"><span><b>沈秋芸</b><small>那盏灯，不用再等了。谢谢你。</small></span></div><p>门外是普通的楼梯。小张就在楼下。<br>妈妈：不合适就回来，家里等你。</p>${S.twoPaths.warnedCandidate?'<p>许晨：'+(S.twoPaths.candidateInside?'门能打开了。我已经下楼了。谢谢你没把我留在里面。':'我没再过去，已经往家走了。谢谢你后来告诉我实话。')+'</p>':''}<p>相册里的阳光停在2006年的夏天。两双拖鞋，两只牙杯，两个人的家。604不再寻找新的留宿者。</p></div>`:`<div class="rd-after"><p>${S.ending==='escape'?'小张：我接到你了。别回头。<br>你：妈，我想回家。':'许晨：妈妈我不找工作了<br><br>对方已离线。'}</p>${S.twoPaths.warnedCandidate&&S.ending==='escape'?'<p>'+ (S.twoPaths.candidateInside?'许晨：我下来了。没接那个电话。谢谢。':'许晨：幸好你让我没去。谢谢。')+'</p>':''}</div>`;return `<div class="rd-ending ${S.ending}"><div class="rd-end-card"><small class="rd-end-eyebrow">达 成 结 局</small><h1>${m.label}</h1><span class="rd-end-kind">${m.kind}</span><div class="rd-end-rule"></div><h2>${m.subtitle}</h2><p>${m.line}</p><div class="rd-badge" aria-label="已获得${m.label}标签">${m.label}</div><small class="rd-end-coda">${esc(m.coda).replace('周先生？','<span class="rd-coda-name">周先生？</span>')}</small></div>${extra}<div class="rd-awards" aria-label="结局收集">${Object.entries(RD_ENDINGS).map(([id,e])=>`<span class="${S.endingAwards.includes(id)?'earned':''}">${S.endingAwards.includes(id)?e.label:'未解锁'}</span>`).join('')}</div><div class="rd-ending-actions">${B('ending-photos','查看这一夜的照片','secondary')}${S.ending==='redemption'?B('chat','再看沈秋芸的消息','secondary',{id:'hr'}):''}${B('rd-donate','赞赏作者','rd-donate')}${B('restart','重新开始这一夜','rd-restart')}</div><p class="rd-end-footer">谢谢你，陪林夏走完这一夜。</p></div>`;};
ACTIONS['rd-donate']=()=>{if(!RD_ENDINGS[S.ending])return;sheet('赞赏作者',`<div class="rd-donation"><p>如果这个故事让你难忘，可以请作者喝杯咖啡。</p><img src="assets/author-wechat-pay.jpg" alt="作者提供的收款码，扫码可自愿赞赏"><p>金额自定，完全自愿。谢谢你的支持。</p><a href="assets/author-wechat-pay.jpg" download="作者收款码.jpg">保存收款码原图</a>${B('close','返回结局','secondary')}</div>`);};
const rdResetBefore=ACTIONS['reset-now'];ACTIONS['reset-now']=()=>{const awards=[...S.endingAwards];rdResetBefore();S.endingAwards=awards;save();};

save();render();
