'use strict';
const beforeTwoDefaults=v2Defaults;v2Defaults=s=>{beforeTwoDefaults(s);s.twoPaths??={version:1,offered:false,choice:null,employer:false,stage:'draft',job:{title:'凶宅试睡员 · 夜间体验',pay:'1200',description:'独立完成房间拍摄，留宿至天亮。日结，无押金。'},messages:[],queue:[],unread:0,draft:'',committed:false,archiveOpen:false,finalCall:false};return s;};v2Defaults(S);

// Message channels are kept with each message so changing accounts never merges the conversations.
function ensureCandidateChannels(n){
 if(n.channelVersion===2)return;
 const later=['address','door','sleep','plea','complete'].includes(n.stage)||n.candidateInside||n.committed;
 let wx=false;for(const m of n.messages){if(m.self&&/槐安里.*604/.test(m.text||''))wx=true;m.channel??=wx?'wechat':'biss';}
 for(const q of n.queue)q.channel??=later?'wechat':'biss';
 n.wxAdded=!!later;n.wxStatus=later?'accepted':'none';n.wxUnread=0;n.channelVersion=2;
 if(later&&!n.messages.some(m=>m.channel==='wechat'))n.messages.push({system:true,text:'你已添加了许晨，现在可以开始聊天了。',at:time(),channel:'wechat'});
}
const candidateDefaultsBefore=v2Defaults;v2Defaults=s=>{candidateDefaultsBefore(s);ensureCandidateChannels(s.twoPaths);return s;};v2Defaults(S);
function candidateChannel(){return S.twoPaths.wxAdded?'wechat':'biss';}
function candidateMessages(channel){return S.twoPaths.messages.filter(m=>(m.channel||candidateChannel())===channel);}
function candidateCanReply(){const channel=candidateChannel();return !S.ending&&!S.twoPaths.jobClosed&&S.app===channel&&S.accounts?.[channel]==='recruiter'&&(channel!=='wechat'||S.twoPaths.wxAdded);}
function candidateInboxRow(kind){const n=S.twoPaths,list=candidateMessages(kind).filter(m=>!m.local),m=list.at(-1);if(kind==='wechat'&&!n.wxAdded)return '';if(!list.length)return '';const unread=kind==='wechat'?n.wxUnread:n.unread;return B('open',candidateAvatar()+'<div class="rowtext"><b>许晨'+(unread?'<em class="account-unread">'+unread+'</em>':'')+'</b><p>'+esc(m?.text||'你们已经是朋友了')+'</p></div>','chatrow',{app:kind,view:'candidate'});}

const TWO_POSTS=[
 {id:'power-notice',author:'老楼北窗',date:'2021-06-18 08:10',tag:'旧城',title:'槐安里6栋停电检修通知，今天不要用电梯',text:['检修日期：2021年6月18日。上午九点到下午四点。','北侧平台照明和门禁共用一条线路。修完后原来的报修截图我存在网盘，免得以后找不到。'],likes:17,comments:[]},
 {id:'ladder-new',author:'维修老何',date:'2026-09-12 17:40',tag:'旧城',title:'槐安里6栋消防梯已拆，别再照旧照片走',text:['我是这次外梯维修的现场联络人，补发今天的施工进度。北侧平台右端的旧铁梯已经拆除，下面没有台阶。2024年的照片不能再当路线图。','目前平台左端连接临时脚手架，可以下到东侧院子。向左扶住栏杆走，别跨右边的断口。','施工方留了围挡缺口，住户别拿东西堵住。'],likes:38,comments:[['山路','前两年的维修帖还在首页被顶，最好提醒一下。'],['维修老何','围挡上的施工示意图也已经更新，别再走右边的断口。']]},
 {id:'recruit-copy',author:'电台失眠',date:'2025-03-02 12:46',tag:'夜班',title:'你们有没有收到过一字不差的招聘话术',text:['去年有个摄影群里的朋友总说“明早六点联系我”。后来失联了。','这两天找兼职，碰到一个房产招聘的，连标点都跟他以前一样。也可能是共用的模板吧。','以前那人养猫，后来头像和昵称一起改了。'],likes:26,comments:[['鱼饼','招夜班的确实爱用复制粘贴。']]},
 {id:'night-replacement',author:'晚风',date:'2023-10-04 05:12',tag:'夜班',title:'“有人接班就能走”，这句话到底什么意思',text:['以前一起上夜班的人说，房间只要一个留宿的人。不是领了钥匙就算，要睡过去，再也叫不醒。','他一直说自己只是介绍一份工作。可每次电话响，他都会把屏幕扣过去。','后来他终于搬走了，名字却一直挂在那间房的招聘页上。'],likes:41,comments:[['阿岚','哪个小区？'],['晚风','他说不让我写。']]},
 {id:'same-number',author:'山路',date:'2026-08-30 21:09',tag:'旧城',title:'从槐安里出来的人，最后都提到一通电话',text:['采访旧楼维修事故时，碰到一个从平台下来的住户。她说一路不回头，已经看见下面的人，手机却开始响。','来电显示是她自己的号码。她没接，直接把手机塞进口袋，抓住栏杆。','她后来只说了一句：手机里可以有两个名字，电话那头不能再答应一次。'],likes:63,comments:[]},
 {id:'blank-name',author:'阿岚',date:'2025-11-07 09:21',tag:'生活',title:'搬走后还收到前租客的快递',text:['收件人最后一个字被雨泡掉了，开头像个“周”。快递里是猫用的项圈，铭牌写着 Momo。','打电话没人接。物业说那个人很久不住这里了，问我是不是又有人介绍那份夜班。'],likes:23,comments:[['奶油卷','交物业留着吧，说不定会回来找。']]}
];FORUM_POSTS.push(...TWO_POSTS);
const oldLast=FORUM_POSTS.find(p=>p.id==='last');oldLast.text=oldLast.text.filter(t=>t!=='我不写在这里了。剩下的话放进草稿。');oldLast.text.splice(3,0,'我不写在这里了。剩下的话放进草稿。那份网盘还没删。');
FORUM_DRAFTS.push({id:'handover',title:'未发送的招聘文案',time:'2024-11-07 03:19',text:['凶宅试睡员。1200元。日结，无押金。','照片拍完休息。明早六点联系我。','对外称呼沿用原来的。没必要解释谁在拿手机。','先把猫的照片换掉。','——下面这句不要发出去——','他说只要那个人睡过去，我就不用再等了。']});
FORUM_DRAFTS.push({id:'cloud',title:'老楼那份文件',time:'2024-11-07 03:14',text:['老楼北窗的网盘还在：槐安里_旧维修记录。提取码是那次停电的月日，四位。','他让我先去翻当年的检修通知，日期写得很清楚。','不要把旧帖子当成今晚的现场。路线会改，房间里的东西也会学。']});
const searchBeforeTwo=searchPosts;searchPosts=q=>{const original=searchBeforeTwo(q),terms=q.toLowerCase().match(/槐安里|604|消防梯|停电|检修|平台|招聘|接班|号码|网盘|momo/g)||[];if(!terms.length)return original;const extra=forumPosts().filter(p=>{const hay=[p.title,...p.text].join(' ').toLowerCase();return terms.every(t=>hay.includes(t));});return [...new Map([...original,...extra].map(p=>[p.id,p])).values()];};
const articleBeforeTwo=forumArticle;forumArticle=id=>{let html=articleBeforeTwo(id);if(id==='power-notice')html=html.replace('<div class="tb-floor-meta">',B('two-cloud','网盘附件：槐安里_旧维修记录','cloud-link')+'<div class="tb-floor-meta">');return html;};
const privateBeforeTwo=forumPrivate;forumPrivate=v=>{let html=privateBeforeTwo(v);if(v==='draft:cloud'&&pmAccount()===PM_OLD)html=html.replace('</article>',B('two-cloud','打开网盘分享','cloud-link')+'</article>');return html;};
function cloudView(){return `<div class="cloud-head">${B('browser-back',I('back'))}<b>网盘 · 分享</b></div><div class="scroll cloud-page${S.twoPaths.archiveOpen?' cloud-open':''}"><div class="cloud-folder">${I('files')}</div><h2>槐安里_旧维修记录</h2><p class="cloud-share-meta">老楼北窗 分享于 2024-11-07</p>${S.twoPaths.archiveOpen?`<article class="cloud-document"><small>604_通话整理.txt　6.4 KB</small><h3>那晚，我怎么下的平台</h3><p class="cloud-record-meta">老楼北窗口述 · 2023年8月19日清晨补记</p><p>那晚门锁能转，门却拉不开。只要消息一响，门外脚步就往我这边来。</p><p>我把消息提示音关了，也关了相机闪光。没敢再拍新的，翻出入住时拍的那张卧室旧照，发给周先生。</p><p>他问我在哪。我说：“我还在床上，没醒。”过了一会儿，他回：“我进去看看。”</p><p>浴室小窗那时才能推开。一声敲门，我扶着窗沿没动。等又敲三声、脚步回到卧室，我才翻到外面平台。</p><p>有人用我妈的声音叫我。我没回头。手机随后显示本机号码来电，我也没接。接到我的人明明在楼下。</p><p>我走过的只是2023年的路。铁梯、脚手架会拆，后来的人得先看最新维修记录，不能只照旧帖走。</p><hr><small>同目录：job_20241107_0319.txt</small><p>1200元，日结，无押金。照片拍完休息，明早六点联系我。</p><p>导出账户：n***boat　　对外联系称呼：沿用原设置</p><p>最后修改：2024-11-07 03:19<br>公开动态最后一条：03:17</p></article>`:`<form id="two-cloud-form"><label>请输入提取码<input id="two-cloud-code" aria-label="网盘提取码" maxlength="4" autocomplete="off" inputmode="numeric" placeholder="4位提取码"></label><p class="error">${esc(S.twoPaths.cloudError||'')}</p><button type="submit" class="primary">提取文件</button></form>`}</div>`;}
const browserBeforeTwo=VIEWS.browser;VIEWS.browser=()=>S.view==='cloud:604'?cloudView()+webBar():browserBeforeTwo();
const addressBeforeTwo=browserAddress;browserAddress=()=>S.view==='cloud:604'?'pan.baiduu.invalid':addressBeforeTwo();
ACTIONS['two-cloud']=()=>open('browser','cloud:604');
document.addEventListener('submit',e=>{if(e.target.id!=='two-cloud-form')return;e.preventDefault();S.twoPaths.archiveOpen=$('#two-cloud-code').value==='0618';S.twoPaths.cloudError=S.twoPaths.archiveOpen?'':'提取码不正确，请重新输入';save();render();});
const pmRepliesBeforeTwo=pmReplyLines;pmReplyLines=(owner,peer,text)=>{if(peer==='老楼北窗'&&/路|平台|铁梯|窗|逃/.test(text))return ['我当年走的是右边。后来那里一直在施工，我没再进去过。','今晚的路我不敢替你认。找现场维修人员最近发的记录，别只照着我的旧聊天走。'];if(peer==='老楼北窗'&&/替|接班|招聘|周|名字/.test(text))return ['我看过几个人用同一段话招人。后来连名字也不换了。','旧记录里有份招聘草稿。写它的人，前一分钟还在求救。'];return pmRepliesBeforeTwo(owner,peer,text);};
function twoChoices(html,buttons){const markup='<div class="chat-choices">'+buttons+'</div>';return html.includes('<div class="chat-choices">')?html.replace(/<div class="chat-choices">[\s\S]*?<\/div>/,markup):html.replace('<form class="composer"',markup+'<form class="composer"');}
const wxBeforeTwo=wxChat;wxChat=id=>{let html=wxBeforeTwo(id);if(!isHaunted()||S.ending||threadPending('wx',id))return html;const n=S.twoPaths;if(id==='hr'){let extra='';if(!n.offered)extra=B('two-offer','还有别的办法离开吗？');else if(!n.employer&&n.choice!=='escape')extra=B('two-accept','我去找他留下的账号。')+B('two-refuse','我不会找人来替我。');else if(n.employer&&!n.committed&&n.stage!=='withdrawn')extra=B('open','打开biss直聘','',{app:'biss'})+B('two-withdraw','我不做了，撤回招聘。');else if(n.choice==='escape'&&!n.employer)extra=B('two-accept','我想再查查那个旧账号。');if(extra){const existing=html.match(/<div class="chat-choices">([\s\S]*?)<\/div>/)?.[1]||'';html=twoChoices(html,existing+extra);}}
 if(id==='friend'&&n.committed)html=html.replace(/<div class="chat-choices">[\s\S]*?<\/div>/,'');if(id==='friend'&&S.night.escapeStep===3&&!n.committed)html=twoChoices(html,B('night-move','我沿右边的旧铁梯下去。','',{move:'right'})+B('two-left','我试着沿平台向左走。')+B('night-move','回头看看是谁在叫我。','',{move:'look'}));return html;};
ACTIONS['two-offer']=()=>{if(!isHaunted()||S.twoPaths.offered)return;S.twoPaths.offered=true;appendWx('hr','还有别的办法离开吗？',true);wxQueue('hr',['房间只留一个人。等下一位睡下，你就能走。','不是进门就算。要等他睡过去，再也叫不醒。','招人的那个号还在。上一个人也用过，他后来不肯继续。']);save();render();};
ACTIONS['two-accept']=()=>{if(!isHaunted()||!S.twoPaths.offered||S.twoPaths.committed)return;const n=S.twoPaths;n.choice='replacement';n.employer=true;if(n.stage==='withdrawn')n.stage='draft';appendWx('hr','我去找他留下的账号。',true);wxQueue('hr',['biss里已经切到招聘身份，岗位草稿在里面。','对外称呼沿用。说话客气些，你刚来时不也是信这个。']);save();render();};
ACTIONS['two-refuse']=()=>{S.twoPaths.choice='escape';appendWx('hr','我不会找人来替我。',true);wxQueue('hr',['那你自己找。','别照抄上一个人的路。那个人最后也没走完。']);save();render();};
function withdrawRecruitment(){const n=S.twoPaths;if(n.committed||S.ending)return;n.warnedCandidate=n.messages.length>0;n.candidateInside=n.candidateInside||['sleep','plea'].includes(n.stage);n.queue=[];n.stage='withdrawn';n.choice='escape';n.jobClosed=true;if(n.messages.length)n.messages.push({self:true,channel:candidateChannel(),text:'不要来。房子有危险。如果已经进去了，别睡，关掉提示音和闪光灯。保持清醒等我消息，我在找出路。',at:time()});appendWx('friend','他让我找人接班。我差点答应了。现在我把招聘撤了。',true);wxQueue('friend',['撤了就好。你把自己带出来。','我在查这栋楼最近有没有施工，旧帖子不一定还准。']);S.accounts.wechat='player';save();open('wechat','friend');}
ACTIONS['two-withdraw']=withdrawRecruitment;
function candidateAvatar(){return '<img class="avatar" src="assets/candidate-xuchen.png" alt="许晨头像">';}
function employerNav(){return `<nav class="tabs employer-tabs">${B('open',I('files')+'<span>职位</span>','',{app:'biss',view:'employer'})}${B('open',I('wechat')+'<span>消息'+(S.twoPaths.unread?' · '+S.twoPaths.unread:'')+'</span>','',{app:'biss',view:'candidate'})}${B('open',I('user')+'<span>我的</span>','',{app:'biss',view:'employer-profile'})}</nav>`;}
function employerHome(){const n=S.twoPaths;return appHeader('招聘','home')+`<div class="scroll employer-page"><div class="employer-company"><small>安住不动产</small><h2>我的职位</h2></div><article class="employer-job"><small>${n.stage==='draft'?'草稿':n.stage==='withdrawn'?'已关闭':'招聘中'}</small><h2>${esc(n.job.title)}</h2><strong>${esc(n.job.pay)}元 / 晚</strong><p>临川 · 槐安里　经验不限　学历不限</p>${n.stage==='draft'?B('open','编辑并发布','primary',{app:'biss',view:'employer-edit'}):n.stage!=='withdrawn'?B('open','查看沟通','primary',{app:'biss',view:'candidate'}):''}</article>${n.messages.length?B('open',candidateAvatar()+'<span><b>许晨</b><small>应届生 · 可立即到岗</small></span>'+I('next'),'candidate-row',{app:'biss',view:'candidate'}):''}${n.stage!=='draft'&&n.stage!=='withdrawn'&&!n.committed?B('two-withdraw','关闭职位','secondary'):''}</div>`+employerNav();}
function employerEditor(){const j=S.twoPaths.job;return appHeader('发布职位','two-employer')+`<div class="scroll employer-page"><form id="employer-publish"><label class="formfield">职位名称<input id="employer-title" maxlength="40" value="${esc(j.title)}" required></label><label class="formfield">薪资 · 元/晚<input id="employer-pay" type="number" min="100" max="10000" value="${esc(j.pay)}" required></label><label class="formfield">职位描述<textarea id="employer-desc" maxlength="800" required>${esc(j.description)}</textarea></label><p class="muted">联系人：周先生 · 安住不动产<br>工作地点：槐安里6栋604</p><button class="primary" type="submit">发布职位</button></form></div>`;}
function queueCandidate(lines){for(const line of lines){const q=typeof line==='string'?{text:line}:line;S.twoPaths.queue.push({remaining:q.delay||1800,channel:candidateChannel(),...q});}save();}
const CANDIDATE_PHOTO_NOTES={hall:'玄关拍好了。钥匙先放鞋柜上了。',living:'客厅这张。沙发上还铺着旧花布。',kitchen:'厨房也拍好了，水龙头没有漏水。',dining:'餐桌擦得很干净。桌角那块磕痕也拍进去了。',balcony:'阳台拍好了。外面太黑，我没往下看。',bath:'浴室这张，热水能用。',bed:'卧室拍好了，床单已经铺好了。',door:'最后是入户门。我从里面反锁了。'};
const CANDIDATE_STEPS={
 greeting:['你好，把简历发我看看。',[{text:'许晨_个人简历.pdf',kind:'resume'}, {text:'23岁，应届毕业生。做过校园摄影，手机拍照没问题。',stage:'resume'}]],
 resume:['经历符合。现在能过来吗？这一班到早上六点结束。',['可以，我就在临川，还没睡。',{text:'投了好几家都没要我，房租后天就到期了。',stage:'pay'}]],
 pay:['1200元日结，不收押金。',['真的日结吗？太好了。',{text:'写着凶宅……真的安全吗？我妈知道了肯定不让我去。',stage:'risk'}]],
 risk:['只是以前出过事，照片拍完就能休息。现在安排你过来，可以吗？',['那我跟家里说是临时夜班。我接这一班。',{text:'我的威信号是 xuchen_0921，后续安排加威信说吧。',stage:'add-wechat'}]],
 install:['先去App Store下载安住验房。账号 az604_1107，密码0319，登录后按预约拍照。',['好的，我去下载。',{text:'已经下载并登录了。周先生，麻烦发一下地址。',stage:'address'}]],
 address:['槐安里6栋604。先导航过来，到楼下后联系我。',['收到，导航说三十分钟。',{text:'周先生，我到楼下了。钥匙在哪里领？',delay:7000,stage:'keys',timeJump:30}]],
 keys:['去值班处报604，领钥匙后上六楼。',[{text:'拿到钥匙了。',timeJump:2},{text:'六楼窗帘后面好像有人，是同事吗？',stage:'door',timeJump:3}]],
 door:['里面没人，直接进去就行。',[{text:'进来了。灯和热水都能用。',timeJump:1},'门牌是604，没走错。屋里就我一个人。',{text:'你盯着房门。门锁始终没有响。',system:true,local:true},...ROOMS.map(r=>({text:CANDIDATE_PHOTO_NOTES[r.id],kind:'photo',image:r.live,timeJump:1})),{text:'我刚跟我妈说一切正常。可以睡了吗？',stage:'sleep',timeJump:2}]],
 sleep:['照片都正常。早点睡，明早六点联系我。',['已经凌晨了，是早上六点吧？好，我定好闹钟。','谢谢周先生。等结算了，我给我妈买点东西。',{text:'周先生？我刚醒，门打不开了。我的照片里怎么有个人？',delay:6500,stage:'plea',timeJump:45}]],
 plea:['别把脚伸出床外。闭上眼继续睡。',['床下是不是有人？您还在吗？','外面是我妈的声音。可是我妈在老家啊。','为什么床上躺着的人长得跟我一样。',{text:'妈妈我不找工作了',delay:2600},{text:'对方已离线',system:true,event:'replacement-ended',delay:3000}]]
};
function refreshCandidateDialogue(state){const n=state.twoPaths;if(!n)return state;const replacements=new Map([['经历符合，今晚能到岗吗？',CANDIDATE_STEPS.resume[0]],['可以，我就在临川。',CANDIDATE_STEPS.resume[1][0]],['只是以前出过事，照片拍完就能休息。今晚安排你试岗，可以吗？',CANDIDATE_STEPS.risk[0]],['那我跟家里说是普通夜班。我接受今晚的试岗。',CANDIDATE_STEPS.risk[1][0]],...ROOMS.map(r=>[r.name+'拍好了，看着挺正常。',CANDIDATE_PHOTO_NOTES[r.id]])]);for(const m of [...n.messages,...n.queue])if(replacements.has(m.text))m.text=replacements.get(m.text);return state;}
const candidateDialogueDefaultsBefore=v2Defaults;v2Defaults=s=>refreshCandidateDialogue(candidateDialogueDefaultsBefore(s));refreshCandidateDialogue(S);
function candidateStep(){const step=CANDIDATE_STEPS[S.twoPaths.stage];return step?[step[0].replace('1200',S.twoPaths.job.pay),step[1]]:null;}
function candidateView(){const n=S.twoPaths,channel=S.app,wx=channel==='wechat';if(wx&&!n.wxAdded)return candidateFriendView();if(wx)n.wxUnread=0;else n.unread=0;const active=channel===candidateChannel(),step=active?candidateStep():null,pending=n.queue.some(q=>q.channel===channel),handoff=!wx&&(n.wxAdded||n.stage==='add-wechat');return appHeader(pending?'对方正在输入…':'许晨',wx?'account-inbox':'two-employer',B('two-candidate-profile',I('user')))+(wx?'':`<div class="job-chat-strip"><b>${esc(n.job.title)}</b><strong>${esc(n.job.pay)}元 / 晚</strong></div>`)+`<div class="scroll chatbody ${wx?'candidate-wx':'biss-chatbody'}" id="candidate-chat">${candidateMessages(channel).map(m=>m.system?'<div class="chat-time'+(m.local?' candidate-local':'')+'">'+esc(m.text)+'</div>':`<div class="msg ${m.self?'self':''}">${m.self?'<img class="avatar" src="assets/hr-zhou.png" alt="当前账号头像">':candidateAvatar()}<div class="bubble">${m.kind==='resume'?'<strong>附件简历 · PDF</strong><br>'+esc(m.text):m.kind==='photo'?'<img src="assets/'+(m.image==='bed.png'?room('bed').live:m.image)+'" alt="许晨拍摄的房间">'+esc(m.text):esc(m.text)}<small class="candidate-at">${m.at}</small></div></div>`).join('')}</div>`+(handoff?'<div class="candidate-handoff">'+B('two-add-wechat',n.wxAdded?'在威信中联系':'添加许晨的威信','primary')+'</div>':`${step&&!pending&&!n.committed?'<div class="chat-choices">'+B('two-candidate-next',step[0])+(n.stage==='risk'||n.stage==='plea'?B('two-withdraw',n.stage==='plea'?'别睡！有危险，马上离开那里。':'房子有危险，不要来。'):'')+'</div>':''}<form id="candidate-form" class="composer"><input id="candidate-input" aria-label="给许晨发消息" maxlength="300" value="${esc(n.draft)}" ${n.committed||n.jobClosed||S.ending?'disabled':''}><button type="submit" class="send" ${n.committed||n.jobClosed||S.ending?'disabled':''}>发送</button></form>`);}
const bissBeforeTwo=VIEWS.biss;VIEWS.biss=()=>{const n=S.twoPaths;if(!n.employer||!isHaunted())return bissBeforeTwo();if(S.view==='employer-edit'&&n.stage==='draft')return employerEditor();if(S.view==='candidate')return candidateView();if(S.view==='employer-profile')return appHeader('我的','two-employer')+`<div class="scroll employer-page"><div class="contactcard"><img class="avatar" src="assets/hr-zhou.png" alt="招聘账号头像"><h2>周先生</h2><p>安住不动产 · 房源体验</p></div><div class="card"><p>显示称呼：沿用原设置<br>已关联设备：此手机<br>首次招聘记录：2024-11-07 03:19</p></div>${B('two-withdraw','停止招聘','secondary')}</div>`+employerNav();return employerHome();};
ACTIONS['two-employer']=()=>open('biss','employer');
ACTIONS['two-candidate-profile']=()=>sheet('许晨',`<div class="contactcard">${candidateAvatar()}<h2>许晨</h2><p>23岁 · 本科 · 应届生<br>求职方向：摄影助理 / 运营<br>到岗时间：随时</p></div><p>校园摄影社活动跟拍，兼职整理照片。希望找一份稳定的工作。</p>`);
function candidateNext(playerText){const n=S.twoPaths,step=candidateStep();if(!candidateCanReply()||!step||n.queue.length||n.committed||S.ending)return;n.messages.push({self:true,text:typeof playerText==='string'?playerText:step[0],at:time(),channel:candidateChannel()});if(n.stage==='door')n.candidateInside=true;if(n.stage==='plea')n.committed=true;queueCandidate(step[1]);n.draft='';save();render();}
ACTIONS['two-candidate-next']=candidateNext;
document.addEventListener('input',e=>{if(e.target.id==='candidate-input'){S.twoPaths.draft=e.target.value;save();}if(['employer-title','employer-pay','employer-desc'].includes(e.target.id)){S.twoPaths.job[{ 'employer-title':'title','employer-pay':'pay','employer-desc':'description'}[e.target.id]]=e.target.value;save();}});
document.addEventListener('submit',e=>{if(e.target.id==='employer-publish'){e.preventDefault();const n=S.twoPaths;if(!n.employer||n.stage!=='draft')return;n.job={title:$('#employer-title').value.trim(),pay:$('#employer-pay').value,description:$('#employer-desc').value.trim()};if(!n.job.title||!n.job.description)return;n.stage='published';n.jobClosed=false;queueCandidate(['您好，我对这个职位感兴趣。',{text:'请问还招人吗？我刚毕业。',stage:'greeting'}]);open('biss','employer');}if(e.target.id==='candidate-form'){e.preventDefault();const n=S.twoPaths,text=$('#candidate-input').value.trim();if(!text||n.committed||!candidateCanReply()||n.stage==='add-wechat')return;if(/危险|不要来|别来|别睡|离开|快走|取消/.test(text))return withdrawRecruitment();const intent={greeting:/简历/,resume:/到岗|今晚|能来/,pay:/日结|元|押金|工资/,risk:/安全|没事|只是|以前|放心|正常|休息/,install:/安住|下载|0319/,address:/槐安里.*604/,keys:/值班|钥匙/,door:/进去|没人|开门/,sleep:/睡|晚安|休息/,plea:/闭.*眼|继续睡|别把脚/}[n.stage];if(text===candidateStep()?.[0]||intent?.test(text))return candidateNext(text);n.messages.push({self:true,text,at:time(),channel:candidateChannel()});n.draft='';if(!n.queue.length)queueCandidate(['我想先确认一下刚才问的事情，可以吗？']);save();render();}});
function finishReplacement(){if(S.ending)return;S.twoPaths.stage='complete';S.twoPaths.queue=[];S.night.phase='escaped';S.ending='replacement';S.queue=[];save();open('ending');}
const advanceBeforeTwo=advance;advance=ms=>{advanceBeforeTwo(ms);if(document.hidden||!Number.isFinite(ms)||ms<=0||S.ending)return;const n=S.twoPaths,q=n.queue[0];if(!q)return;q.remaining-=ms;if(q.remaining>0)return;n.queue.shift();if(q.timeJump)S.time+=q.timeJump;if(q.event==='candidate-friend-accepted'){n.wxAdded=true;n.wxStatus='accepted';}const channel=q.channel||candidateChannel();n.messages.push({text:q.text,at:time(),kind:q.kind,image:q.image,system:q.system,local:q.local,channel});if(q.stage)n.stage=q.stage;const visible=S.app===channel&&S.accounts?.[channel]==='recruiter'&&S.view==='candidate';if(!visible&&!q.local){if(channel==='wechat')n.wxUnread++;else n.unread++;notify((channel==='wechat'?'威信':'biss直聘')+' · 许晨',q.text,channel,'candidate');}save();if(q.event==='replacement-ended')return finishReplacement();if(S.app===channel&&S.accounts?.[channel]==='recruiter'){const input=$('#candidate-input'),typing=input&&document.activeElement===input,selection=typing?[input.selectionStart,input.selectionEnd]:null,sc=$('#candidate-chat'),atBottom=sc&&sc.scrollHeight-sc.scrollTop-sc.clientHeight<80,y=sc?.scrollTop||0;render();const nextScroll=$('#candidate-chat');if(nextScroll)nextScroll.scrollTop=atBottom?nextScroll.scrollHeight:y;if(typing){const next=$('#candidate-input');if(next){next.focus({preventScroll:true});next.setSelectionRange(...selection);}}}};
const routeBeforeTwo=nightRoute;nightRoute=route=>{if(S.twoPaths.committed)return;routeBeforeTwo(route);for(const q of S.queue)if(q.id==='friend'&&q.text==='我到楼下了。你沿平台往右，消防梯在右边。')q.text='我到楼下了。平台那边太黑，你先扶稳栏杆。';};ACTIONS['night-route']=d=>nightRoute(d.route);
const moveBeforeTwo=nightMove;nightMove=move=>{if(S.twoPaths.committed)return;if(S.night.escapeStep===3&&move==='right')return nightLose('你踩向记忆中的铁梯。脚下没有台阶。旧帖子没有错，只是那架梯子已经拆掉了。');moveBeforeTwo(move);for(const q of S.queue)if(q.id==='friend'&&q.text==='看脚下，沿右边过来。')q.text='看脚下。我在院子等你，别回头。';};ACTIONS['night-move']=d=>nightMove(d.move);
ACTIONS['two-left']=()=>{if(S.night.escapeStep!==3||S.ending||S.twoPaths.committed||threadPending('wx','friend'))return;S.night.escapeStep=4;S.twoPaths.choice='escape';appendWx('friend','右边的铁梯拆了。我走左侧脚手架。',true);wxQueue('friend',['我在左边院子。看见你了，抓好栏杆。',{text:'手机突然响了，屏幕上是我自己的号码。',self:true,event:'two-final-call',delay:2200}]);save();render();};
const deliveryBeforeTwo=deliveryEvent;deliveryEvent=q=>{deliveryBeforeTwo(q);if(q.event==='two-final-call'){S.twoPaths.finalCall=true;save();open('phone','incoming-self');}};
const phoneBeforeTwo=VIEWS.phone;VIEWS.phone=()=>S.twoPaths.finalCall?`<div class="two-incoming"><small>手机来电</small><img src="assets/player-avatar.png" alt="来电头像"><h2>林砚</h2><p>本机号码</p><div class="two-call-actions">${B('two-decline-call',I('phone')+'<span>拒绝</span>','call-decline')}${B('two-answer-call',I('phone')+'<span>接听</span>','call-answer')}</div></div>`:phoneBeforeTwo();
ACTIONS['two-answer-call']=()=>{if(!S.twoPaths.finalCall||S.twoPaths.committed)return;S.twoPaths.finalCall=false;nightLose('听筒里有人用你的声音说：我还在屋里。你答了一声，脚下的铁架便变成了床沿。');};
ACTIONS['two-decline-call']=()=>{if(!S.twoPaths.finalCall||S.twoPaths.committed)return;S.twoPaths.finalCall=false;S.twoPaths.choice='escape';if(S.twoPaths.employer&&!S.twoPaths.committed){S.twoPaths.stage='withdrawn';S.twoPaths.queue=[];S.twoPaths.jobClosed=true;S.twoPaths.warnedCandidate=S.twoPaths.messages.length>0;if(S.twoPaths.warnedCandidate&&!S.twoPaths.candidateInside)S.twoPaths.messages.push({self:true,channel:candidateChannel(),text:'职位已取消。房子有危险，请不要过来。',at:time()});if(S.twoPaths.candidateInside){S.twoPaths.messages.push({self:true,channel:candidateChannel(),text:'用入住时的卧室旧照骗它回床边。关提示音和闪光，等三声敲门后从浴室小窗出去，平台走左侧脚手架。不要接自己号码的电话。',at:time()});}}appendWx('friend','我没接。手机收起来了，正在下楼。',true);wxQueue('friend',['抓住我。别回头。',{text:'我接到你了。我们走。',event:'night-escaped'}]);save();open('wechat','friend');};
const endingBeforeTwo=VIEWS.ending;VIEWS.ending=()=>{if(S.ending==='replacement')return `<div class="end-view bad"><small>${time()} / 已结束体验</small><h2>下一位，晚安。</h2><div class="end-line">门锁响了一声。你终于走出604。<br><br>许晨的求救停在“妈妈我不找工作了”。系统没有再显示已读。窗帘后的人影换了站姿。<br><br>你的手机恢复了信号，biss里的称呼仍是“周先生”。</div><div class="receipt">岗位状态：招聘中<br>候选人：许晨 · 已离线<br><br>一份草稿自动保存：<br>“照片拍完休息。明早六点联系我。”<br><br>论坛账号 nightboat：最后在线 2024-11-07 03:17<br>招聘记录：2024-11-07 03:19</div>${B('restart','重新开始这一夜','secondary')}</div>`;if(S.ending==='escape')return `<div class="end-view"><small>${time()} / OUTSIDE</small><h2>这一夜，到你为止。</h2><div class="end-line">小张把你从左侧脚手架上拉下来。你没有接那通来自自己号码的电话。<br><br>六楼窗帘动了一下。那里还在等人，但你没有替它找到下一位。</div><div class="receipt">妈妈：到小张那里了吗？<br>你：到了。我想回家。<br><br>${S.twoPaths.warnedCandidate?(S.twoPaths.candidateInside?'你把刚走过的路线发给许晨。过了很久，他回复：<br>我下来了。没接那个电话。谢谢。<br><br>':'许晨：幸好你让我没去。谢谢。<br><br>'):''}贴吧里那张蓝色纸船的头像，和招聘页一起变成了灰色。<br>最后一条未发送的文案里，仍然有“明早六点”。</div>${B('ending-photos','查看照片','primary')}${B('restart','重新开始这一夜','secondary')}</div>`;return endingBeforeTwo();};
const replyBeforeTwo=wxReply;wxReply=reply=(id,text)=>{if(isHaunted()&&id==='hr'&&!threadPending('wx','hr')){if(/别的办法|接班|替班/.test(text)&&!S.twoPaths.offered)return ACTIONS['two-offer']();if(S.twoPaths.offered&&!S.twoPaths.employer&&/不给|不会找|不想害|不找人/.test(text))return ACTIONS['two-refuse']();if(S.twoPaths.offered&&!S.twoPaths.employer&&/招聘账号|我来招|给我账号|找.*账号|接手.*账号/.test(text))return ACTIONS['two-accept']();}return replyBeforeTwo(id,text);};
const renderBeforeTwo=render;render=()=>{const old=$('#candidate-chat'),position=old?.scrollTop||0,bottom=!old||old.scrollHeight-position-old.clientHeight<80;renderBeforeTwo();const next=$('#candidate-chat');if(next){next.scrollTop=bottom?next.scrollHeight:position;if(bottom){let touched=false;for(const event of ['wheel','touchstart','pointerdown'])next.addEventListener(event,()=>{touched=true;},{once:true,passive:true});Promise.all([...next.querySelectorAll('img')].map(img=>img.decode().catch(()=>{}))).then(()=>{if(next.isConnected&&!touched)next.scrollTop=next.scrollHeight;});}}};
const textBeforeTwo=window.render_game_to_text;window.render_game_to_text=()=>JSON.stringify({...JSON.parse(textBeforeTwo()),twoPaths:{choice:S.twoPaths.choice,employer:S.twoPaths.employer,stage:S.twoPaths.stage,channel:candidateChannel(),friendStatus:S.twoPaths.wxStatus,committed:S.twoPaths.committed,pending:S.twoPaths.queue.length,archiveOpen:S.twoPaths.archiveOpen,finalCall:S.twoPaths.finalCall}});
save();render();


