'use strict';
const defaultsBeforeBoot=v2Defaults;v2Defaults=s=>{defaultsBeforeBoot(s);s.lens??='rear';s.zoom??=1;s.savedImages??=[];s.social.savedImages??=[];s.prefs.grid??=false;return s;};v2Defaults(S);
const renderBeforeBoot=render;render=()=>{v2Defaults(S);socialEnsure();renderBeforeBoot();if(S.app==='map')paintRoute();if(S.app==='biss'&&S.view.startsWith('chat:')){const sc=$('#chatbody');if(sc)sc.scrollTop=sc.scrollHeight;}};
const notifyBeforeBoot=notify;notify=(title,text,app='wechat',view='')=>{if(app==='wechat'&&S.social.muted[view])return;notifyBeforeBoot(title,text,app,view);};
const deliveryBeforeBoot=deliveryEvent;deliveryEvent=q=>{deliveryBeforeBoot(q);if(q.event==='task'&&S.app==='stay')render();};
const calendarBeforeBoot=VIEWS.calendar;VIEWS.calendar=()=>{S.calendarDay=Math.min(S.calendarDay,new Date(S.calendarYear,S.calendarMonth,0).getDate());return calendarBeforeBoot();};
const feedBeforeBoot=feed;feed=owner=>{const html=feedBeforeBoot(owner);return !owner||owner==='self'?html.replace(/<img src="([^"]+)" alt="朋友圈封面">/,(_,src)=>B('cover-options',`<img src="${src}" alt="朋友圈封面">`,'cover-change',{label:'更换朋友圈封面'})):html;};
Object.assign(ACTIONS,{'cover-options':()=>sheet('更换朋友圈封面',`<div class="post-pick">${['wx-cover-self-v6.png','wx-mountain.png','life-coffee.png','wx-cover-lin-v6.png'].map(asset=>B('cover-select',`<img src="assets/${asset}" alt="可选封面">`,'',{asset})).join('')}</div>`),'cover-select':d=>{S.social.covers.self=d.asset;save();close();render();}});
document.addEventListener('input',e=>{if(e.target.id==='post-text'){S.social.draft=e.target.value;save();}});
ACTIONS['social-save-image']=d=>{if(!S.savedImages.includes(d.asset))S.savedImages.push(d.asset);save();close();notify('照片','图片已保存到本机相册。','photos');};
window.render_game_to_text=()=>JSON.stringify({...JSON.parse(V1.renderText()),edition:2,recruitment:S.recruit,pendingMessages:S.queue.map(q=>({channel:q.channel,id:q.id,remaining:Math.round(q.remaining),event:q.event})),friendRequested:S.friendRequested,contactAccepted:S.contactAccepted,installed:S.installed,taskReady:S.taskReady,taskSeen:S.taskSeen,currentRoom:S.currentRoom,puzzles:S.puzzle,breakers:S.breakers,map:{destination:mapHasDestination()?'槐安里6栋604':null},route:S.nav?{...S.nav,position:routePoint(S.nav.elapsed/30000)}:null,camera:{mode:S.cameraMode,lens:S.lens,zoom:S.zoom},social:{posts:S.social.posts.length,likes:S.social.likes,comments:S.social.comments},onSiteLog:S.onSiteLog});
const endingBeforeBoot=VIEWS.ending;VIEWS.ending=()=>endingBeforeBoot().replace('发送成功的提示音响起。门后的敲击停了。<br><br>你把钥匙放回鞋柜。红色拖鞋安静地并在一旁，鞋尖不再朝着你。<br><br>楼道里，感应灯一盏接着一盏亮起。','机械插销落下，你侧身挤进衣柜后的维修通道。<br><br>消防楼梯里，每下一层，身后就多响起一步。你始终没有回头。<br><br>你在值班室守到天亮。06:03，小张是好bro终于赶到。她手机里保存着全部原片。').replace('回到报告提交前','恢复最近检查点');
VIEWS.phone=()=>appHeader('电话','home')+`<div class="scroll"><div class="pad"><h2>通讯录</h2></div>${Object.keys(PEOPLE).filter(id=>canSeePeer(id)&&PEOPLE[id].number).map(id=>B('call',`${AV(id)}<div class="rowtext"><b>${esc(personName(id))}</b><p>${PEOPLE[id].number}</p></div>`,'chatrow',{id})).join('')}${B('call','报警求助 · 110','setting',{id:'police'})}<div class="pad"><h3>最近通话</h3>${S.calls.slice(-6).reverse().map(c=>`<p class="muted">${c.at}　${esc(c.name)} · ${esc(c.status)}</p>`).join('')}</div></div>`;
const iconBeforeBoot=appIcon;appIcon=(id,dock=false)=>id==='calendar'?B('open',`<span class="appicon native-calendar"><small>${S.time>=1440?'周一':'周日'}</small><strong>${S.time>=1440?'14':'13'}</strong></span><span>日历</span>`,'app',{app:'calendar'}):iconBeforeBoot(id,dock);
save();render();requestAnimationFrame(frame);if(!S.flags.welcomed){S.flags.welcomed=true;save();setTimeout(()=>notify('威信 · 妈妈','小砚，今天投了几家？','wechat','mom'),750);}
