'use strict';
// V2 orchestration: separate app accounts, persistent deliveries and installation.
const V1={initial,open,render,advance,addMsg,capture,upload,checkin,restore,finish,photo,photos,settings,call,drawCamera,submitReport,renderText:window.render_game_to_text};
Object.assign(APP_NAMES,{store:'App Store',calendar:'日历',stay:'安住验房'});
PATHS.store='M8 3l11 18 M16 3L5 21 M3 15h18';
function v2Defaults(s){GameStorage.migrateNames(s);s.edition=2;s.queue??=[];s.seq??=100;s.recruit??={};s.bissMessages??={};s.bissUnread??={};s.jobFilter??='all';s.jobQuery??='';s.social??={likes:{},comments:{},posts:[],remarks:{},bookmarks:[],muted:{},covers:{}};s.contactAccepted??=!!s.hired;s.friendRequested??=false;s.hrIntroduced??=!!s.hired;s.installed??=!!s.hired;s.install??=null;s.nav??=null;s.currentRoom??='hall';s.cameraMode??='photo';s.cameraLens??='rear';s.cameraZoom??=1;s.videoSeconds??=0;s.puzzle??={power:hasLegacy(s,'bath'),bedroom:hasLegacy(s,'bed'),mapping:false,album:false,drawer:false,plan:false,exitLocated:false,reportRevoked:false,powerCut:false,lever:false};s.breakers??=s.puzzle.power?[1,1,1]:[1,0,1];s.taskReady??=s.checked?Math.min(4,s.uploads.length):-1;s.taskSeen??=[];s.calendarYear??=2026;s.calendarMonth??=9;s.calendarDay??=13;s.onSiteLog??=[];s.sharedPhotos??=[];s.prefs??={showGrid:false};s.failedPuzzles??={};s.wxExtras??={};return s;}
function hasLegacy(s,id){return !!s.photos?.some(p=>p.room===id);}
initial=()=>v2Defaults(V1.initial());
const wasV1=!S.edition;v2Defaults(S);
if(wasV1){S.route=null;S.flags.addressSent=!!S.hired;S.flags.keyGiven=!!S.arrived;S.hrGreeting=!!S.hired;S.currentRoom=ROOMS.some(r=>r.id===S.view)?S.view:(S.photos.at(-1)?.room||'hall');if(S.hired)S.recruit.haunted={phase:'accepted'};if(!S.hired&&S.messages.hr){S.bissMessages.haunted=S.messages.hr.map(m=>({...m,at:m.at,kind:m.image?'photo':'text'}));S.recruit.haunted={phase:'reviewed'};delete S.messages.hr;delete S.unread.hr;}if(S.ending)S.puzzle={power:true,bedroom:true,mapping:true,album:true,drawer:true,plan:true,exitLocated:true,reportRevoked:S.ending==='escape',powerCut:S.ending==='escape',lever:S.ending==='escape'};}
function queueMessages(channel,id,messages,delay=1300){for(const m of messages){const obj=typeof m==='string'?{text:m}:m;S.queue.push({channel,id,remaining:obj.delay??delay,...obj});}save();refreshThread(channel,id);}
function wxQueue(id,lines,delay){queueMessages('wx',id,lines,delay);}
function appendWx(id,text,self=false,extra={}){if(id==='hr'&&!S.contactAccepted)return;V1.addMsg(id,text,self,{order:++S.seq,...extra});}
addMsg=(id,text,self=false,extra={})=>{if(self){appendWx(id,text,true,extra);return;}if(id==='hr'&&!S.contactAccepted)return;wxQueue(id,[{text,...extra}]);};
function appendBiss(id,text,self=false,extra={}){S.bissMessages[id]??=[];S.bissMessages[id].push({text,self,at:time(),order:++S.seq,...extra});if(!self&&!(S.app==='biss'&&S.view==='chat:'+id))S.bissUnread[id]=(S.bissUnread[id]||0)+1;save();}
function threadPending(channel,id){return S.queue.some(q=>q.channel===channel&&q.id===id);}
function wxUnreadTotal(){return Object.entries(S.unread).reduce((sum,[id,n])=>sum+(S.messages[id]&&(id!=='hr'||S.contactAccepted)?Math.max(0,Number(n)||0):0),0);}
function wxUnreadBadge(count,dot=false){count=Math.max(0,Number(count)||0);return count?'<b class="wx-unread-badge'+(dot?' dot':'')+'" aria-label="'+count+'条未读消息">'+(dot?'':count>99?'99+':count)+'</b>':'';}
function refreshThread(channel,id){
 if(channel==='wx'&&(S.app==='home'||S.app==='wechat'&&['','chats','contacts','discover','me','new-friends',id].includes(S.view))){
  const scroll=$('#screen .scroll'),y=scroll?.scrollTop;render();
  if(S.app==='wechat'&&S.view!==id&&y)$('#screen .scroll')?.scrollTo(0,y);
 }else if(channel==='biss'&&S.app==='biss'&&S.view==='chat:'+id)render();
}
function deliveryEvent(item){if(item.phase){S.recruit[item.id]??={};S.recruit[item.id].phase=item.phase;}if(item.event==='friend-request'){S.friendRequested=true;notify('威信 · 新的朋友','周先生请求添加你为朋友。','wechat','new-friends');}if(item.event==='hr-introduced'){S.hrIntroduced=true;}if(item.event==='task'){S.taskReady=Math.max(S.taskReady,item.task);notify('安住验房','新任务：'+room(ROOMS[item.task].id).subtitle,'stay','task:'+ROOMS[item.task].id);}if(item.event==='arrived'){S.arrived=true;notify('地图','已到达槐安里6栋。','map');}save();}
function stepDeliveries(ms){if(!S.queue.length)return;const q=S.queue[0];q.remaining-=ms;if(q.remaining>0)return;S.queue.shift();if(q.channel==='wx'&&q.text!==undefined){appendWx(q.id,q.text,!!q.self,q);if(!q.self&&!q.system&&(q.forceNotify||!(S.app==='wechat'&&S.view===q.id)))notify('威信 · '+(PEOPLE[q.id]?.name||'消息'),q.text,'wechat',q.id);}if(q.channel==='biss'&&q.text!==undefined){appendBiss(q.id,q.text,false,q);if(!(S.app==='biss'&&S.view==='chat:'+q.id))notify('biss直聘 · '+(getJob(q.id)?.hr||''),q.text,'biss','chat:'+q.id);}deliveryEvent(q);refreshThread(q.channel,q.id);if(q.event==='friend-request'&&S.app==='wechat'&&S.view==='new-friends')render();}
function stageTask(index){if(index>=ROOMS.length||S.taskReady>=index||S.queue.some(q=>q.event==='task'&&q.task===index))return;queueMessages('app','stay',[{event:'task',task:index,delay:1700}]);}
function gatedRoom(id){if(!S.checked||!S.installed)return false;const i=ROOMS.findIndex(x=>x.id===id);if(i>S.taskReady)return false;if(id==='bath'&&!S.puzzle.power)return false;if(id==='bed'&&!S.puzzle.bedroom)return false;return true;}
unlocked=id=>gatedRoom(id);
function enteredApp(app,view){if(app==='stay'&&!S.installed){open('store','app:stay');return false;}if(app==='wechat'&&view==='hr'&&!S.contactAccepted){open('wechat','new-friends');return false;}if(app==='camera'&&view&&ROOMS.some(r=>r.id===view)){if(gatedRoom(view))S.currentRoom=view;view='';}return true;}
open=(app,view='')=>{if(!enteredApp(app,view))return;if(app==='biss'&&view.startsWith('chat:'))S.bissUnread[view.slice(5)]=0;if(app==='camera')view='';V1.open(app,view);};
function v2Home(){const apps=['wechat','biss','store','camera','photos','browser','map','settings','notes','calendar','clock','files'];if(S.installed)apps.push('stay');return `<div class="home v2home"><div class="widgets">${B('weather','<span>临川</span><strong>18°</strong><small>小雨 · 体感16°</small><small>最高20°　最低16°</small>','widget weather')}${B('open',`<small>星期${S.time>=1440?'一':'日'}</small><strong>${S.time>=1440?'14':'13'}</strong><span>${S.hired?'今晚：房源体验':'今天没有日程'}</span>`,'widget calendar',{app:'calendar'})}</div><div class="apps">${apps.map(id=>appIcon(id)).join('')}</div><div class="home-spacer"></div>${B('open','⌕ 搜索','home-search',{app:'browser'})}<div class="dock">${['phone','wechat','browser','camera'].map(id=>appIcon(id,true)).join('')}</div></div>`;}
function storeView(){return appHeader('App Store','home')+`<div class="scroll store-page"><div class="store-heading"><small>9月13日 星期日</small><h2>搜索</h2></div><form id="store-search" class="searchbox">${I('search')}<input id="store-query" aria-label="搜索App" placeholder="游戏、App、故事等" value="${S.view?'安住验房':''}"></form>${S.view==='app:stay'||S.hrIntroduced?`<div class="store-app"><div class="appicon stay">${I('home')}</div><div><h3>安住验房</h3><p>房源体验与影像记录</p></div>${B(S.installed?'store-open':S.install?'store-cancel':'install',S.installed?'打开':S.install?Math.floor(S.install.elapsed/4500*100)+'%':'获取','get-app')}</div><div class="store-stats"><span><b>4.7</b>326个评分</span><span><b>17+</b>年龄</span><span><b>安住</b>开发者</span></div><div class="store-preview"><small>ANZHU INSPECTION</small><h2>一份房屋档案<br>从真实记录开始。</h2><div class="store-fake-task">现场任务　⌁<hr>影像采集　·　问题记录　·　交付报告</div></div><h3>关于此App</h3><p>接收体验任务、整理现场影像、查看房屋资料和提交报告。支持从系统相机拍摄并选择照片附件。</p><h3>版本 2.4.1</h3><p>改进现场记录与任务提醒体验。</p>`:'<p class="empty">在上方输入App名称搜索。</p>'}</div>`;}
function calendarViewV2(){const y=S.calendarYear,m=S.calendarMonth,first=(new Date(y,m-1,1).getDay()+6)%7,total=new Date(y,m,0).getDate();return appHeader('日历','home')+`<div class="scroll pad calendar-v2"><form id="calendar-jump"><input type="number" id="calendar-year" min="1950" max="2099" value="${y}" aria-label="年份"><select id="calendar-month" aria-label="月份">${Array.from({length:12},(_,i)=>`<option ${m===i+1?'selected':''} value="${i+1}">${i+1}月</option>`).join('')}</select><button type="submit">前往</button></form><div class="calendar-month"><h2>${y}年${m}月</h2>${B('month-prev',I('back'))}${B('month-next',I('next'))}</div><div class="calendar-grid">${'一二三四五六日'.split('').map(d=>`<small>${d}</small>`).join('')}${'<span></span>'.repeat(first)}${Array.from({length:total},(_,i)=>B('calendar-day',String(i+1),S.calendarDay===i+1?'selected':'',{day:i+1})).join('')}</div><h3>${m}月${S.calendarDay}日　星期${'日一二三四五六'[new Date(y,m-1,S.calendarDay).getDay()]}</h3><p class="muted">${y===2026&&m===9?'周五 · 房租缴费':'当天没有日程'}</p></div>`;}
function installStep(ms){if(!S.install)return;S.install.elapsed+=ms;if(S.install.elapsed>=4500){S.installed=true;S.install=null;save();if(S.app==='store')render();notify('App Store','安住验房已安装。','store','app:stay');}else if(S.app==='store'){const b=$('[data-action="store-cancel"]');if(b)b.textContent=Math.floor(S.install.elapsed/4500*100)+'%';}}
advance=ms=>{V1.advance(ms);if(document.hidden)return;stepDeliveries(ms);installStep(ms);if(typeof navigationStep==='function')navigationStep(ms);if(S.recording){S.videoSeconds+=ms/1000;const t=$('#video-time');if(t)t.textContent='● '+String(Math.floor(S.videoSeconds/60)).padStart(2,'0')+':'+String(Math.floor(S.videoSeconds%60)).padStart(2,'0');}};
restore=()=>{let cp;try{cp=JSON.parse(localStorage.getItem(CHECKPOINT));}catch{}if(!cp)return sheet('还没有检查点','<p>接受试岗并进入房源后会自动保存检查点。</p>');const settings=S.settings;S=v2Defaults({...initial(),...cp,settings,ending:null});S.queue=[];R.scareLeft=0;$('#scare').className='';open(S.installed?'stay':'biss');save();};
Object.assign(VIEWS,{home:v2Home,store:storeView,calendar:calendarViewV2});
Object.assign(ACTIONS,{install:()=>{if(!S.hrIntroduced)return sheet('获取App','<p>可先在biss直聘与负责人沟通，确认体验安排后再下载。</p>');if(!S.installed&&!S.install){S.install={elapsed:0};save();render();}},'store-open':()=>open('stay'),'store-cancel':()=>{S.install=null;save();render();},'restore-now':()=>restore(),'month-prev':()=>{if(--S.calendarMonth<1){S.calendarMonth=12;S.calendarYear--;}save();render();},'month-next':()=>{if(++S.calendarMonth>12){S.calendarMonth=1;S.calendarYear++;}save();render();},'calendar-day':d=>{S.calendarDay=Number(d.day);save();render();},'reset-now':()=>{const settings=S.settings;S=initial();S.settings=settings;try{localStorage.removeItem(CHECKPOINT);}catch{}R.scareLeft=0;$('#scare').className='';open('home');save();notify('威信 · 妈妈','小砚，今天投了几家？','wechat','mom');}});
document.addEventListener('submit',e=>{if(e.target.id==='store-search'){const q=$('#store-query').value.trim();if(/安住|验房|试睡/.test(q))open('store','app:stay');else sheet('没有找到App','<p>可以按周先生发来的名称搜索。</p>');}if(e.target.id==='calendar-jump'){S.calendarYear=Math.max(1950,Math.min(2099,Number($('#calendar-year').value)||2026));S.calendarMonth=Number($('#calendar-month').value);save();render();}});


