'use strict';
const TASK_COPY=['站在玄关内，拍全入户门、门锁和左侧鞋柜。请保留未经处理的原片。','拍全客厅沙发、窗帘及窗框。请勿挪动屋主物品。','浴室恢复照明后，正对洗手台镜面拍摄。','解锁主卧，降低镜头，拍摄床沿和床底。','返回玄关，复拍门锁及鞋柜。请与第一张留档对照。'];
function stayTabs(id){return `<nav class="bottomtabs stay-tabs">${[['tasks','files','现场任务'],['onsite','home','现场'],['docs','notes','资料'],['account','user','我的']].map(([v,i,t])=>B('stay-tab',I(i)+`<span>${t}</span>`,id===v?'active':'',{view:v})).join('')}</nav>`;}
function stayV2(){if(!S.installed)return storeView();if(S.view==='report')return reportV2();if(S.view.startsWith('task:'))return taskDetail(S.view.slice(5));if(S.view==='onsite')return onsiteView();if(S.view==='docs')return docsView();if(S.view==='account')return appHeader('我的','home')+`<div class="scroll pad"><div class="card">${AV('self')}<h2>林砚</h2><p>体验员 · 临时试岗</p><p>进行中 1　已结算 0</p></div>${B('contract','查看试岗预约单','setting')}${B('hint','现场帮助','setting')}${B('open','手机设置','setting',{app:'settings'})}</div>`+stayTabs('account');return appHeader('现场任务','home')+`<div class="scroll stay-v2"><div class="stayhero"><small>ANZHU · INSPECTION</small><h2>槐安里 · 6栋604</h2><p>${S.checked?'现场记录中 · 体验员 林砚':S.flags.addressSent?'9月13日 23:50 — 次日06:00':'等待负责人同步预约地址'}</p></div><div class="pad">${!S.checked?`<div class="card"><h3>报到与入户</h3><p>${S.arrived?'你站在604门外。钥匙在四位密码盒内。请先联系负责人。':'按预约时间到楼下，联系周先生获取钥匙盒密码。'}</p>${S.arrived?B('checkin','打开钥匙盒并报到','primary'):B('open','查看步行路线','primary',{app:'map'})}</div>`:''}<div class="card"><div class="eyebrow">影像采集</div><h2>${S.uploads.length} / 5 已提交</h2><div class="progressline"><i style="width:${S.uploads.length*20}%"></i></div>${ROOMS.map((r,i)=>i<=S.taskReady?B('task',`<span class="tasknum">${S.uploads.includes(r.id)?I('check'):String(i+1).padStart(2,'0')}</span><span class="tasktext"><b>${r.name}</b><small>${S.uploads.includes(r.id)?'已提交':!gatedRoom(r.id)?'需要先处理现场通行问题':'任务已收到 · '+r.subtitle}</small></span>${I('next')}`,'taskrow'+(S.uploads.includes(r.id)?' done':''),{id:r.id}):`<div class="taskrow"><span class="tasknum">${String(i+1).padStart(2,'0')}</span><span class="tasktext"><b>等待派单</b><small>完成前一项后派发</small></span>${I('lock')}</div>`).join('')}</div>${S.uploads.length===5?B('report','填写房屋体验报告','primary'):''}${S.checked?B('stay-tab','查看现场平面图与可调查物品','secondary',{view:'onsite'}):''}</div></div>`+stayTabs('tasks');}
function taskDetail(id){const r=room(id),i=ROOMS.indexOf(r);if(i>S.taskReady)return appHeader('任务','stay-home')+'<p class="empty">暂未收到此任务。</p>';if(!S.taskSeen.includes(id)){S.taskSeen.push(id);save();}return appHeader('拍摄任务 · '+String(i+1).padStart(2,'0'),'stay-home')+`<div class="scroll pad"><div class="card"><small class="eyebrow">${S.uploads.includes(id)?'已完成':'待记录'}</small><h2>${r.subtitle}</h2><p>${TASK_COPY[i]}</p><p class="muted">上传方式：使用系统相机拍照，返回本页选择原片。</p>${gatedRoom(id)?B('task-camera','前往位置并打开相机','primary',{id}):B('stay-tab',id==='bath'?'去现场检查配电箱':'去现场检查主卧门锁','primary',{view:'onsite'})}</div><div class="card"><h3>照片附件</h3>${hasPhoto(id)?`<img class="task-attachment" src="assets/${r.photo}" alt="${r.name}已拍摄原片">${B('view-photo','放大检查原片','secondary',{id})}${B('submit-photo',S.uploads.includes(id)?'已提交':'提交这张原片','primary',{id})}`:'<p>尚未选择照片。</p>'+B('select-task-photo','从照片中选择','secondary',{id})}</div></div>`;}
function codeSheet(kind,title,copy){sheet(title,`<p>${copy}</p><form id="puzzle-form" data-kind="${kind}"><label class="formfield">输入四位数字<input id="puzzle-code" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" minlength="4" required autocomplete="off" aria-label="四位密码"></label><p id="puzzle-error" class="error"></p><button class="primary" type="submit">确认</button></form>`);}
checkin=()=>{if(!S.arrived||S.checked)return;if(!S.flags.keyGiven)return sheet('钥匙盒','<p>盒上有四位密码转轮。周先生还没有发来密码。</p>'+B('chat','联系周先生','primary',{id:'hr'}));codeSheet('entry','门口钥匙盒','金属盒里有一把604的钥匙。转轮上需要四位数字。');};
function enterHouse(){S.checked=true;S.currentRoom='hall';S.time=Math.max(S.time,1438);S.breakers=[1,0,1];S.breakerSteps=0;S.taskReady=-1;S.onSiteLog.push(time()+' 用钥匙进入604。');close();stageTask(0);open('stay');checkpoint();tone('knock');}
function cameraV2(){return `<div class="camera-top">${B('home',I('back'),'',{label:'离开相机'})}${B('flash',I('flash'),S.flash?'camera-yellow':'',{label:'闪光灯'})}${B('camera-grid',S.prefs.grid?'网格开':'网格关')}${B('camera-help',I('dots'),'',{label:'相机设置'})}</div><div class="viewfinder camera-native ${S.prefs.grid?'with-grid':''}"><canvas id="camera-canvas" aria-label="实时取景"></canvas><div class="focus" id="native-focus"></div>${S.recording?'<span id="video-time">● 00:00</span>':''}<div class="lens-controls">${[.5,1,2].map(z=>B('camera-zoom',z+'×',S.zoom===z?'selected':'',{zoom:z})).join('')}</div></div><div class="camera-bottom"><div class="camera-modes">${[['video','视频'],['photo','照片'],['portrait','人像']].map(([m,t])=>B('camera-mode',t,S.cameraMode===m?'selected':'',{mode:m})).join('')}</div><div class="shutterbar">${B('latest-photo',S.photos.length?`<img src="assets/${room(S.photos.at(-1).room).photo}" alt="最近照片">`:I('photos'),'thumb')}${B('native-shutter','',`shutter ${S.cameraMode==='video'?'video-shutter':''} ${S.recording?'recording':''}`,{label:S.cameraMode==='video'?'录制':'拍照'})}${B('camera-flip',I('rotate'),'',{label:'切换前后摄像头'})}</div></div>`;}
drawCamera=()=>{const c=$('#camera-canvas');if(!c)return;const src=S.lens==='front'?(typeof selfieAsset==='function'?selfieAsset():'selfie-player-home.png'):S.checked?room(S.currentRoom).live:'wx-cover-lin-v6.png',img=loadImage(src);const draw=()=>{if(!c.isConnected)return;const rc=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);c.width=rc.width*dpr;c.height=rc.height*dpr;const ctx=c.getContext('2d');ctx.fillStyle='#090b0b';ctx.fillRect(0,0,c.width,c.height);const scale=Math.max(c.width/img.naturalWidth,c.height/img.naturalHeight)*(S.zoom===.5?.8:S.zoom);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);};if(img.complete&&img.naturalWidth)draw();else img.addEventListener('load',draw,{once:true});};
capture=id=>{if(R.busy||S.ending)return;if(S.lens==='front'||!S.checked){S.savedImages.push(S.lens==='front'?'player-avatar.png':'wx-cover-lin-v6.png');save();tone('shutter');return notify('照片','照片已保存到最近项目。','photos');}if(!gatedRoom(id))return;R.busy=true;const first=!hasPhoto(id);if(first){S.photos.push({room:id,at:time()});nowAdd(id==='hall'?1:7);if(id==='bed'&&!S.flags.falseMom){S.flags.falseMom=true;wxQueue('mom',['小砚，妈来接你了。','就在门外，把门开一下。']);}if(id==='door')tone('knock');save();checkpoint();}tone('shutter');if(S.flash&&S.settings.intense){$('#flash').className='on';setTimeout(()=>$('#flash').className='',260);}setTimeout(()=>{R.busy=false;render();if(first&&id==='bed')scare('镜头下面，有人托住了你的手。');},300);};
upload=id=>{if(!hasPhoto(id)||!S.taskSeen.includes(id))return;if(S.uploads.includes(id))return open('stay','task:'+id);if(ROOMS[S.uploads.length]?.id!==id)return sheet('附件顺序','<p>请先完成前一项任务。</p>');S.uploads.push(id);stageTask(S.uploads.length);if(id==='bed')wxQueue('hr',['回玄关把门锁复拍一张。今晚补贴加到1800，报告填完就能走。']);if(id==='door')wxQueue('hr',['报告选“房内无人，本人独住”。确认入住就结款。']);S.onSiteLog.push(time()+' 已提交'+room(id).name+'原片。');save();checkpoint();open('stay');notify('安住验房','原片已保存至房屋档案。','stay');};
function photoV2(){return V1.photo().replace('发给雇主','用于现场任务').replace('查看清单','查看任务');}
function photosV2(){return V1.photos().replace('</div>', '</div>')+((S.savedImages||[]).length?`<div class="saved-photo-strip">${S.savedImages.map((a,i)=>B('saved-view',`<img src="assets/${a}" alt="保存的照片">`,'',{index:i})).join('')}</div>`:'');}
function planSvg(old=false){return `<svg class="floorplan" viewBox="0 0 320 270" role="img" aria-label="${old?'2011年原始户型：主卧西侧有储藏间连通消防楼梯':'现售户型：玄关、客厅、浴室、主卧，主卧西侧墙线异常加厚'}"><rect x="15" y="15" width="290" height="240" fill="#f8f5e9" stroke="#4e665c" stroke-width="5"/><path d="M15 160H305 M180 15V255 M15 215H180" stroke="#4e665c" stroke-width="4" fill="none"/><path d="M${old?'70':'45'} 15V160" stroke="#6f8378" stroke-width="${old?'3':'24'}"/><text x="93" y="85">主卧</text><text x="225" y="85">客厅</text><text x="84" y="193">浴室</text><text x="81" y="242">玄关</text><text x="224" y="215">厨房</text>${old?'<text transform="translate(43 45) rotate(90)" font-size="12">储藏间 → 消防楼梯</text>':''}<text x="21" y="284">西 ←　　北 ↑</text></svg>`;}
function onsiteView(){if(!S.checked)return appHeader('现场','home')+'<p class="empty">报到后可以记录房屋现场。</p>'+stayTabs('onsite');return appHeader('现场 · 604','stay-home')+`<div class="scroll pad onsite"><p class="muted">当前位置：${room(S.currentRoom).name}　·　选择物品进行调查</p>${planSvg()}<div class="onsite-grid">${[['meter','配电箱','clue-meter.png'],['bed-lock','主卧电子锁','bed.png'],['drawer','床头抽屉','clue-drawer.png'],['wall','衣柜与墙面','clue-wall.png']].map(([id,t,img])=>B('inspect',`<img src="assets/${img}" alt="${t}"><b>${t}</b>`,'',{id})).join('')}</div>${B('front-door','检查入户门','setting')}${S.puzzle.exitLocated?B('hidden-exit','检查暗门与机械拉杆','setting'):''}<div class="card"><h3>现场记录</h3>${S.onSiteLog.map(t=>`<p>${esc(t)}</p>`).join('')||'<p>暂无调查记录。</p>'}</div></div>`+stayTabs('onsite');}
function docsView(){return appHeader('房屋资料','stay-home')+`<div class="scroll pad"><div class="card"><h3>房源管理资料</h3>${B('doc-meter','浴室灯控 · 复位说明','setting')}${B('doc-current','现售户型图','setting')}${B('doc-history','上一位体验员的留档留言','setting')}${S.puzzle.drawer?B('doc-diary','沈秋宁的工作日记','setting'):''}${S.puzzle.album?B('doc-oldplan','2011年原始户型','setting'):''}</div><div class="card"><h3>浏览器调查</h3><p>资料里只写着“槐安里6栋604”。旧小区改过名，也改过楼号。</p>${B('open','打开浏览器查地址','secondary',{app:'browser'})}</div>${S.checked?B('report','体验报告','primary'):''}</div>`+stayTabs('docs');}
function logPuzzle(text){S.onSiteLog.push(time()+' '+text);save();}
function inspect(id){if(!S.checked)return;if(id==='meter')return meterView();if(id==='bed-lock'){if(S.puzzle.bedroom)return sheet('主卧门锁','<p>门已打开。锁后贴着安住的不动产标签。</p>'+B('task','查看主卧拍摄任务','primary',{id:'bed'}));if(S.taskReady<3)return sheet('主卧门锁','<p>门被锁住了。当前还没有主卧拍摄任务。</p>');return codeSheet('bedroom','主卧电子锁','锁背贴着字条：“密码沿用最后验收日，月日在前后各两位。”周先生的朋友圈保存着旧验收记录。');}if(id==='drawer'){if(!S.puzzle.bedroom)return sheet('床头抽屉','<p>需要先打开主卧门。</p>');if(S.puzzle.drawer)return diaryView();return codeSheet('drawer','床头柜密码锁','抽屉上的布签写着：“我们成家的日子”。日历旁贴着博客地址：秋宁的小屋。');}if(id==='wall'){if(!S.puzzle.bedroom)return sheet('衣柜','<p>主卧门还锁着。</p>');return sheet('衣柜后面的墙',`<p>你摸到衣柜后有一条缝。现售户型图与旧房原始图纸似乎不一致。</p>${S.puzzle.album?planSvg(true)+`<p>对照当前户型，消失的空间在哪？</p>${['主卧西侧','厨房北侧','浴室南侧'].map((t,i)=>B('compare-plan',t,'secondary',{index:i})).join('')}`:B('open','查找旧房的原始资料','primary',{app:'browser'})}`);}}
function meterView(){return sheet('配电箱',`<img class="clue-photo" src="assets/clue-meter.png" alt="照明、浴室、门禁三路开关"><p>灯罩内有嗡嗡声。面板下贴着复位说明。</p><div class="breaker-row">${['客厅照明','浴室照明','门禁回路'].map((t,i)=>B('breaker',`<span>${t}</span><b>${S.breakers[i]?'I 开':'O 关'}</b>`,S.breakers[i]?'on':'',{index:i})).join('')}</div>${B('doc-meter','阅读复位说明','secondary')}${S.puzzle.power?'<p>浴室照明已经恢复。</p>':'<p class="muted">浴室支路处于锁定状态，需要按顺序复位。</p>'}`);}
function flipBreaker(index){if(!S.puzzle.power){const steps=[[2,0],[1,1],[2,1]],next=steps[S.breakerSteps||0];S.breakers[index]=S.breakers[index]?0:1;if(index===next[0]&&S.breakers[index]===next[1])S.breakerSteps=(S.breakerSteps||0)+1;else{S.breakerSteps=0;S.breakers=[1,0,1];tone('knock');}if(S.breakerSteps===3){S.puzzle.power=true;S.breakers=[1,1,1];logPuzzle('按停门禁→开浴室→恢复门禁的顺序，浴室照明恢复。');}}else{S.breakers[index]=S.breakers[index]?0:1;if(index===2){S.puzzle.powerCut=S.breakers[2]===0;if(S.puzzle.powerCut)logPuzzle('门禁回路已断开，墙里的电磁锁停止了嗡鸣。');}}save();meterView();}
function diaryView(){sheet('工作日记 · 2018年6月13日',`<img class="clue-photo" src="assets/clue-drawer.png" alt="抽屉里的工作日记、钥匙和婚礼信封"><p>扉页：<strong>沈秋宁</strong>，裁缝。下面别着一把黄铜钥匙。</p><p>“原来的储藏间改成衣柜后，维修通道就被封在后面了。他又换了锁。只有断掉门禁回路，才拉得动机械插销。钥匙我藏在自己的抽屉里。”</p><p>“我的蓝燕子绣样还压在床下。等这件衣服做完，我就走。”</p><p class="muted">日记停在6月13日。黄铜钥匙已收好。</p>`);}
const WEB2={
 address:{title:'槐安里社区 · 新旧门牌对应查询',source:'临川社区服务站',body:()=>`<h2>槐安里新旧门牌对应查询</h2><p>2021年社区整治后，槐安二村更名为槐安里，楼号重新编排。室号未改。</p><label class="formfield">现楼号<select id="building-number"><option value="1">1栋</option><option value="3">3栋</option><option value="6">6栋</option><option value="8">8栋</option></select></label>${B('lookup-building','查询旧门牌','primary')}${S.puzzle.mapping?'<blockquote>槐安里6栋604 → 槐安二村3幢604</blockquote>':''}`},
 news:{title:'槐安二村一居民家中身亡，邻居曾听见求救',source:'临川晚报 · 2018年6月15日',body:()=>`<div class="masthead">临川晚报 · 旧报存档</div><h2>槐安二村一居民家中身亡</h2><p>2018年6月14日凌晨，槐安二村3幢604发生一起非正常死亡事件。死者沈秋宁，女，32岁，经营服装修改铺。</p><p>邻居称夜里听见女子拍门求救，但入户门没有打开。家属称门锁完好。相关情况仍在调查。</p><p>邻居记得她爱穿红布鞋，常在个人博客“秋宁的小屋”分享针线活和生活。卧室西墙在婚后装修时改动过。</p>`},
 blog:{title:'秋宁的小屋 · 周末，我们结婚啦',source:'秋宁的小屋 · 2011年9月20日 星期二',body:()=>`<h2>周末，我们结婚啦</h2><small>2011年9月20日 · 星期二 · 秋宁</small><p>这周六就是婚礼了！收拾房子到半夜，终于有自己的小家。以后重要的东西都用这个日子做密码，就不怕忘啦。</p><p>婚礼相册设了问题，里面还有买房时留下的原始图纸。朋友们记得来呀。</p>${S.puzzle.album?B('doc-oldplan','查看婚礼相册里的原始户型','primary'):B('album-unlock','打开私密婚礼相册','primary')}<p class="muted">密保问题：婚礼月日（四位数字）</p>`},
 forum:{title:'住过604的人：写给下一个进去的人',source:'临川夜话 · 用户 许青 · 2024年11月',body:()=>`<h2>我没有签那张入住声明</h2><p>我在604做过试睡。周姓负责人说拍完就能走，最后却让你签“唯一住户”。他在找人顶替原来的居住人。</p><p>想撤销，先把每处异常留在原片上，核实她的名字，再把照片交给屋外的人保留。报告写明房内还有她，拒绝变更居住人。</p><p>撤销报告只能断掉他手里的登记，打不开屋门。我当年是从封掉的维修通道逃出去的。门禁失电后，用钥匙释放拉杆。</p><p>别听门外亲人的声音。打一个真正的电话。那东西只能学你手机里最熟悉的称呼。</p>`},
 company:{title:'安住不动产 · 房源体验员招聘',source:'企业信息',body:()=>'<h2>安住不动产</h2><p>房屋租赁、居住体验、房源管理。槐安里体验项目由周先生负责。</p><p>企业页面最后更新于2020年。联系电话多次变更。</p>'}
};
function webHits(){const q=S.query;let ids=[];if(/槐安里|604|门牌|楼号/.test(q))ids.push('address');if(S.puzzle.mapping&&/槐安二村|沈秋宁|旧报|身亡/.test(q))ids.push('news');if(/秋宁|博客|婚礼/.test(q))ids.push('blog');if(/住过604|许青|夜话/.test(q))ids.push('forum');if(/安住|周先生|公司/.test(q))ids.push('company');return [...new Set(ids)];}
function browserV2(){if(S.view.startsWith('article:')){const id=S.view.slice(8),a=WEB2[id];return appHeader(a?.source||'网页','search-back',B('bookmark',I('heart')))+`<div class="scroll article">${a?.body()||'<p>该链接已过期，请重新搜索。</p>'}</div>`;}return appHeader('浏览器','home',B('history',I('clock')))+`<div class="scroll" style="background:white"><div class="browser-home"><h2>搜<span>一下</span></h2><form class="search-form" id="search-form"><div class="searchbox">${I('search')}<input id="search-input" aria-label="搜索关键词" placeholder="搜索网页、人物、地点" value="${esc(S.query)}"></div><button type="submit">搜索</button></form></div><div class="search-results">${S.query?webHits().map(id=>B('web-article',`<small>${WEB2[id].source}</small><h3>${WEB2[id].title}</h3><p>查看网页内容 ›</p>`,'result',{id})).join('')||'<p class="empty">没有匹配结果。试着使用文件里的原地址或完整人名。</p>':`<p class="muted">最近搜索</p>${S.history.slice(-8).reverse().map(q=>B('search-term',esc(q),'setting',{q})).join('')}`}</div></div>`;}
function reportV2(){return appHeader('房屋体验报告','stay-home')+`<div class="scroll pad"><div class="card"><h2>试睡结果确认</h2><p>房源：槐安里6栋604<br>报酬：1800元（含夜间补贴）</p><p class="muted">签署结果将更新房屋居住人登记。</p></div>${S.puzzle.reportRevoked?`<div class="card"><h3>登记已撤销</h3><p>原居住人：沈秋宁。你不再是登记候选人。但入户门依然锁着，需要从原始户型中的维修通道离开。</p>${B('stay-tab','返回现场寻找出口','primary',{view:'onsite'})}</div>`:`<form id="report-form"><label class="formfield">房屋居住情况<select id="report-finding"><option value="unknown">请选择</option><option value="alone" ${S.report.finding==='alone'?'selected':''}>房内无人，本人独住</option><option value="occupied" ${S.report.finding==='occupied'?'selected':''}>存在其他居住者，拒绝变更登记</option></select></label><label class="formfield">其他居住者姓名<input id="resident-name" value="${esc(S.report.name)}" placeholder="核对身份后填写"></label><p>影像附件 ${S.uploads.length}/5　异常标注 ${['living','bath','bed'].filter(id=>S.marks[id]).length}/3</p><p id="report-error" class="error"></p><button class="primary" type="submit">提交并签署</button></form>`}</div>`;}
submitReport=()=>{S.report.finding=$('#report-finding').value;S.report.name=$('#resident-name').value.trim();save();const err=$('#report-error');if(S.uploads.length<5){err.textContent='影像未齐，请先完成5项任务。';return;}if(S.report.finding==='unknown'){err.textContent='请选择居住情况。';return;}if(S.report.finding==='alone')return sheet('确认登记为唯一住户','<p>我确认屋内没有其他居住者，同意将本人登记为604唯一住户。</p>'+B('sign-alone','确认入住，领取1800元','danger')+B('close','返回修改','secondary'));if(S.report.name!=='沈秋宁'||!S.puzzle.drawer){err.textContent='需要从现场的个人物品与旧报道交叉核实原住户身份。';return;}if(['living','bath','bed'].some(id=>!S.marks[id])){err.textContent='请在客厅、浴室、卧室照片上标记人影。';return;}if(!S.flags.shared){err.textContent='原片仍只有屋内的人和雇主能看到。请给可信的外部联系人备份。';return;}if(!S.read.includes('forum')){err.textContent='登记条款无法正常撤回。上一位体验员似乎留下了处理办法。';return;}S.puzzle.reportRevoked=true;logPuzzle('核实沈秋宁身份并提交异常，居住人变更已撤销。');checkpoint();open('stay','report');tone('knock');};
function hiddenExit(){if(!S.puzzle.exitLocated)return;sheet('衣柜后的维修通道',`<img class="clue-photo" src="assets/clue-wall.png" alt="衣柜后的暗道与黄铜机械拉杆"><p>${!S.puzzle.reportRevoked?'手机上仍显示“等待确认入住”。通道里传来一声与你同时响起的呼吸。先处理那份登记。':!S.puzzle.powerCut?'拉杆纹丝不动，锁盒仍在发出电磁嗡鸣。':!S.puzzle.drawer?'锁孔是黄铜色的，需要找匹配的钥匙。':S.puzzle.lever?'拉杆已经落下，狭窄的台阶通向楼下。':'锁盒安静了。抽屉里的黄铜钥匙恰好能插进去。'}</p>${S.puzzle.reportRevoked&&S.puzzle.powerCut&&S.puzzle.drawer?B(S.puzzle.lever?'escape-stairs':'release-lever',S.puzzle.lever?'沿消防楼梯下楼':'插入黄铜钥匙，释放拉杆','primary'):B('close','继续调查','secondary')}`);}
function puzzleSubmit(kind,value){const codes={entry:'0614',bedroom:'1024',album:'0924',drawer:'0924'};if(value!==codes[kind]){S.failedPuzzles[kind]=(S.failedPuzzles[kind]||0)+1;save();$('#puzzle-error').textContent='密码不正确。'+({entry:'核对周先生发来的数字。',bedroom:'验收帖发出那天不是验收当天，查看日历。',album:'“这周六”要结合帖子年份和日期。',drawer:'布签说的是婚礼当天，试试查她的旧博客。'}[kind]);tone('knock');return;}if(kind==='entry')return enterHouse();if(kind==='bedroom'){S.puzzle.bedroom=true;logPuzzle('从周先生2020年10月20日的朋友圈推算验收日为10月24日，打开主卧。');close();open('stay','onsite');}if(kind==='album'){S.puzzle.album=true;logPuzzle('根据2011年9月20日的博客推算婚礼为9月24日，恢复原始户型。');close();sheet('婚礼相册 · 房子最初的样子',planSvg(true)+'<p>2011年9月24日，秋宁与家人搬进新家。原图主卧西侧有一间储藏间，连通楼外消防楼梯。</p>');}if(kind==='drawer'){if(!S.puzzle.bedroom)return;S.puzzle.drawer=true;logPuzzle('打开床头抽屉，找到沈秋宁的日记、黄铜钥匙与蓝燕子绣样。');close();diaryView();}save();checkpoint();}
const houseHint=()=>{const text=!S.hired?'在biss里主动打招呼，然后发送简历。':!S.contactAccepted?'去威信的通讯录 → 新的朋友，接受周先生。':!S.hrIntroduced?'给刚加上的周先生先发一句问候。':!S.installed?'到App Store搜索“安住验房”并获取。':!S.flags.addressSent?'回威信告诉周先生下载好了，索取地址。':!S.arrived?'在地图开始步行，蓝色定位点会沿道路移动。':!S.checked?'到楼下后主动联系周先生，钥匙盒密码在他的回复里。':S.taskReady<0?'第一项任务正在派发，稍候查看安住验房。':S.taskReady>=2&&!S.puzzle.power?'资料页有灯控复位说明，按顺序操作三路开关。':S.taskReady>=3&&!S.puzzle.bedroom?'查看周先生个人朋友圈的验收帖子，用手机日历计算“这周六”。':!S.puzzle.mapping?'浏览器查槐安里的新旧门牌，旧报道不会用新地址。':!S.puzzle.album?'旧报道提到了秋宁的博客，相册问题要结合2011年的日历。':!S.puzzle.drawer?'卧室抽屉的布签写着“我们成家的日子”。':!S.puzzle.exitLocated?'比较现售与原始户型图，找消失的空间。':S.uploads.length<5?'回到安住验房完成剩余拍摄；在任务页提交原片。':!S.puzzle.reportRevoked?'核实原住户姓名、标出三处人影、把照片发给小张是好bro，并阅读上一位体验员的帖子。':!S.puzzle.powerCut?'维修通道的电磁锁还通着电，检查门禁回路。':!S.puzzle.lever?'用抽屉里的钥匙释放暗门拉杆。':'沿维修通道的消防楼梯离开。';sheet('现场帮助','<p>'+text+'</p>');};
Object.assign(VIEWS,{stay:stayV2,camera:cameraV2,photo:photoV2,photos:photosV2,browser:browserV2});
Object.assign(ACTIONS,{
 'stay-tab':d=>open('stay',d.view==='tasks'?'':d.view),task:d=>open('stay','task:'+d.id),'task-camera':d=>{if(gatedRoom(d.id)){S.currentRoom=d.id;S.cameraMode='photo';S.lens='rear';S.zoom=1;open('camera');}},checkin:()=>checkin(),
 'select-task-photo':d=>sheet('选择照片',hasPhoto(d.id)?B('submit-photo',`<img class="task-attachment" src="assets/${room(d.id).photo}" alt="原片">选择并提交这张照片`,'primary',{id:d.id}):'<p>相册里还没有该位置的照片。请先前往拍摄。</p>'),
 'submit-photo':d=>{close();upload(d.id);},upload:d=>open('stay','task:'+d.id),
 'native-shutter':()=>{if(S.cameraMode==='video'){S.recording=!S.recording;if(!S.recording){S.videos??=[];S.videos.push({room:S.currentRoom,seconds:Math.floor(S.videoSeconds)});S.videoSeconds=0;}save();render();}else capture(S.currentRoom);},
 'camera-mode':d=>{S.recording=false;S.videoSeconds=0;S.cameraMode=d.mode;save();render();},'camera-zoom':d=>{S.zoom=Number(d.zoom);save();render();},'camera-flip':()=>{S.lens=S.lens==='rear'?'front':'rear';save();render();},'camera-grid':()=>{S.prefs.grid=!S.prefs.grid;save();render();},'camera-help':()=>sheet('相机设置','<p>闪光灯、网格、焦段和前后镜头可直接切换。照片保存在系统相册。视频保存时长记录。</p>'+B('camera-grid',S.prefs.grid?'关闭网格':'开启网格','secondary')),
 inspect:d=>inspect(d.id),breaker:d=>flipBreaker(Number(d.index)),
 'doc-meter':()=>sheet('灯控复位说明','<p>浴室灯未启动时，请依次操作：</p><p>① 门禁回路切到 O；<br>② 浴室照明切到 I；<br>③ 门禁回路恢复 I。</p><p>客厅照明保持原位。操作顺序错误，联锁会恢复初始状态。</p>'+B('inspect','返回配电箱','primary',{id:'meter'})),
 'doc-current':()=>sheet('现售户型图',planSvg()+'<p>安住不动产 · 2020年归档。主卧西墙经过加厚处理。</p>'),'doc-oldplan':()=>sheet('2011年原始户型',planSvg(true)+'<p>来源：秋宁的婚礼相册。西侧储藏间与消防楼梯相连。</p>'),'doc-diary':diaryView,
 'doc-history':()=>sheet('历史体验留言','<p>许青 · 2024年11月</p><p>如果这份留言还没被删，搜“住过604的人”。不要把这条留言发给负责人。</p>'+B('search-term','在浏览器搜索“住过604的人”','primary',{q:'住过604的人'})+B('add-survivor','添加留言作者威信','secondary')),
 'add-survivor':()=>{if(!S.messages.unknown)S.messages.unknown=[{text:'你通过历史体验留言添加了许青，可以开始聊天了。',at:time(),system:true}];save();close();open('wechat','unknown');},
 'lookup-building':()=>{const n=$('#building-number').value;if(n==='6'){S.puzzle.mapping=true;logPuzzle('现6栋对应旧3幢，旧地址为槐安二村3幢604。');sheet('查询结果','<p>现门牌：槐安里6栋604<br>原门牌：<strong>槐安二村3幢604</strong><br>更名日期：2021年8月</p>'+B('search-term','搜索旧门牌','primary',{q:'槐安二村3幢604'}));}else sheet('查询结果','<p>该楼不是预约单上的6栋，请核对楼号。</p>');},
 'web-article':d=>{if(!WEB2[d.id])return;if(!S.read.includes(d.id))S.read.push(d.id);save();open('browser','article:'+d.id);},'album-unlock':()=>codeSheet('album','婚礼相册密保','问题：婚礼当天的月日？博客的发布时间可以在日历里核对。'),
 'compare-plan':d=>{if(Number(d.index)!==0)return sheet('墙线没有吻合','<p>这里的轮廓与原图相同。再对照衣柜旁加厚的西墙。</p>'+B('inspect','重新比较','primary',{id:'wall'}));S.puzzle.plan=true;S.puzzle.exitLocated=true;logPuzzle('主卧西墙吞掉了原来的储藏间，移开衣柜找到维修通道。');close();hiddenExit();},
 'front-door':()=>sheet('入户门','<p>钥匙能转，锁舌却不动。门外响起妈妈的声音：“别找了，打开就能回家。”</p>'+B('call','拨打妈妈的电话','secondary',{id:'mom'})+B('force-door','相信门外的声音，开门','danger')+B('close','离开门口','secondary')),
 'force-door':()=>{close();finish('trapped');},'hidden-exit':hiddenExit,'release-lever':()=>{if(!S.puzzle.reportRevoked||!S.puzzle.powerCut||!S.puzzle.drawer)return;S.puzzle.lever=true;logPuzzle('黄铜钥匙释放机械拉杆，消防通道打开。');save();hiddenExit();},'escape-stairs':()=>{if(S.puzzle.lever&&S.puzzle.reportRevoked&&S.puzzle.powerCut){close();finish('escape');}},escape:()=>hiddenExit(),hint:houseHint,
 'saved-view':d=>sheet('照片',`<img class="clue-photo" src="assets/${esc(S.savedImages[Number(d.index)])}" alt="保存的照片">`)
});
document.addEventListener('submit',e=>{if(e.target.id==='puzzle-form'){e.preventDefault();puzzleSubmit(e.target.dataset.kind,$('#puzzle-code').value.trim());}});
document.addEventListener('pointerdown',e=>{if(e.target.id==='camera-canvas'){const rc=e.target.getBoundingClientRect(),f=$('#native-focus');f.style.left=(e.clientX-rc.left-30)+'px';f.style.top=(e.clientY-rc.top-30)+'px';f.style.width='60px';f.style.height='60px';f.style.borderColor='#e4c36b';}});



